libpq-async++: pq_async::data_large_object Class Reference
pq_async::data_large_object Class Reference
#include <src/data_large_object.h>
Public Member Functions
bool opened ()
bool opened_read ()
bool opened_write ()
void open (lo_mode m)
int32_t read (char *buf, int32_t len)
int32_t write (const char *buf, int32_t len)
int64_t tell ()
int64_t seek (int64_t offset, lo_whence w=lo_whence::seek_cur)
void resize (int64_t new_size)
void close ()
void unlink ()
Friends
class pq_async::database
Member Function Documentation
close()
void pq_async::data_large_object::close ()
References opened().
open()
void pq_async::data_large_object::open (lo_mode m)
References pq_async::oid::data(), opened(), pq_async::read, and pq_async::write.
opened()
bool pq_async::data_large_object::opened () inline
Referenced by close(), open(), read(), resize(), seek(), tell(), unlink(), and write().
opened_read()
bool pq_async::data_large_object::opened_read () inline
opened_write()
bool pq_async::data_large_object::opened_write () inline
References pq_async::database::close(), pq_async::m, pq_async::database::open(), pq_async::read, pq_async::seek_cur, pq_async::w, and pq_async::write.
read()
int32_t pq_async::data_large_object::read (char * buf, int32_t len)
References opened().
resize()
void pq_async::data_large_object::resize (int64_t new_size)
References opened().
seek()
int64_t pq_async::data_large_object::seek (int64_t offset, lo_whence w = lo_whence::seek_cur)
References opened().
tell()
int64_t pq_async::data_large_object::tell ()
References opened().
unlink()
void pq_async::data_large_object::unlink ()
References opened().
write()
int32_t pq_async::data_large_object::write (const char * buf, int32_t len)
References opened().
Friends And Related Function Documentation
pq_async::database
friend class pq_async::database friend
The documentation for this class was generated from the following files:
src/data_large_object.h
src/data_large_object.cpp