libpq-async++: pq_async::tests::db_test_base Class Reference
pq_async::tests::db_test_base Class Reference
#include <tests/db_test_base.h>
Public Member Functions
std::string connection_string ()
void SetUp () override
void TearDown () override
Data Fields
pq_async::sp_database db
Member Function Documentation
connection_string()
std::string pq_async::tests::db_test_base::connection_string () inline
References pq_async_connection_string.
SetUp()
void pq_async::tests::db_test_base::SetUp () inline override
References pq_async::database::open(), and pq_async_connection_string.
Referenced by pq_async::tests::data_prepared_test::SetUp(), pq_async::tests::uuid_types_test::SetUp(), pq_async::tests::sys_types_test::SetUp(), pq_async::tests::char_types_test::SetUp(), pq_async::tests::bin_types_test::SetUp(), pq_async::tests::queue_test::SetUp(), pq_async::tests::database_test::SetUp(), and pq_async::tests::data_reader_test::SetUp().
TearDown()
void pq_async::tests::db_test_base::TearDown () inline override
Referenced by pq_async::tests::data_prepared_test::TearDown(), pq_async::tests::uuid_types_test::TearDown(), pq_async::tests::sys_types_test::TearDown(), pq_async::tests::char_types_test::TearDown(), pq_async::tests::bin_types_test::TearDown(), pq_async::tests::queue_test::TearDown(), pq_async::tests::database_test::TearDown(), and pq_async::tests::data_reader_test::TearDown().
Field Documentation
db
pq_async::sp_database pq_async::tests::db_test_base::db
Referenced by pq_async::tests::data_prepared_test::create_table(), pq_async::tests::data_reader_test::create_table(), pq_async::tests::queue_test::create_table(), pq_async::tests::uuid_types_test::create_table(), pq_async::tests::bin_types_test::create_table(), pq_async::tests::database_test::create_table(), pq_async::tests::char_types_test::create_table(), pq_async::tests::sys_types_test::create_table(), pq_async::tests::bin_types_test::drop_table(), pq_async::tests::data_reader_test::drop_table(), pq_async::tests::queue_test::drop_table(), pq_async::tests::sys_types_test::drop_table(), pq_async::tests::char_types_test::drop_table(), pq_async::tests::database_test::drop_table(), pq_async::tests::uuid_types_test::drop_table(), pq_async::tests::data_prepared_test::drop_table(), and pq_async::tests::TEST_F().
The documentation for this class was generated from the following file:
tests/db_test_base.h