libpq-async++: pq_async::connection_pool Class Reference
pq_async::connection_pool Class Reference
#include <src/data_connection_pool.h>
Public Member Functions
virtual ~connection_pool ()
Static Public Member Functions
static void init (bool init_ssl, bool init_crypto)
static void init (int max_connection_pool_count, bool init_ssl, bool init_crypto)
static void destroy ()
static connection_pool * instance ()
static int get_max_conn ()
static connection * get_connection (pq_async::database *owner, const std::string &connection_string, int32_t timeout_ms=5000)
static int32_t get_opened_connection_count (const std::string &connection_string)
Constructor & Destructor Documentation
~connection_pool()
pq_async::connection_pool::~connection_pool () virtual
References pq_async_log_debug.
Member Function Documentation
destroy()
static void pq_async::connection_pool::destroy () inline static
Referenced by pq_async::tests::pq_async_test_env::TearDown().
get_connection()
static connection* pq_async::connection_pool::get_connection (pq_async::database * owner, const std::string & connection_string, int32_t timeout_ms = 5000) inline static
Referenced by pq_async::connection_task::_connect(), and pq_async::database::open_connection().
get_max_conn()
static int pq_async::connection_pool::get_max_conn () inline static
Referenced by pq_async::tests::TEST_F().
get_opened_connection_count()
static int32_t pq_async::connection_pool::get_opened_connection_count (const std::string & connection_string) inline static
References pq_async::connection::lock().
init() [1/2]
void pq_async::connection_pool::init (bool init_ssl, bool init_crypto) static
Referenced by pq_async::tests::pq_async_test_env::SetUp().
init() [2/2]
void pq_async::connection_pool::init (int max_connection_pool_count, bool init_ssl, bool init_crypto) static
instance()
static connection_pool* pq_async::connection_pool::instance () inline static
Referenced by pq_async::connection_task::_connect(), pq_async::database::close(), and pq_async::database::open_connection().
The documentation for this class was generated from the following files:
src/data_connection_pool.h
src/data_connection_pool.cpp