libpq-async++: pq_async::data_table Class Reference
pq_async::data_table Class Reference
#include <src/data_table.h>
Public Member Functions
data_table ()
virtual ~data_table ()
void dispose ()
sp_data_columns_container get_columns () const
size_t col_count () const
int32_t get_col_index (const char *col_name) const
sp_data_value get_value (uint32_t row_idx, uint32_t col_id) const
sp_data_value get_value (uint32_t row_idx, const char *col_name) const
sp_data_value get_value (uint32_t row_idx, const std::string &col_name) const
bool is_null (uint32_t row_idx, const char *col_name) const
template<typename T >
T as (uint32_t row_idx, const char *col_name) const
bool as_bool (uint32_t row_idx, const char *col_name) const
bool as_bool (uint32_t row_idx, int32_t col_idx) const
std::string as_text (uint32_t row_idx, const char *col_name) const
std::string as_text (uint32_t row_idx, int32_t col_idx) const
int16_t as_int16 (uint32_t row_idx, const char *col_name) const
int16_t as_int16 (uint32_t row_idx, int32_t col_idx) const
int32_t as_int32 (uint32_t row_idx, const char *col_name) const
int32_t as_int32 (uint32_t row_idx, int32_t col_idx) const
int64_t as_int64 (uint32_t row_idx, const char *col_name) const
int64_t as_int64 (uint32_t row_idx, int32_t col_idx) const
pq_async::numeric as_numeric (uint32_t row_idx, const char *col_name) const
pq_async::numeric as_numeric (uint32_t row_idx, int32_t col_idx) const
pq_async::money as_money (uint32_t row_idx, const char *col_name) const
pq_async::money as_money (uint32_t row_idx, int32_t col_idx) const
float as_float (uint32_t row_idx, const char *col_name) const
float as_float (uint32_t row_idx, int32_t col_idx) const
double as_double (uint32_t row_idx, const char *col_name) const
double as_double (uint32_t row_idx, int32_t col_idx) const
pq_async::time as_time (uint32_t row_idx, const char *col_name) const
pq_async::time as_time (uint32_t row_idx, int32_t col_idx) const
pq_async::time_tz as_time_tz (uint32_t row_idx, const char *col_name) const
pq_async::time_tz as_time_tz (uint32_t row_idx, int32_t col_idx) const
pq_async::timestamp as_timestamp (uint32_t row_idx, const char *col_name) const
pq_async::timestamp as_timestamp (uint32_t row_idx, int32_t col_idx) const
pq_async::timestamp_tz as_timestamp_tz (uint32_t row_idx, const char *col_name) const
pq_async::timestamp_tz as_timestamp_tz (uint32_t row_idx, int32_t col_idx) const
pq_async::date as_date (uint32_t row_idx, const char *col_name) const
pq_async::date as_date (uint32_t row_idx, int32_t col_idx) const
pq_async::interval as_interval (uint32_t row_idx, const char *col_name) const
pq_async::interval as_interval (uint32_t row_idx, int32_t col_idx) const
pq_async::json as_json (uint32_t row_idx, const char *col_name) const
pq_async::json as_json (uint32_t row_idx, int32_t col_idx) const
std::vector< int8_t > as_bytea (uint32_t row_idx, const char *col_name) const
std::vector< int8_t > as_bytea (uint32_t row_idx, int32_t col_idx) const
pq_async::uuid as_uuid (uint32_t row_idx, const char *col_name) const
pq_async::uuid as_uuid (uint32_t row_idx, int32_t col_idx) const
pq_async::oid as_oid (uint32_t row_idx, const char *col_name) const
pq_async::oid as_oid (uint32_t row_idx, int32_t col_idx) const
pq_async::cidr as_cidr (uint32_t row_idx, const char *col_name) const
pq_async::cidr as_cidr (uint32_t row_idx, int32_t col_idx) const
pq_async::inet as_inet (uint32_t row_idx, const char *col_name) const
pq_async::inet as_inet (uint32_t row_idx, int32_t col_idx) const
pq_async::macaddr as_macaddr (uint32_t row_idx, const char *col_name) const
pq_async::macaddr as_macaddr (uint32_t row_idx, int32_t col_idx) const
pq_async::macaddr8 as_macaddr8 (uint32_t row_idx, const char *col_name) const
pq_async::macaddr8 as_macaddr8 (uint32_t row_idx, int32_t col_idx) const
pq_async::point as_point (uint32_t row_idx, const char *col_name) const
pq_async::point as_point (uint32_t row_idx, int32_t col_idx) const
pq_async::line as_line (uint32_t row_idx, const char *col_name) const
pq_async::line as_line (uint32_t row_idx, int32_t col_idx) const
pq_async::lseg as_lseg (uint32_t row_idx, const char *col_name) const
pq_async::lseg as_lseg (uint32_t row_idx, int32_t col_idx) const
pq_async::box as_box (uint32_t row_idx, const char *col_name) const
pq_async::box as_box (uint32_t row_idx, int32_t col_idx) const
pq_async::path as_path (uint32_t row_idx, const char *col_name) const
pq_async::path as_path (uint32_t row_idx, int32_t col_idx) const
pq_async::polygon as_polygon (uint32_t row_idx, const char *col_name) const
pq_async::polygon as_polygon (uint32_t row_idx, int32_t col_idx) const
pq_async::circle as_circle (uint32_t row_idx, const char *col_name) const
pq_async::circle as_circle (uint32_t row_idx, int32_t col_idx) const
pq_async::int4range as_int4range (uint32_t row_idx, const char *col_name) const
pq_async::int4range as_int4range (uint32_t row_idx, int32_t col_idx) const
pq_async::int8range as_int8range (uint32_t row_idx, const char *col_name) const
pq_async::int8range as_int8range (uint32_t row_idx, int32_t col_idx) const
pq_async::numrange as_numrange (uint32_t row_idx, const char *col_name) const
pq_async::numrange as_numrange (uint32_t row_idx, int32_t col_idx) const
pq_async::tsrange as_tsrange (uint32_t row_idx, const char *col_name) const
pq_async::tsrange as_tsrange (uint32_t row_idx, int32_t col_idx) const
pq_async::tstzrange as_tstzrange (uint32_t row_idx, const char *col_name) const
pq_async::tstzrange as_tstzrange (uint32_t row_idx, int32_t col_idx) const
pq_async::daterange as_daterange (uint32_t row_idx, const char *col_name) const
pq_async::daterange as_daterange (uint32_t row_idx, int32_t col_idx) const
bool is_array (uint32_t row_idx, const char *col_name) const
sp_data_value operator() (uint32_t i, const char *col_name) const
const data_row * get_row_ptr (uint32_t i) const
sp_data_row get_row_safe (uint32_t i) const
void to_json (pq_async::json &rows) const
void to_json_string (std::string &str, const unsigned int current_indent=0) const
Friends
class data_reader
Constructor & Destructor Documentation
data_table()
pq_async::data_table::data_table ()
References pq_async_log_trace.
~data_table()
pq_async::data_table::~data_table () virtual
References pq_async_log_trace.
Member Function Documentation
as()
template<typename T > T pq_async::data_table::as (uint32_t row_idx, const char * col_name) const inline
References get_value().
as_bool() [1/2]
bool pq_async::data_table::as_bool (uint32_t row_idx, const char * col_name) const inline
as_bool() [2/2]
bool pq_async::data_table::as_bool (uint32_t row_idx, int32_t col_idx) const inline
as_box() [1/2]
pq_async::box pq_async::data_table::as_box (uint32_t row_idx, const char * col_name) const inline
as_box() [2/2]
pq_async::box pq_async::data_table::as_box (uint32_t row_idx, int32_t col_idx) const inline
as_bytea() [1/2]
std::vector<int8_t> pq_async::data_table::as_bytea (uint32_t row_idx, const char * col_name) const inline
as_bytea() [2/2]
std::vector<int8_t> pq_async::data_table::as_bytea (uint32_t row_idx, int32_t col_idx) const inline
as_cidr() [1/2]
pq_async::cidr pq_async::data_table::as_cidr (uint32_t row_idx, int32_t col_idx) const inline
as_cidr() [2/2]
pq_async::cidr pq_async::data_table::as_cidr (uint32_t row_idx, const char * col_name) const inline
as_circle() [1/2]
pq_async::circle pq_async::data_table::as_circle (uint32_t row_idx, const char * col_name) const inline
as_circle() [2/2]
pq_async::circle pq_async::data_table::as_circle (uint32_t row_idx, int32_t col_idx) const inline
as_date() [1/2]
pq_async::date pq_async::data_table::as_date (uint32_t row_idx, const char * col_name) const inline
as_date() [2/2]
pq_async::date pq_async::data_table::as_date (uint32_t row_idx, int32_t col_idx) const inline
as_daterange() [1/2]
pq_async::daterange pq_async::data_table::as_daterange (uint32_t row_idx, const char * col_name) const inline
as_daterange() [2/2]
pq_async::daterange pq_async::data_table::as_daterange (uint32_t row_idx, int32_t col_idx) const inline
as_double() [1/2]
double pq_async::data_table::as_double (uint32_t row_idx, const char * col_name) const inline
as_double() [2/2]
double pq_async::data_table::as_double (uint32_t row_idx, int32_t col_idx) const inline
as_float() [1/2]
float pq_async::data_table::as_float (uint32_t row_idx, const char * col_name) const inline
as_float() [2/2]
float pq_async::data_table::as_float (uint32_t row_idx, int32_t col_idx) const inline
as_inet() [1/2]
pq_async::inet pq_async::data_table::as_inet (uint32_t row_idx, const char * col_name) const inline
as_inet() [2/2]
pq_async::inet pq_async::data_table::as_inet (uint32_t row_idx, int32_t col_idx) const inline
as_int16() [1/2]
int16_t pq_async::data_table::as_int16 (uint32_t row_idx, const char * col_name) const inline
as_int16() [2/2]
int16_t pq_async::data_table::as_int16 (uint32_t row_idx, int32_t col_idx) const inline
as_int32() [1/2]
int32_t pq_async::data_table::as_int32 (uint32_t row_idx, int32_t col_idx) const inline
as_int32() [2/2]
int32_t pq_async::data_table::as_int32 (uint32_t row_idx, const char * col_name) const inline
as_int4range() [1/2]
pq_async::int4range pq_async::data_table::as_int4range (uint32_t row_idx, const char * col_name) const inline
as_int4range() [2/2]
pq_async::int4range pq_async::data_table::as_int4range (uint32_t row_idx, int32_t col_idx) const inline
as_int64() [1/2]
int64_t pq_async::data_table::as_int64 (uint32_t row_idx, const char * col_name) const inline
as_int64() [2/2]
int64_t pq_async::data_table::as_int64 (uint32_t row_idx, int32_t col_idx) const inline
as_int8range() [1/2]
pq_async::int8range pq_async::data_table::as_int8range (uint32_t row_idx, const char * col_name) const inline
as_int8range() [2/2]
pq_async::int8range pq_async::data_table::as_int8range (uint32_t row_idx, int32_t col_idx) const inline
as_interval() [1/2]
pq_async::interval pq_async::data_table::as_interval (uint32_t row_idx, const char * col_name) const inline
as_interval() [2/2]
pq_async::interval pq_async::data_table::as_interval (uint32_t row_idx, int32_t col_idx) const inline
as_json() [1/2]
pq_async::json pq_async::data_table::as_json (uint32_t row_idx, int32_t col_idx) const inline
as_json() [2/2]
pq_async::json pq_async::data_table::as_json (uint32_t row_idx, const char * col_name) const inline
as_line() [1/2]
pq_async::line pq_async::data_table::as_line (uint32_t row_idx, const char * col_name) const inline
as_line() [2/2]
pq_async::line pq_async::data_table::as_line (uint32_t row_idx, int32_t col_idx) const inline
as_lseg() [1/2]
pq_async::lseg pq_async::data_table::as_lseg (uint32_t row_idx, int32_t col_idx) const inline
as_lseg() [2/2]
pq_async::lseg pq_async::data_table::as_lseg (uint32_t row_idx, const char * col_name) const inline
as_macaddr() [1/2]
pq_async::macaddr pq_async::data_table::as_macaddr (uint32_t row_idx, const char * col_name) const inline
as_macaddr() [2/2]
pq_async::macaddr pq_async::data_table::as_macaddr (uint32_t row_idx, int32_t col_idx) const inline
as_macaddr8() [1/2]
pq_async::macaddr8 pq_async::data_table::as_macaddr8 (uint32_t row_idx, int32_t col_idx) const inline
as_macaddr8() [2/2]
pq_async::macaddr8 pq_async::data_table::as_macaddr8 (uint32_t row_idx, const char * col_name) const inline
as_money() [1/2]
pq_async::money pq_async::data_table::as_money (uint32_t row_idx, const char * col_name) const inline
as_money() [2/2]
pq_async::money pq_async::data_table::as_money (uint32_t row_idx, int32_t col_idx) const inline
as_numeric() [1/2]
pq_async::numeric pq_async::data_table::as_numeric (uint32_t row_idx, const char * col_name) const inline
as_numeric() [2/2]
pq_async::numeric pq_async::data_table::as_numeric (uint32_t row_idx, int32_t col_idx) const inline
as_numrange() [1/2]
pq_async::numrange pq_async::data_table::as_numrange (uint32_t row_idx, const char * col_name) const inline
as_numrange() [2/2]
pq_async::numrange pq_async::data_table::as_numrange (uint32_t row_idx, int32_t col_idx) const inline
as_oid() [1/2]
pq_async::oid pq_async::data_table::as_oid (uint32_t row_idx, int32_t col_idx) const inline
as_oid() [2/2]
pq_async::oid pq_async::data_table::as_oid (uint32_t row_idx, const char * col_name) const inline
as_path() [1/2]
pq_async::path pq_async::data_table::as_path (uint32_t row_idx, const char * col_name) const inline
as_path() [2/2]
pq_async::path pq_async::data_table::as_path (uint32_t row_idx, int32_t col_idx) const inline
as_point() [1/2]
pq_async::point pq_async::data_table::as_point (uint32_t row_idx, int32_t col_idx) const inline
as_point() [2/2]
pq_async::point pq_async::data_table::as_point (uint32_t row_idx, const char * col_name) const inline
as_polygon() [1/2]
pq_async::polygon pq_async::data_table::as_polygon (uint32_t row_idx, const char * col_name) const inline
as_polygon() [2/2]
pq_async::polygon pq_async::data_table::as_polygon (uint32_t row_idx, int32_t col_idx) const inline
as_text() [1/2]
std::string pq_async::data_table::as_text (uint32_t row_idx, int32_t col_idx) const inline
as_text() [2/2]
std::string pq_async::data_table::as_text (uint32_t row_idx, const char * col_name) const inline
as_time() [1/2]
pq_async::time pq_async::data_table::as_time (uint32_t row_idx, int32_t col_idx) const inline
as_time() [2/2]
pq_async::time pq_async::data_table::as_time (uint32_t row_idx, const char * col_name) const inline
as_time_tz() [1/2]
pq_async::time_tz pq_async::data_table::as_time_tz (uint32_t row_idx, int32_t col_idx) const inline
as_time_tz() [2/2]
pq_async::time_tz pq_async::data_table::as_time_tz (uint32_t row_idx, const char * col_name) const inline
as_timestamp() [1/2]
pq_async::timestamp pq_async::data_table::as_timestamp (uint32_t row_idx, const char * col_name) const inline
as_timestamp() [2/2]
pq_async::timestamp pq_async::data_table::as_timestamp (uint32_t row_idx, int32_t col_idx) const inline
as_timestamp_tz() [1/2]
pq_async::timestamp_tz pq_async::data_table::as_timestamp_tz (uint32_t row_idx, const char * col_name) const inline
as_timestamp_tz() [2/2]
pq_async::timestamp_tz pq_async::data_table::as_timestamp_tz (uint32_t row_idx, int32_t col_idx) const inline
as_tsrange() [1/2]
pq_async::tsrange pq_async::data_table::as_tsrange (uint32_t row_idx, const char * col_name) const inline
as_tsrange() [2/2]
pq_async::tsrange pq_async::data_table::as_tsrange (uint32_t row_idx, int32_t col_idx) const inline
as_tstzrange() [1/2]
pq_async::tstzrange pq_async::data_table::as_tstzrange (uint32_t row_idx, int32_t col_idx) const inline
as_tstzrange() [2/2]
pq_async::tstzrange pq_async::data_table::as_tstzrange (uint32_t row_idx, const char * col_name) const inline
as_uuid() [1/2]
pq_async::uuid pq_async::data_table::as_uuid (uint32_t row_idx, int32_t col_idx) const inline
as_uuid() [2/2]
pq_async::uuid pq_async::data_table::as_uuid (uint32_t row_idx, const char * col_name) const inline
col_count()
size_t pq_async::data_table::col_count () const inline
dispose()
void pq_async::data_table::dispose () inline
get_col_index()
int32_t pq_async::data_table::get_col_index (const char * col_name) const inline
References get_value().
get_columns()
sp_data_columns_container pq_async::data_table::get_columns () const inline
get_row_ptr()
const data_row* pq_async::data_table::get_row_ptr (uint32_t i) const inline
get_row_safe()
sp_data_row pq_async::data_table::get_row_safe (uint32_t i) const inline
References to_json(), and to_json_string().
Referenced by get_value().
get_value() [1/3]
pq_async::sp_data_value pq_async::data_table::get_value (uint32_t row_idx, uint32_t col_id) const
References get_row_safe().
Referenced by as(), get_col_index(), get_value(), is_array(), is_null(), and operator()().
get_value() [2/3]
pq_async::sp_data_value pq_async::data_table::get_value (uint32_t row_idx, const char * col_name) const
References get_row_safe().
get_value() [3/3]
sp_data_value pq_async::data_table::get_value (uint32_t row_idx, const std::string & col_name) const inline
References get_value().
is_array()
bool pq_async::data_table::is_array (uint32_t row_idx, const char * col_name) const inline
References get_value().
is_null()
bool pq_async::data_table::is_null (uint32_t row_idx, const char * col_name) const inline
References get_value().
operator()()
sp_data_value pq_async::data_table::operator() (uint32_t i, const char * col_name) const inline
References get_value().
to_json()
void pq_async::data_table::to_json (pq_async::json & rows) const
Referenced by get_row_safe(), and to_json_string().
to_json_string()
void pq_async::data_table::to_json_string (std::string & str, const unsigned int current_indent = 0) const
References to_json().
Referenced by get_row_safe().
Friends And Related Function Documentation
data_reader
friend class data_reader friend
The documentation for this class was generated from the following files:
src/data_table.h
src/data_table.cpp