libpq-async++: pq_async::database Class Reference
pq_async::database Class Reference
#include <src/database.h>
Public Member Functions
virtual ~database ()
sp_event_strand< int > get_strand ()
sp_connection_lock open_connection (int32_t timeout_ms=5000)
synchronously try to acquire and open a connection
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &, sp_connection_lock >::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type, sp_connection_lock >::value), int32_t >::type = -1>
void open_connection (const CB &acb, int32_t timeout_ms=5000)
asynchronously try to acquire and open a connection
void close ()
release the underlying connection this call is always synchronous
bool working ()
returns true if the database is currently working.
bool in_transaction ()
returns if a transaction is in progress
void begin ()
synchronously starts a new transaction
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1>
void begin (const CB &acb)
asynchronously starts a new transaction
void commit ()
synchonously commit current transaction
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1>
void commit (const CB &acb)
asynchonously commit current transaction
void rollback ()
synchonously rollback current transaction
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1>
void roollback (const CB &acb)
asynchonously rollback current transaction
void set_savepoint (const char *name)
synchronously sets a new savepoint inside the current transaction
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1>
void set_savepoint (const CB &acb, const char *name)
asynchronously sets a new savepoint inside the current transaction
void release_savepoint (const char *name)
synchonously release the specified savepoint
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1>
void release_savepoint (const CB &acb, const char *name)
asynchonously release the specified savepoint
void rollback_savepoint (const char *name)
synchonously rollback the specified savepoint
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1>
void rollback_savepoint (const CB &acb, const char *name)
asynchonously rollback the specified savepoint
template<typename... PARAMS, typename std::enable_if< !std::is_same< int, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, int >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, int >::value), int32_t >::type = -1>
void execute (const char *sql, const PARAMS &... args)
asynchrounously process a query and returns the number of rows affected by insert, update and delete
template<typename T , typename std::enable_if< !std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, int >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, int >::value), int32_t >::type = -1>
void execute (const char *sql, const parameters &p, const T &acb)
asynchrounously process a query and returns the number of rows affected by insert, update and delete
template<typename... PARAMS, typename std::enable_if< std::is_same< int, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, int >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, int >::value), int32_t >::type = -1>
int32_t execute (const char *sql, const PARAMS &... args)
synchrounously process a query and returns the number of rows affected by insert, update and delete
int32_t execute (const char *sql)
synchrounously process a query and returns the number of rows affected by insert, update and delete
int32_t execute (const char *sql, const parameters &p)
synchrounously process a query and returns the number of rows affected by insert, update and delete
template<typename... PARAMS, typename std::enable_if< !std::is_same< sp_data_table, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_table >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_table >::value), int32_t >::type = -1>
void query (const char *sql, const PARAMS &... args)
asynchrounously process a query and returns a pq_async::data_table as the result
template<typename T , typename std::enable_if< !std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, sp_data_table >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, sp_data_table >::value), int32_t >::type = -1>
void query (const char *sql, const parameters &p, const T &acb)
asynchrounously process a query and returns a pq_async::data_table as the result
template<typename... PARAMS, typename std::enable_if< std::is_same< sp_data_table, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_table >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_table >::value), int32_t >::type = -1>
sp_data_table query (const char *sql, const PARAMS &... args)
synchrounously process a query and returns a pq_async::data_table as the result
sp_data_table query (const char *sql)
synchrounously process a query and returns a pq_async::data_table as the result
sp_data_table query (const char *sql, const parameters &p)
synchrounously process a query and returns a pq_async::data_table as the result
template<typename... PARAMS, typename std::enable_if< !std::is_same< sp_data_row, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_row >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_row >::value), int32_t >::type = -1>
void query_single (const char *sql, const PARAMS &... args)
asynchrounously process a query and returns a pq_async::data_row as the result
template<typename T , typename std::enable_if< !std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, sp_data_row >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, sp_data_row >::value), int32_t >::type = -1>
void query_single (const char *sql, const parameters &p, const T &acb)
asynchrounously process a query and returns a pq_async::data_row as the result
template<typename... PARAMS, typename std::enable_if< std::is_same< sp_data_row, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_row >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_row >::value), int32_t >::type = -1>
sp_data_row query_single (const char *sql, const PARAMS &... args)
synchrounously process a query and returns a pq_async::data_row as the result
sp_data_row query_single (const char *sql)
synchrounously process a query and returns a pq_async::data_row as the result
sp_data_row query_single (const char *sql, const parameters &p)
synchrounously process a query and returns a pq_async::data_row as the result
template<typename R , typename... PARAMS, typename std::enable_if< !std::is_same< R, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, R >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, R >::value), int32_t >::type = -1>
void query_value (const char *sql, const PARAMS &... args)
asynchrounously process a query and returns a scalar value as the result
template<typename R , typename T , typename std::enable_if< !std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, R >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, R >::value), int32_t >::type = -1>
void query_value (const char *sql, const parameters &p, const T &acb)
asynchrounously process a query and returns a scalar value as the result
template<typename R , typename... PARAMS, typename std::enable_if< std::is_same< R, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, R >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, R >::value), int32_t >::type = -1>
R query_value (const char *sql, const PARAMS &... args)
synchrounously process a query and returns a scalar value as the result
template<typename R >
R query_value (const char *sql)
synchrounously process a query and returns a scalar value as the result
template<typename R >
R query_value (const char *sql, const parameters &p)
synchrounously process a query and returns a scalar value as the result
template<typename... PARAMS, typename std::enable_if< !std::is_same< sp_data_reader, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_reader >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_reader >::value), int32_t >::type = -1>
void query_reader (const char *sql, const PARAMS &... args)
asynchrounously process a query and returns a pq_async::data_reader as the result
template<typename T , typename std::enable_if< !std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, sp_data_reader >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, sp_data_reader >::value), int32_t >::type = -1>
void query_reader (const char *sql, const parameters &p, const T &acb)
asynchrounously process a query and returns a pq_async::data_reader as the result
template<typename... PARAMS, typename std::enable_if< std::is_same< sp_data_reader, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_reader >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_reader >::value), int32_t >::type = -1>
sp_data_reader query_reader (const char *sql, const PARAMS &... args)
synchrounously process a query and returns a pq_async::data_reader as the result
sp_data_reader query_reader (const char *sql)
synchrounously process a query and returns a pq_async::data_reader as the result
sp_data_reader query_reader (const char *sql, const parameters &p)
synchrounously process a query and returns a pq_async::data_reader as the result
void exec_queries (const std::string &sql)
synchronously parse and execute an sql script
void exec_queries (const std::string &sql, const async_cb &cb)
asynchronously parse and execute an sql script
sp_data_large_object create_lo ()
Create a large object.
sp_data_large_object get_lo (const pq_async::oid &lo_oid)
Get the lo object.
sp_data_prepared prepare (const char *name, const char *sql, bool auto_deallocate)
synchronously creates a new prepared statement and returns a data_prepared object
template<typename... PARAMS, typename std::enable_if< std::is_same< sp_data_prepared, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_prepared >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_prepared >::value), int32_t >::type = -1>
sp_data_prepared prepare (const char *name, const char *sql, bool auto_deallocate, const PARAMS &... args)
synchronously creates a new prepared statement and returns a data_prepared object
template<template< typename ... > typename Container, typename ... Args>
sp_data_prepared prepare (const char *name, const char *sql, bool auto_deallocate, const Container< pq_async::data_type, Args... > &types)
synchronously creates a new prepared statement and returns a data_prepared object
void prepare (const char *name, const char *sql, bool auto_deallocate, value_cb< sp_data_prepared > acb)
asynchronously creates a new prepared statement
template<typename... PARAMS, typename std::enable_if< !std::is_same< sp_data_prepared, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_prepared >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_prepared >::value), int32_t >::type = -1>
void prepare (const char *name, const char *sql, bool auto_deallocate, const PARAMS &... args)
asynchronously creates a new prepared statement
void prepare (const char *name, const char *sql, bool auto_deallocate, const std::vector< data_type > &types, value_cb< sp_data_prepared > cb)
asynchronously creates a new prepared statement
void deallocate_prepared (const char *name)
synchronously delete a prepared statement
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1>
void deallocate_prepared (const char *name, const CB &acb)
asynchronously delete a prepared statement
Static Public Member Functions
static sp_database open (const std::string &connection_string)
creates a new database instance using a new strand from the default event_queue
static sp_database open (sp_event_strand< int > strand, const std::string &connection_string)
creates a new database instance usign the specified event_strand
static void split_queries (const std::string &sql, std::vector< std::string > &queries)
Friends
class connection
class connection_task
class connection_pool
class data_large_object
class data_prepared
Constructor & Destructor Documentation
~database()
pq_async::database::~database () virtual
References pq_async_log_trace.
Member Function Documentation
begin() [1/2]
void pq_async::database::begin () inline
synchronously starts a new transaction
References pq_async::connection::begin_transaction(), and open_connection().
begin() [2/2]
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1> void pq_async::database::begin (const CB & acb) inline
asynchronously starts a new transaction
Template Parameters
CB
PQ_ASYNC_VALID_DB_ASY_CALLBACK(CB)
Parameters
acb async_cb callback to call on completion
References in_transaction(), and open_connection().
close()
void pq_async::database::close () inline
release the underlying connection this call is always synchronous
References pq_async::connection_pool::instance(), and pq_async::connection::release().
Referenced by pq_async::data_large_object::opened_write().
commit() [1/2]
void pq_async::database::commit () inline
synchonously commit current transaction
References pq_async::connection::commit_transaction().
commit() [2/2]
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1> void pq_async::database::commit (const CB & acb) inline
asynchonously commit current transaction
Template Parameters
CB
PQ_ASYNC_VALID_DB_ASY_CALLBACK(CB)
Parameters
acb
References execute(), in_transaction(), and pq_async::connection::touch().
create_lo()
sp_data_large_object pq_async::database::create_lo ()
Create a large object.
Returns
sp_data_large_object
References pq_async::oid.
Referenced by query_reader().
deallocate_prepared() [1/2]
void pq_async::database::deallocate_prepared (const char * name) inline
synchronously delete a prepared statement
Parameters
name the prepared statement name
References execute(), and open_connection().
deallocate_prepared() [2/2]
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1> void pq_async::database::deallocate_prepared (const char * name, const CB & acb) inline
asynchronously delete a prepared statement
Template Parameters
CB
PQ_ASYNC_VALID_DB_ASY_CALLBACK(CB)
Parameters
name the prepared statement name
acb completion void(const cb_error&) callback
References open_connection().
exec_queries() [1/2]
void pq_async::database::exec_queries (const std::string & sql)
synchronously parse and execute an sql script
Parameters
sql script commands to execute
References pq_async::join(), and pq_async_log_debug.
Referenced by query_reader().
exec_queries() [2/2]
void pq_async::database::exec_queries (const std::string & sql, const async_cb & cb)
asynchronously parse and execute an sql script
Parameters
sql script commands to execute
cb callback to call on completion or error cb: void(const cb_error& err)
execute() [1/5]
template<typename... PARAMS, typename std::enable_if< !std::is_same< int, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, int >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, int >::value), int32_t >::type = -1> void pq_async::database::execute (const char * sql, const PARAMS &... args) inline
asynchrounously process a query and returns the number of rows affected by insert, update and delete
Template Parameters
PARAMS
PQ_ASYNC_VALID_DB_CALLBACK(int)
Parameters
sql the SQL query to process
args query parameters, the last parameter is the query callback pq_async::value_cb<int>
References _PQ_ASYNC_SEND_QRY_BODY_PARAMS.
Referenced by commit(), deallocate_prepared(), release_savepoint(), rollback_savepoint(), roollback(), and set_savepoint().
execute() [2/5]
template<typename T , typename std::enable_if< !std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, int >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, int >::value), int32_t >::type = -1> void pq_async::database::execute (const char * sql, const parameters & p, const T & acb) inline
asynchrounously process a query and returns the number of rows affected by insert, update and delete
Template Parameters
T
PQ_ASYNC_VALID_DB_VAL_CALLBACK(T,int)
Parameters
sql the SQL query to process
p query parameters
acb completion void(const cb_error&, int) callback
References _PQ_ASYNC_SEND_QRY_BODY_T, and PQ_ASYNC_INVALID_DB_CALLBACK.
execute() [3/5]
template<typename... PARAMS, typename std::enable_if< std::is_same< int, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, int >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, int >::value), int32_t >::type = -1> int32_t pq_async::database::execute (const char * sql, const PARAMS &... args) inline
synchrounously process a query and returns the number of rows affected by insert, update and delete
Template Parameters
PARAMS
PQ_ASYNC_INVALID_DB_CALLBACK(int)
Parameters
sql the SQL query to process
args query parameters
Returns
int32_t the number of record processed
References _PQ_ASYNC_SEND_QRY_BODY_SYNC.
execute() [4/5]
int32_t pq_async::database::execute (const char * sql) inline
synchrounously process a query and returns the number of rows affected by insert, update and delete
Parameters
sql the SQL query to process
Returns
int32_t the number of record processed
References _PQ_ASYNC_SEND_QRY_BODY_SYNC.
execute() [5/5]
int32_t pq_async::database::execute (const char * sql, const parameters & p) inline
synchrounously process a query and returns the number of rows affected by insert, update and delete
Parameters
sql the SQL query to process
p query parameters
Returns
int32_t the number of record processed
References _PQ_ASYNC_SEND_QRY_BODY_SYNC, and PQ_ASYNC_VALID_DB_CALLBACK.
get_lo()
sp_data_large_object pq_async::database::get_lo (const pq_async::oid & lo_oid)
Get the lo object.
Parameters
lo_oid
Returns
sp_data_large_object
Referenced by query_reader().
get_strand()
sp_event_strand<int> pq_async::database::get_strand () inline
Referenced by pq_async::connection::strand().
in_transaction()
bool pq_async::database::in_transaction () inline
returns if a transaction is in progress
Returns
true if a transaction is in progress
false if no transaction is in progress
References pq_async::connection::in_transaction().
Referenced by begin(), commit(), release_savepoint(), rollback_savepoint(), roollback(), and set_savepoint().
open() [1/2]
static sp_database pq_async::database::open (const std::string & connection_string) inline static
creates a new database instance using a new strand from the default event_queue
Parameters
connection_string the connection string used for that instance
Returns
sp_database
References pq_async::event_queue::get_default().
Referenced by pq_async::data_large_object::opened_write(), pq_async::tests::db_test_base::SetUp(), and pq_async::tests::TEST_F().
open() [2/2]
static sp_database pq_async::database::open (sp_event_strand< int > strand, const std::string & connection_string) inline static
creates a new database instance usign the specified event_strand
Parameters
strand the pq_async::event_strand to use
connection_string the connection string used for that instance
Returns
sp_database
References pq_async::connection::conn(), pq_async_log_trace, split_queries(), and working().
open_connection() [1/2]
sp_connection_lock pq_async::database::open_connection (int32_t timeout_ms = 5000) inline
synchronously try to acquire and open a connection
Parameters
timeout_ms milliseconds to wait before failure, default to 5000
Returns
sp_connection_lock
References pq_async::connection_pool::get_connection(), pq_async::connection_pool::instance(), pq_async::connection::open_connection(), PQ_ASYNC_VALID_DB_VAL_CALLBACK, and pq_async::connection::reserve().
Referenced by begin(), deallocate_prepared(), prepare(), and query_reader().
open_connection() [2/2]
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &, sp_connection_lock >::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type, sp_connection_lock >::value), int32_t >::type = -1> void pq_async::database::open_connection (const CB & acb, int32_t timeout_ms = 5000) inline
asynchronously try to acquire and open a connection
Template Parameters
CB
PQ_ASYNC_VALID_DB_CALLBACK_T(CB,bool)
Parameters
acb
timeout_ms milliseconds to wait before failure, default to 5000
References pq_async_log_debug.
prepare() [1/6]
sp_data_prepared pq_async::database::prepare (const char * name, const char * sql, bool auto_deallocate) inline
synchronously creates a new prepared statement and returns a data_prepared object
Parameters
name the prepared statement name
sql the prepared statement query
auto_deallocate if the prepared statement shoul be delete on
Returns
sp_data_prepared
References PQ_ASYNC_INVALID_DB_CALLBACK.
Referenced by prepare().
prepare() [2/6]
template<typename... PARAMS, typename std::enable_if< std::is_same< sp_data_prepared, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_prepared >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_prepared >::value), int32_t >::type = -1> sp_data_prepared pq_async::database::prepare (const char * name, const char * sql, bool auto_deallocate, const PARAMS &... args) inline
synchronously creates a new prepared statement and returns a data_prepared object
Template Parameters
PARAMS
PQ_ASYNC_INVALID_DB_CALLBACK(sp_data_prepared)
Parameters
name the prepared statement name
sql the prepared statement query
auto_deallocate if the prepared statement shoul be delete on
args list of query parameter's data_type
Returns
sp_data_prepared
References prepare().
prepare() [3/6]
template<template< typename ... > typename Container, typename ... Args> sp_data_prepared pq_async::database::prepare (const char * name, const char * sql, bool auto_deallocate, const Container< pq_async::data_type, Args... > & types) inline
synchronously creates a new prepared statement and returns a data_prepared object
Template Parameters
Container
Args
Parameters
name the prepared statement name
sql the prepared statement query
auto_deallocate if the prepared statement shoul be delete on data_prepared object destruction
types list of query parameter's data_type
Returns
sp_data_prepared
References open_connection().
prepare() [4/6]
void pq_async::database::prepare (const char * name, const char * sql, bool auto_deallocate, value_cb< sp_data_prepared > acb) inline
asynchronously creates a new prepared statement
Parameters
name the prepared statement name
sql the prepared statement query
auto_deallocate if the prepared statement shoul be delete on
acb completion void(const cb_error&, sp_data_prepared) callback
References PQ_ASYNC_VALID_DB_CALLBACK, and prepare().
prepare() [5/6]
template<typename... PARAMS, typename std::enable_if< !std::is_same< sp_data_prepared, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_prepared >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_prepared >::value), int32_t >::type = -1> void pq_async::database::prepare (const char * name, const char * sql, bool auto_deallocate, const PARAMS &... args) inline
asynchronously creates a new prepared statement
Template Parameters
PARAMS
PQ_ASYNC_VALID_DB_CALLBACK(sp_data_prepared)
Parameters
name the prepared statement name
sql the prepared statement query
auto_deallocate if the prepared statement shoul be delete on
args list of query parameter's data_type, the last argument is the completion void(const cb_error&, sp_data_prepared) callback
References pq_async::get_last(), and prepare().
prepare() [6/6]
void pq_async::database::prepare (const char * name, const char * sql, bool auto_deallocate, const std::vector< data_type > & types, value_cb< sp_data_prepared > cb) inline
asynchronously creates a new prepared statement
Parameters
name the prepared statement name
sql the prepared statement query
auto_deallocate if the prepared statement shoul be delete on
types list of query parameter's data_type
cb completion void(const cb_error&, sp_data_prepared) callback
References open_connection().
query() [1/5]
template<typename... PARAMS, typename std::enable_if< !std::is_same< sp_data_table, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_table >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_table >::value), int32_t >::type = -1> void pq_async::database::query (const char * sql, const PARAMS &... args) inline
asynchrounously process a query and returns a pq_async::data_table as the result
Template Parameters
PARAMS
PQ_ASYNC_VALID_DB_CALLBACK(sp_data_table)
Parameters
sql the SQL query to process
args query parameters, the last parameter is the completion void(const cb_error&, sp_data_table) callback
References _PQ_ASYNC_SEND_QRY_BODY_PARAMS.
query() [2/5]
template<typename T , typename std::enable_if< !std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, sp_data_table >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, sp_data_table >::value), int32_t >::type = -1> void pq_async::database::query (const char * sql, const parameters & p, const T & acb) inline
asynchrounously process a query and returns a pq_async::data_table as the result
Template Parameters
T
PQ_ASYNC_VALID_DB_VAL_CALLBACK(T,sp_data_table)
Parameters
sql the SQL query to process
p query parameters
acb completion void(const cb_error&, sp_data_table) callback
References _PQ_ASYNC_SEND_QRY_BODY_T, and PQ_ASYNC_INVALID_DB_CALLBACK.
query() [3/5]
template<typename... PARAMS, typename std::enable_if< std::is_same< sp_data_table, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_table >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_table >::value), int32_t >::type = -1> sp_data_table pq_async::database::query (const char * sql, const PARAMS &... args) inline
synchrounously process a query and returns a pq_async::data_table as the result
Template Parameters
PARAMS
PQ_ASYNC_INVALID_DB_CALLBACK(sp_data_table)
Parameters
sql the SQL query to process
args query parameters
Returns
sp_data_table
References _PQ_ASYNC_SEND_QRY_BODY_SYNC.
query() [4/5]
sp_data_table pq_async::database::query (const char * sql) inline
synchrounously process a query and returns a pq_async::data_table as the result
Parameters
sql the SQL query to process
Returns
sp_data_table
References _PQ_ASYNC_SEND_QRY_BODY_SYNC.
query() [5/5]
sp_data_table pq_async::database::query (const char * sql, const parameters & p) inline
synchrounously process a query and returns a pq_async::data_table as the result
Parameters
sql the SQL query to process
p query parameters
Returns
sp_data_table
References _PQ_ASYNC_SEND_QRY_BODY_SYNC, and PQ_ASYNC_VALID_DB_CALLBACK.
query_reader() [1/5]
template<typename... PARAMS, typename std::enable_if< !std::is_same< sp_data_reader, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_reader >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_reader >::value), int32_t >::type = -1> void pq_async::database::query_reader (const char * sql, const PARAMS &... args) inline
asynchrounously process a query and returns a pq_async::data_reader as the result
Template Parameters
PARAMS
PQ_ASYNC_VALID_DB_CALLBACK(sp_data_reader)
Parameters
sql the SQL query to process
args query parameters, the last parameter is the query callback pq_async::value_cb<sp_data_reader>
References pq_async::get_last(), open_connection(), and pq_async::parameters::push_back().
query_reader() [2/5]
template<typename T , typename std::enable_if< !std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, sp_data_reader >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, sp_data_reader >::value), int32_t >::type = -1> void pq_async::database::query_reader (const char * sql, const parameters & p, const T & acb) inline
asynchrounously process a query and returns a pq_async::data_reader as the result
Template Parameters
T
PQ_ASYNC_VALID_DB_VAL_CALLBACK(T,sp_data_reader)
Parameters
sql the SQL query to process
p query parameters
acb completion void(const cb_error&, sp_data_reader) callback
References open_connection(), and PQ_ASYNC_INVALID_DB_CALLBACK.
query_reader() [3/5]
template<typename... PARAMS, typename std::enable_if< std::is_same< sp_data_reader, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_reader >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_reader >::value), int32_t >::type = -1> sp_data_reader pq_async::database::query_reader (const char * sql, const PARAMS &... args) inline
synchrounously process a query and returns a pq_async::data_reader as the result
Template Parameters
PARAMS
PQ_ASYNC_INVALID_DB_CALLBACK(sp_data_reader)
Parameters
sql the SQL query to process
args query parameters
Returns
sp_data_reader
References open_connection().
query_reader() [4/5]
sp_data_reader pq_async::database::query_reader (const char * sql) inline
synchrounously process a query and returns a pq_async::data_reader as the result
Parameters
sql the SQL query to process
Returns
sp_data_reader
References open_connection().
query_reader() [5/5]
sp_data_reader pq_async::database::query_reader (const char * sql, const parameters & p) inline
synchrounously process a query and returns a pq_async::data_reader as the result
Parameters
sql the SQL query to process
p query parameters
Returns
sp_data_reader
References create_lo(), exec_queries(), get_lo(), and open_connection().
query_single() [1/5]
template<typename... PARAMS, typename std::enable_if< !std::is_same< sp_data_row, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_row >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_row >::value), int32_t >::type = -1> void pq_async::database::query_single (const char * sql, const PARAMS &... args) inline
asynchrounously process a query and returns a pq_async::data_row as the result
Template Parameters
PARAMS
PQ_ASYNC_VALID_DB_CALLBACK(sp_data_row)
Parameters
sql the SQL query to process
args query parameters, the last parameter is the completion void(const cb_error&, sp_data_row) callback
References _PQ_ASYNC_SEND_QRY_BODY_PARAMS.
query_single() [2/5]
template<typename T , typename std::enable_if< !std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, sp_data_row >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, sp_data_row >::value), int32_t >::type = -1> void pq_async::database::query_single (const char * sql, const parameters & p, const T & acb) inline
asynchrounously process a query and returns a pq_async::data_row as the result
Template Parameters
T
PQ_ASYNC_VALID_DB_VAL_CALLBACK(T,sp_data_row)
Parameters
sql the SQL query to process
p query parameters
acb the completion void(const cb_error&, sp_data_row) callback
References _PQ_ASYNC_SEND_QRY_BODY_T, and PQ_ASYNC_INVALID_DB_CALLBACK.
query_single() [3/5]
template<typename... PARAMS, typename std::enable_if< std::is_same< sp_data_row, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, sp_data_row >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, sp_data_row >::value), int32_t >::type = -1> sp_data_row pq_async::database::query_single (const char * sql, const PARAMS &... args) inline
synchrounously process a query and returns a pq_async::data_row as the result
Template Parameters
PARAMS
PQ_ASYNC_INVALID_DB_CALLBACK(sp_data_row)
Parameters
sql the SQL query to process
args query parameters
Returns
sp_data_row
References _PQ_ASYNC_SEND_QRY_BODY_SYNC.
query_single() [4/5]
sp_data_row pq_async::database::query_single (const char * sql) inline
synchrounously process a query and returns a pq_async::data_row as the result
Parameters
sql
Returns
sp_data_row
References _PQ_ASYNC_SEND_QRY_BODY_SYNC.
query_single() [5/5]
sp_data_row pq_async::database::query_single (const char * sql, const parameters & p) inline
synchrounously process a query and returns a pq_async::data_row as the result
Parameters
sql the SQL query to process
p query parameters
Returns
sp_data_row
References _PQ_ASYNC_SEND_QRY_BODY_SYNC, and PQ_ASYNC_VALID_DB_CALLBACK.
query_value() [1/5]
template<typename R , typename... PARAMS, typename std::enable_if< !std::is_same< R, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, R >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, R >::value), int32_t >::type = -1> void pq_async::database::query_value (const char * sql, const PARAMS &... args) inline
asynchrounously process a query and returns a scalar value as the result
Template Parameters
R the result type
PARAMS
PQ_ASYNC_VALID_DB_CALLBACK(R)
Parameters
sql the SQL query to process
args query parameters, the last parameter is the query callback pq_async::value_cb<R>
References _PQ_ASYNC_SEND_QRY_BODY_PARAMS, and PQ_ASYNC_VALID_DB_VAL_CALLBACK.
query_value() [2/5]
template<typename R , typename T , typename std::enable_if< !std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, R >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, R >::value), int32_t >::type = -1> void pq_async::database::query_value (const char * sql, const parameters & p, const T & acb) inline
asynchrounously process a query and returns a scalar value as the result
Template Parameters
R
T
PQ_ASYNC_VALID_DB_VAL_CALLBACK(T,R)
Parameters
sql the SQL query to process
p query parameters
acb completion void(const cb_error&, R) callback
References _PQ_ASYNC_SEND_QRY_BODY_T, and PQ_ASYNC_INVALID_DB_CALLBACK.
query_value() [3/5]
template<typename R , typename... PARAMS, typename std::enable_if< std::is_same< R, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||std::is_array< typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value||(!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, const cb_error &, R >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< typename select_last< PARAMS... >::type >::type, R >::value), int32_t >::type = -1> R pq_async::database::query_value (const char * sql, const PARAMS &... args) inline
synchrounously process a query and returns a scalar value as the result
Template Parameters
R the result type
PARAMS
PQ_ASYNC_INVALID_DB_CALLBACK(R)
Parameters
sql the SQL query to process
args query parameters
Returns
R the scalar value
References _PQ_ASYNC_SEND_QRY_BODY_SYNC.
query_value() [4/5]
template<typename R > R pq_async::database::query_value (const char * sql) inline
synchrounously process a query and returns a scalar value as the result
Template Parameters
R
Parameters
sql the SQL query to process
Returns
R
References _PQ_ASYNC_SEND_QRY_BODY_SYNC.
query_value() [5/5]
template<typename R > R pq_async::database::query_value (const char * sql, const parameters & p) inline
synchrounously process a query and returns a scalar value as the result
Template Parameters
R
Parameters
sql the SQL query to process
p query parameters
Returns
R
References _PQ_ASYNC_SEND_QRY_BODY_SYNC, and PQ_ASYNC_VALID_DB_CALLBACK.
release_savepoint() [1/2]
void pq_async::database::release_savepoint (const char * name) inline
synchonously release the specified savepoint
Parameters
name
References pq_async::connection::release_savepoint().
release_savepoint() [2/2]
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1> void pq_async::database::release_savepoint (const CB & acb, const char * name) inline
asynchonously release the specified savepoint
Template Parameters
CB
PQ_ASYNC_VALID_DB_ASY_CALLBACK(CB)
Parameters
acb
name
References execute(), in_transaction(), pq_async::s, and pq_async::connection::touch().
rollback()
void pq_async::database::rollback () inline
synchonously rollback current transaction
References pq_async::connection::rollback_transaction().
rollback_savepoint() [1/2]
void pq_async::database::rollback_savepoint (const char * name) inline
synchonously rollback the specified savepoint
Parameters
name
References pq_async::connection::rollback_savepoint().
rollback_savepoint() [2/2]
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1> void pq_async::database::rollback_savepoint (const CB & acb, const char * name) inline
asynchonously rollback the specified savepoint
Template Parameters
CB
PQ_ASYNC_VALID_DB_ASY_CALLBACK(CB)
Parameters
acb
name
References execute(), in_transaction(), PQ_ASYNC_VALID_DB_CALLBACK, pq_async::s, and pq_async::connection::touch().
roollback()
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1> void pq_async::database::roollback (const CB & acb) inline
asynchonously rollback current transaction
Template Parameters
CB
PQ_ASYNC_VALID_DB_ASY_CALLBACK(CB)
Parameters
acb
References execute(), in_transaction(), and pq_async::connection::touch().
set_savepoint() [1/2]
void pq_async::database::set_savepoint (const char * name) inline
synchronously sets a new savepoint inside the current transaction
Parameters
name the savepoint name
References pq_async::connection::set_savepoint().
set_savepoint() [2/2]
template<typename CB , typename std::enable_if< !std::is_array< typename std::remove_pointer< CB >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< CB >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< CB >::type >::value), int32_t >::type = -1> void pq_async::database::set_savepoint (const CB & acb, const char * name) inline
asynchronously sets a new savepoint inside the current transaction
Template Parameters
CB
PQ_ASYNC_VALID_DB_ASY_CALLBACK(CB)
Parameters
acb
name
References execute(), in_transaction(), pq_async::s, and pq_async::connection::touch().
split_queries()
void pq_async::database::split_queries (const std::string & sql, std::vector< std::string > & queries) static
References pq_async_log_trace, and pq_async::trim().
Referenced by open().
working()
bool pq_async::database::working () inline
returns true if the database is currently working.
Returns
true
false
References pq_async::connection::running().
Referenced by open().
Friends And Related Function Documentation
connection
friend class connection friend
connection_pool
friend class connection_pool friend
connection_task
friend class connection_task friend
data_large_object
friend class data_large_object friend
data_prepared
friend class data_prepared friend
The documentation for this class was generated from the following files:
src/database.h
src/database.cpp