libpq-async++: pq_async::duration Class Reference
pq_async::duration Class Reference
#include <src/pg_type_duration_def.h>
Public Member Functions
duration (const std::string &val)
duration (const char *val)
duration (long double val)
virtual ~duration ()
std::string to_short_string () const
std::string to_long_string () const
operator interval () const
operator std::string () const
Static Public Member Functions
static duration from_seconds (int64_t seconds)
Friends
std::ostream & operator<< (std::ostream &os, const duration &d)
std::istream & operator>> (std::istream &is, duration &v)
Constructor & Destructor Documentation
duration() [1/3]
pq_async::duration::duration (const std::string & val)
References pq_async::text_to_duration().
Referenced by from_seconds(), and pq_async::operator>>().
duration() [2/3]
pq_async::duration::duration (const char * val)
References pq_async::text_to_duration().
duration() [3/3]
pq_async::duration::duration (long double val) inline
~duration()
virtual pq_async::duration::~duration () inline virtual
Member Function Documentation
from_seconds()
static duration pq_async::duration::from_seconds (int64_t seconds) inline static
References duration(), to_long_string(), and to_short_string().
Referenced by pq_async::tests::TEST_F().
operator interval()
pq_async::duration::operator interval () const inline
References pq_async::d, pq_async::interval, operator<<, and operator>>.
operator std::string()
pq_async::duration::operator std::string () const explicit
References to_long_string().
to_long_string()
std::string pq_async::duration::to_long_string () const
References pq_async::num_to_str(), and pq_async::plural().
Referenced by from_seconds(), operator std::string(), and pq_async::operator<<().
to_short_string()
std::string pq_async::duration::to_short_string () const
References pq_async::num_to_str().
Referenced by from_seconds().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const duration & d) friend
Referenced by operator interval().
operator>>
std::istream& operator>> (std::istream & is, duration & v) friend
Referenced by operator interval().
The documentation for this class was generated from the following files:
src/pg_type_duration_def.h
src/pg_type_duration_def.cpp