libpq-async++: pq_async::cb_error Class Reference
pq_async::cb_error Class Reference
#include <src/exceptions.h>
Public Member Functions
cb_error ()
cb_error (nullptr_t)
cb_error (const std::exception &err)
virtual ~cb_error ()
const std::exception & error () const
operator bool () const
operator const char * () const
const char * c_str () const
Static Public Attributes
static cb_error no_err
Friends
std::ostream & operator<< (std::ostream &s, const cb_error &v)
Constructor & Destructor Documentation
cb_error() [1/3]
pq_async::cb_error::cb_error () inline
cb_error() [2/3]
pq_async::cb_error::cb_error (nullptr_t) inline
cb_error() [3/3]
pq_async::cb_error::cb_error (const std::exception & err) inline
~cb_error()
virtual pq_async::cb_error::~cb_error () inline virtual
Member Function Documentation
c_str()
const char* pq_async::cb_error::c_str () const inline
References pq_async::operator<<(), and pq_async::s.
Referenced by pq_async::assign_value_cb(), and pq_async::operator<<().
error()
const std::exception& pq_async::cb_error::error () const inline
operator bool()
pq_async::cb_error::operator bool () const inline explicit
operator const char *()
pq_async::cb_error::operator const char * () const inline explicit
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & s, const cb_error & v) friend
Field Documentation
no_err
cb_error pq_async::cb_error::no_err static
Referenced by pq_async::connection_pool_assign_exception::~connection_pool_assign_exception().
The documentation for this class was generated from the following files:
src/exceptions.h
src/exceptions.cpp