libpq-async++: pq_async::event_task_base Class Reference
pq_async::event_task_base Class Reference abstract
#include <src/event_queue.h>
Public Member Functions
event_task_base (event_queue *owner)
virtual ~event_task_base ()
event_queue * owner ()
uint64_t id () const
virtual bool force_push ()
virtual void switch_owner (event_queue *new_owner, bool requeue=false)
virtual void run_task ()=0
virtual event_requeue_pos requeue ()=0
virtual size_t size () const =0
Protected Attributes
event_queue * _owner
uint64_t _id
Friends
template<typename T >
class event_strand
class event_queue
Constructor & Destructor Documentation
event_task_base()
pq_async::event_task_base::event_task_base (event_queue * owner) inline
~event_task_base()
virtual pq_async::event_task_base::~event_task_base () inline virtual
Member Function Documentation
force_push()
virtual bool pq_async::event_task_base::force_push () inline virtual
Reimplemented in pq_async::event_strand< T >.
id()
uint64_t pq_async::event_task_base::id () const inline
Referenced by pq_async::event_strand< T >::push_back(), pq_async::event_strand< T >::push_front(), and pq_async::event_queue::run().
owner()
event_queue* pq_async::event_task_base::owner () inline
requeue()
virtual event_requeue_pos pq_async::event_task_base::requeue () pure virtual
Implemented in pq_async::connection_task, pq_async::event_task, and pq_async::event_strand< T >.
run_task()
virtual void pq_async::event_task_base::run_task () pure virtual
Implemented in pq_async::reader_connection_task, pq_async::connection_task, pq_async::event_task, and pq_async::event_strand< T >.
size()
virtual size_t pq_async::event_task_base::size () const pure virtual
Implemented in pq_async::connection_task, pq_async::event_task, and pq_async::event_strand< T >.
switch_owner()
void pq_async::event_task_base::switch_owner (event_queue * new_owner, bool requeue = false) virtual
References _owner, and event_queue.
Referenced by pq_async::event_queue::run().
Friends And Related Function Documentation
event_queue
friend class event_queue friend
Referenced by switch_owner().
event_strand
template<typename T > friend class event_strand friend
Field Documentation
_id
uint64_t pq_async::event_task_base::_id protected
_owner
event_queue* pq_async::event_task_base::_owner protected
Referenced by pq_async::event_strand< T >::push_back(), pq_async::event_strand< T >::push_front(), pq_async::event_strand< T >::requeue_self_back(), pq_async::event_strand< T >::requeue_self_front(), switch_owner(), and pq_async::event_strand< T >::~event_strand().
The documentation for this class was generated from the following files:
src/event_queue.h
src/event_queue.cpp