libpq-async++: pq_async::event_queue Class Reference
pq_async::event_queue Class Reference
#include <src/event_queue.h>
Public Member Functions
event_queue ()
virtual ~event_queue ()
Destructor.
virtual bool is_thread_safe ()
size_t local_size () const
virtual size_t size () const
template<typename T = int>
sp_event_strand< T > new_strand (bool auto_requeue=true)
template<typename Task >
uint64_t push_back (Task task)
template<typename Task >
uint64_t push_front (Task task)
bool cancel_task (uint64_t task_id)
template<typename Iterator , typename T >
void each (Iterator first, Iterator last, T cb, async_cb end_cb)
void series (std::vector< async_series_cb > cbs, async_cb end_cb)
virtual void run_n (uint32_t count=1)
virtual void run (uint32_t usec_wait=1)
Static Public Member Functions
static event_queue * get_default ()
static void destroy_default ()
Friends
class event_task_base
template<typename T >
class event_strand
template<typename Task , typename std::enable_if< std::is_invocable< Task >::value, int32_t >::type >
uint64_t _event_queue_push_back (event_queue *eq, Task task)
uint64_t _event_queue_push_back (event_queue *eq, sp_event_task task)
template<typename Task , typename std::enable_if< std::is_invocable< Task >::value, int32_t >::type >
uint64_t _event_queue_push_front (event_queue *eq, Task task)
uint64_t _event_queue_push_front (event_queue *eq, sp_event_task task)
Constructor & Destructor Documentation
event_queue()
pq_async::event_queue::event_queue () inline
~event_queue()
virtual pq_async::event_queue::~event_queue () inline virtual
Destructor.
Member Function Documentation
cancel_task()
bool pq_async::event_queue::cancel_task (uint64_t task_id) inline
References PQ_ASYNC_LOCK_EVENT_QUEUE.
destroy_default()
static void pq_async::event_queue::destroy_default () inline static
Referenced by pq_async::tests::pq_async_test_env::TearDown().
each()
template<typename Iterator , typename T > void pq_async::event_queue::each (Iterator first, Iterator last, T cb, async_cb end_cb)
Referenced by pq_async::tests::TEST_F().
get_default()
static event_queue* pq_async::event_queue::get_default () inline static
Referenced by pq_async::database::open(), and pq_async::tests::TEST_F().
is_thread_safe()
virtual bool pq_async::event_queue::is_thread_safe () inline virtual
local_size()
size_t pq_async::event_queue::local_size () const inline
References PQ_ASYNC_LOCK_EVENT_QUEUE.
new_strand()
template<typename T = int> sp_event_strand<T> pq_async::event_queue::new_strand (bool auto_requeue = true) inline
Referenced by pq_async::async::series(), and pq_async::tests::TEST_F().
push_back()
template<typename Task > uint64_t pq_async::event_queue::push_back (Task task) inline
References pq_async::_event_queue_push_back(), and PQ_ASYNC_LOCK_EVENT_QUEUE.
Referenced by pq_async::async::each(), pq_async::event_strand< T >::push_back(), pq_async::event_strand< T >::push_front(), pq_async::event_strand< T >::requeue_self_back(), run(), pq_async::async::series(), pq_async::tests::TEST_F(), and pq_async::event_strand< T >::~event_strand().
push_front()
template<typename Task > uint64_t pq_async::event_queue::push_front (Task task) inline
References pq_async::_event_queue_push_front(), and PQ_ASYNC_LOCK_EVENT_QUEUE.
Referenced by pq_async::event_strand< T >::requeue_self_front().
run()
virtual void pq_async::event_queue::run (uint32_t usec_wait = 1) inline virtual
References pq_async::back, pq_async::front, pq_async::event_task_base::id(), pq_async::none, PQ_ASYNC_LOCK_EVENT_QUEUE, push_back(), and pq_async::event_task_base::switch_owner().
Referenced by pq_async::tests::TEST_F().
run_n()
virtual void pq_async::event_queue::run_n (uint32_t count = 1) inline virtual
Referenced by pq_async::event_strand< T >::run_task().
series()
void pq_async::event_queue::series (std::vector< async_series_cb > cbs, async_cb end_cb)
//example:
pq_async::async::series({
    [&](pq_async::async_cb scb) -> void {
        return scb(nullptr);
    },
    [&](pq_async::async_cb scb) -> void {
        return scb(nullptr);
    },
}, [&](const pq_async::cb_error& err) -> void {
    if(err)
        return cb(err, cfg);
    cb(pq_async::cb_error::no_err, cfg);
});
References pq_async::async::series().
Referenced by pq_async::tests::TEST_F().
size()
virtual size_t pq_async::event_queue::size () const inline virtual
Reimplemented in pq_async::event_strand< T >.
References PQ_ASYNC_LOCK_EVENT_QUEUE.
Friends And Related Function Documentation
_event_queue_push_back [1/2]
template<typename Task , typename std::enable_if< std::is_invocable< Task >::value, int32_t >::type > uint64_t _event_queue_push_back (event_queue * eq, Task task) friend
Referenced by pq_async::event_strand< T >::push_back().
_event_queue_push_back [2/2]
uint64_t _event_queue_push_back (event_queue * eq, sp_event_task task) friend
_event_queue_push_front [1/2]
template<typename Task , typename std::enable_if< std::is_invocable< Task >::value, int32_t >::type > uint64_t _event_queue_push_front (event_queue * eq, Task task) friend
Referenced by pq_async::event_strand< T >::push_front().
_event_queue_push_front [2/2]
uint64_t _event_queue_push_front (event_queue * eq, sp_event_task task) friend
event_strand
template<typename T > friend class event_strand friend
event_task_base
friend class event_task_base friend
The documentation for this class was generated from the following files:
src/event_queue.h
src/async.h
src/event_queue.cpp