libpq-async++: pq_async::connection_task Class Reference
pq_async::connection_task Class Reference
#include <src/data_connection_pool.h>
Public Member Functions
connection_task (event_queue *owner, sp_database db, sp_connection_lock lock, const value_cb< PGresult *> &cb)
connection_task (event_queue *owner, sp_database db, connection *conn, const value_cb< sp_connection_lock > &cb)
connection_task (event_queue *owner, sp_database db, sp_connection_lock lock)
connection_task (event_queue *owner, sp_database db, connection *conn)
sp_database db ()
void connect (const std::string &connection_string, int32_t timeout_ms)
void send_query (const char *sql, const parameters &p, int format=1)
void send_query (const char *sql, parameters &p, int format=1)
void send_prepare (const char *name, const char *sql, const std::vector< data_type > &t)
void send_query_prepared (const char *name, parameters &p, int format=1)
void send_query_prepared (const char *name, const parameters &p, int format=1)
void cancel ()
virtual PGresult * run_now ()
virtual void run_task ()
virtual event_requeue_pos requeue ()
virtual size_t size () const
PGconn * conn ()
Public Member Functions inherited from pq_async::event_task_base
event_task_base (event_queue *owner)
virtual ~event_task_base ()
event_queue * owner ()
uint64_t id () const
virtual bool force_push ()
virtual void switch_owner (event_queue *new_owner, bool requeue=false)
Protected Types
enum command_type {
command_type::none = 0, command_type::connect = 1, command_type::query = 2, command_type::prepare = 3,
command_type::query_prepared = 4, command_type::cancel = 5, command_type::sent = 6
}
Protected Member Functions
void _connect ()
void _send_query ()
void _send_prepare ()
void _send_query_prepared ()
void _cancel_command ()
bool _consume_data ()
Protected Attributes
command_type _cmd_type
std::string _name
std::string _sql
parameters _p
std::vector< data_type > _t
int64_t _format
bool _completed
sp_database _db
connection * _conn
value_cb< sp_connection_lock > _lock_cb
sp_connection_lock _lock
value_cb< PGresult * > _cb
Protected Attributes inherited from pq_async::event_task_base
event_queue * _owner
uint64_t _id
Member Enumeration Documentation
command_type
enum pq_async::connection_task::command_type strong protected
Enumerator
none
connect
query
prepare
query_prepared
cancel
sent
Constructor & Destructor Documentation
connection_task() [1/4]
pq_async::connection_task::connection_task (event_queue * owner, sp_database db, sp_connection_lock lock, const value_cb< PGresult *> & cb)
connection_task() [2/4]
pq_async::connection_task::connection_task (event_queue * owner, sp_database db, connection * conn, const value_cb< sp_connection_lock > & cb)
References pq_async::none.
connection_task() [3/4]
pq_async::connection_task::connection_task (event_queue * owner, sp_database db, sp_connection_lock lock)
References pq_async::none.
connection_task() [4/4]
pq_async::connection_task::connection_task (event_queue * owner, sp_database db, connection * conn)
References pq_async::none.
Member Function Documentation
_cancel_command()
void pq_async::connection_task::_cancel_command () inline protected
References pq_async::connection::conn(), and pq_async_log_debug.
_connect()
void pq_async::connection_task::_connect () protected
References _completed, _db, _format, _lock_cb, _sql, pq_async::connection_pool::get_connection(), pq_async::connection_pool::instance(), and pq_async_log_debug.
_consume_data()
bool pq_async::connection_task::_consume_data () inline protected
References pq_async::connection::conn(), and pq_async_log_trace.
_send_prepare()
void pq_async::connection_task::_send_prepare () inline protected
References pq_async::connection::conn(), and pq_async_log_debug.
_send_query()
void pq_async::connection_task::_send_query () inline protected
References pq_async::connection::conn(), and pq_async_log_debug.
_send_query_prepared()
void pq_async::connection_task::_send_query_prepared () inline protected
References pq_async::connection::conn(), and pq_async_log_debug.
cancel()
void pq_async::connection_task::cancel () inline
conn()
PGconn * pq_async::connection_task::conn ()
References _db.
connect()
void pq_async::connection_task::connect (const std::string & connection_string, int32_t timeout_ms) inline
db()
sp_database pq_async::connection_task::db () inline
requeue()
virtual event_requeue_pos pq_async::connection_task::requeue () inline virtual
Implements pq_async::event_task_base.
References pq_async::front, and pq_async::none.
run_now()
virtual PGresult* pq_async::connection_task::run_now () inline virtual
Reimplemented in pq_async::reader_connection_task.
References pq_async::connection::conn(), and pq_async::none.
run_task()
virtual void pq_async::connection_task::run_task () inline virtual
Implements pq_async::event_task_base.
Reimplemented in pq_async::reader_connection_task.
References pq_async::connection::conn(), and pq_async::none.
send_prepare()
void pq_async::connection_task::send_prepare (const char * name, const char * sql, const std::vector< data_type > & t) inline
send_query() [1/2]
void pq_async::connection_task::send_query (const char * sql, const parameters & p, int format = 1) inline
send_query() [2/2]
void pq_async::connection_task::send_query (const char * sql, parameters & p, int format = 1) inline
send_query_prepared() [1/2]
void pq_async::connection_task::send_query_prepared (const char * name, parameters & p, int format = 1) inline
send_query_prepared() [2/2]
void pq_async::connection_task::send_query_prepared (const char * name, const parameters & p, int format = 1) inline
size()
virtual size_t pq_async::connection_task::size () const inline virtual
Implements pq_async::event_task_base.
References pq_async::connection::conn().
Field Documentation
_cb
value_cb<PGresult*> pq_async::connection_task::_cb protected
_cmd_type
command_type pq_async::connection_task::_cmd_type protected
_completed
bool pq_async::connection_task::_completed protected
Referenced by _connect().
_conn
connection* pq_async::connection_task::_conn protected
_db
sp_database pq_async::connection_task::_db protected
Referenced by _connect(), and conn().
_format
int64_t pq_async::connection_task::_format protected
Referenced by _connect().
_lock
sp_connection_lock pq_async::connection_task::_lock protected
_lock_cb
value_cb<sp_connection_lock> pq_async::connection_task::_lock_cb protected
Referenced by _connect().
_name
std::string pq_async::connection_task::_name protected
_p
parameters pq_async::connection_task::_p protected
_sql
std::string pq_async::connection_task::_sql protected
Referenced by _connect().
_t
std::vector<data_type> pq_async::connection_task::_t protected
The documentation for this class was generated from the following files:
src/data_connection_pool.h
src/data_connection_pool.cpp