libpq-async++: pq_async::numeric Class Reference
pq_async::numeric Class Reference
#include <src/pg_type_numeric_def.h>
Public Member Functions
numeric ()
numeric (const numeric &b)
numeric (const char *s, ssize_t len=-1)
numeric (double val)
numeric (float val)
numeric (int64_t val)
numeric (int32_t val)
~numeric ()
operator std::string () const
bool is_nan () const
bool operator== (const numeric &b) const
bool operator!= (const numeric &b) const
bool operator< (const numeric &b) const
bool operator> (const numeric &b) const
bool operator<= (const numeric &b) const
bool operator>= (const numeric &b) const
numeric & operator= (const numeric &b)
numeric operator+ (const numeric &b) const
numeric operator- (const numeric &b) const
numeric operator* (const numeric &b) const
numeric operator/ (const numeric &b) const
numeric operator% (const numeric &b) const
numeric & operator+= (const numeric &b)
numeric & operator-= (const numeric &b)
numeric & operator*= (const numeric &b)
numeric & operator/= (const numeric &b)
numeric & operator%= (const numeric &b)
numeric & operator++ ()
numeric operator++ (int)
numeric & operator-- ()
numeric operator-- (int)
operator int64_t () const
operator int32_t () const
operator double () const
Static Public Member Functions
static numeric nan ()
static numeric from (int64_t val)
static numeric from (int32_t val)
static numeric from (double val)
static int cmp (const numeric &var1, const numeric &var2)
static void add (const numeric &var1, const numeric &var2, numeric &result)
Friends
pq_async::numeric pgval_to_numeric (char *val, int len, int fmt)
pq_async::parameter * new_parameter (const pq_async::numeric &value)
pq_async::parameter * new_parameter (const pq_async::numrange &value)
void copy_var_to_var (const numeric &src, numeric &dest)
void alloc_var (numeric *var, int ndigits)
void free_var (numeric *var)
void zero_var (numeric *var)
const char * set_var_from_str (const char *str, const char *cp, numeric *dest)
char * get_str_from_var (const numeric *var)
char * get_str_from_var_sci (const numeric *var, int rscale)
bool numericvar_to_int64 (const numeric *var, int64_t *result)
void int64_to_numericvar (int64_t val, numeric *var)
int cmp_var (const numeric *var1, const numeric *var2)
void add_var (const numeric *var1, const numeric *var2, numeric *result)
void sub_var (const numeric *var1, const numeric *var2, numeric *result)
void mul_var (const numeric *var1, const numeric *var2, numeric *result, int rscale)
void div_var (const numeric *var1, const numeric *var2, numeric *result, int rscale, bool round)
void div_var_fast (const numeric *var1, const numeric *var2, numeric *result, int rscale, bool round)
int select_div_scale (const numeric *var1, const numeric *var2)
void mod_var (const numeric *var1, const numeric *var2, numeric *result)
void ceil_var (const numeric *var, numeric *result)
void floor_var (const numeric *var, numeric *result)
void sqrt_var (const numeric *arg, numeric *result, int rscale)
void exp_var (const numeric *arg, numeric *result, int rscale)
int estimate_ln_dweight (const numeric *var)
void ln_var (const numeric *arg, numeric *result, int rscale)
void log_var (const numeric *base, const numeric *num, numeric *result)
void power_var (const numeric *base, const numeric *exp, numeric *result)
void power_var_int (const numeric *base, int exp, numeric *result, int rscale)
int cmp_abs (const numeric *var1, const numeric *var2)
void add_abs (const numeric *var1, const numeric *var2, numeric *result)
void sub_abs (const numeric *var1, const numeric *var2, numeric *result)
void round_var (numeric *var, int rscale)
void trunc_var (numeric *var, int rscale)
void strip_var (numeric *var)
std::ostream & operator<< (std::ostream &s, const numeric &v)
Constructor & Destructor Documentation
numeric() [1/7]
pq_async::numeric::numeric ()
Referenced by from().
numeric() [2/7]
pq_async::numeric::numeric (const numeric & b)
References digitbuf_alloc.
numeric() [3/7]
pq_async::numeric::numeric (const char * s, ssize_t len = -1)
References NUMERIC_NAN, pq_async::pg_strncasecmp(), and set_var_from_str.
numeric() [4/7]
pq_async::numeric::numeric (double val)
numeric() [5/7]
pq_async::numeric::numeric (float val)
numeric() [6/7]
pq_async::numeric::numeric (int64_t val)
numeric() [7/7]
pq_async::numeric::numeric (int32_t val)
~numeric()
pq_async::numeric::~numeric ()
References digitbuf_free.
Member Function Documentation
add()
static void pq_async::numeric::add (const numeric & var1, const numeric & var2, numeric & result) static
cmp()
int pq_async::numeric::cmp (const numeric & var1, const numeric & var2) static
References pq_async::cmp_var_common().
Referenced by pq_async::ceil_var(), pq_async::floor_var(), pq_async::ln_var(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
from() [1/3]
numeric pq_async::numeric::from (int64_t val) static
References int64_to_numericvar.
Referenced by pq_async::exp_var(), and from().
from() [2/3]
numeric pq_async::numeric::from (int32_t val) static
References from().
from() [3/3]
numeric pq_async::numeric::from (double val) static
References pq_async::num_to_str(), and numeric().
is_nan()
bool pq_async::numeric::is_nan () const
References NUMERIC_NAN.
nan()
numeric pq_async::numeric::nan () static
References NUMERIC_NAN.
operator double()
pq_async::numeric::operator double () const
References pq_async::numericvar_to_double_no_overflow().
operator int32_t()
pq_async::numeric::operator int32_t () const
References pq_async::numericvar_to_int32().
operator int64_t()
pq_async::numeric::operator int64_t () const
References numericvar_to_int64.
operator std::string()
pq_async::numeric::operator std::string () const
References get_str_from_var, and pq_async::s.
operator!=()
bool pq_async::numeric::operator!= (const numeric & b) const
References cmp().
operator%()
numeric pq_async::numeric::operator% (const numeric & b) const
References mod_var.
operator%=()
numeric & pq_async::numeric::operator%= (const numeric & b)
References copy_var_to_var, and mod_var.
operator*()
numeric pq_async::numeric::operator* (const numeric & b) const
References mul_var.
operator*=()
numeric & pq_async::numeric::operator*= (const numeric & b)
References copy_var_to_var, and mul_var.
operator+()
numeric pq_async::numeric::operator+ (const numeric & b) const
References add_var.
operator++() [1/2]
numeric & pq_async::numeric::operator++ ()
References add_var, and copy_var_to_var.
operator++() [2/2]
numeric pq_async::numeric::operator++ (int)
operator+=()
numeric & pq_async::numeric::operator+= (const numeric & b)
References add_var, and copy_var_to_var.
operator-()
numeric pq_async::numeric::operator- (const numeric & b) const
References sub_var.
operator--() [1/2]
numeric & pq_async::numeric::operator-- ()
References copy_var_to_var, and sub_var.
operator--() [2/2]
numeric pq_async::numeric::operator-- (int)
operator-=()
numeric & pq_async::numeric::operator-= (const numeric & b)
References copy_var_to_var, and sub_var.
operator/()
numeric pq_async::numeric::operator/ (const numeric & b) const
References div_var.
operator/=()
numeric & pq_async::numeric::operator/= (const numeric & b)
References copy_var_to_var, and div_var.
operator<()
bool pq_async::numeric::operator< (const numeric & b) const
References cmp().
operator<=()
bool pq_async::numeric::operator<= (const numeric & b) const
References cmp().
operator=()
numeric & pq_async::numeric::operator= (const numeric & b)
References digitbuf_alloc, and digitbuf_free.
operator==()
bool pq_async::numeric::operator== (const numeric & b) const
References cmp().
operator>()
bool pq_async::numeric::operator> (const numeric & b) const
References cmp().
operator>=()
bool pq_async::numeric::operator>= (const numeric & b) const
References cmp().
Friends And Related Function Documentation
add_abs
void add_abs (const numeric * var1, const numeric * var2, numeric * result) friend
Referenced by pq_async::add_var(), and pq_async::sub_var().
add_var
void add_var (const numeric * var1, const numeric * var2, numeric * result) friend
Referenced by pq_async::ceil_var(), pq_async::exp_var(), pq_async::ln_var(), operator+(), operator++(), operator+=(), and pq_async::sqrt_var().
alloc_var
void alloc_var (numeric * var, int ndigits) friend
Referenced by pq_async::div_var(), pq_async::div_var_fast(), pq_async::int64_to_numericvar(), pq_async::mul_var(), pq_async::set_var_from_str(), and pq_async::sqrt_var().
ceil_var
void ceil_var (const numeric * var, numeric * result) friend
cmp_abs
int cmp_abs (const numeric * var1, const numeric * var2) friend
Referenced by pq_async::add_var(), and pq_async::sub_var().
cmp_var
int cmp_var (const numeric * var1, const numeric * var2) friend
Referenced by pq_async::estimate_ln_dweight(), pq_async::ln_var(), pq_async::power_var(), and pq_async::sqrt_var().
copy_var_to_var
void copy_var_to_var (const numeric & src, numeric & dest) friend
Referenced by operator%=(), operator*=(), operator++(), operator+=(), operator--(), operator-=(), and operator/=().
div_var
void div_var (const numeric * var1, const numeric * var2, numeric * result, int rscale, bool round) friend
Referenced by pq_async::get_str_from_var_sci(), pq_async::mod_var(), operator/(), operator/=(), and pq_async::power_var_int().
div_var_fast
void div_var_fast (const numeric * var1, const numeric * var2, numeric * result, int rscale, bool round) friend
Referenced by pq_async::exp_var(), pq_async::ln_var(), pq_async::log_var(), pq_async::power_var_int(), and pq_async::sqrt_var().
estimate_ln_dweight
int estimate_ln_dweight (const numeric * var) friend
Referenced by pq_async::log_var(), and pq_async::power_var().
exp_var
void exp_var (const numeric * arg, numeric * result, int rscale) friend
Referenced by pq_async::power_var().
floor_var
void floor_var (const numeric * var, numeric * result) friend
free_var
void free_var (numeric * var) friend
Referenced by pq_async::ceil_var(), pq_async::estimate_ln_dweight(), pq_async::exp_var(), pq_async::floor_var(), pq_async::ln_var(), pq_async::log_var(), pq_async::mod_var(), pq_async::numericvar_to_int64(), pq_async::power_var(), pq_async::power_var_int(), and pq_async::sqrt_var().
get_str_from_var
char* get_str_from_var (const numeric * var) friend
Referenced by pq_async::get_str_from_var_sci(), pq_async::numericvar_to_double_no_overflow(), and operator std::string().
get_str_from_var_sci
char* get_str_from_var_sci (const numeric * var, int rscale) friend
int64_to_numericvar
void int64_to_numericvar (int64_t val, numeric * var) friend
Referenced by from().
ln_var
void ln_var (const numeric * arg, numeric * result, int rscale) friend
Referenced by pq_async::estimate_ln_dweight(), pq_async::log_var(), and pq_async::power_var().
log_var
void log_var (const numeric * base, const numeric * num, numeric * result) friend
mod_var
void mod_var (const numeric * var1, const numeric * var2, numeric * result) friend
Referenced by operator%(), and operator%=().
mul_var
void mul_var (const numeric * var1, const numeric * var2, numeric * result, int rscale) friend
Referenced by pq_async::exp_var(), pq_async::ln_var(), pq_async::mod_var(), operator*(), operator*=(), pq_async::power_var(), pq_async::power_var_int(), and pq_async::sqrt_var().
new_parameter [1/2]
pq_async::parameter* new_parameter (const pq_async::numeric & value) friend
new_parameter [2/2]
pq_async::parameter* new_parameter (const pq_async::numrange & value) friend
numericvar_to_int64
bool numericvar_to_int64 (const numeric * var, int64_t * result) friend
Referenced by pq_async::numericvar_to_int32(), operator int64_t(), and pq_async::power_var().
operator<<
std::ostream& operator<< (std::ostream & s, const numeric & v) friend
pgval_to_numeric
pq_async::numeric pgval_to_numeric (char * val, int len, int fmt) friend
power_var
void power_var (const numeric * base, const numeric * exp, numeric * result) friend
power_var_int
void power_var_int (const numeric * base, int exp, numeric * result, int rscale) friend
Referenced by pq_async::get_str_from_var_sci(), and pq_async::power_var().
round_var
void round_var (numeric * var, int rscale) friend
Referenced by pq_async::div_var(), pq_async::div_var_fast(), pq_async::exp_var(), pq_async::mul_var(), pq_async::numericvar_to_int64(), pq_async::power_var_int(), and pq_async::sqrt_var().
select_div_scale
int select_div_scale (const numeric * var1, const numeric * var2) friend
set_var_from_str
const char* set_var_from_str (const char * str, const char * cp, numeric * dest) friend
Referenced by numeric().
sqrt_var
void sqrt_var (const numeric * arg, numeric * result, int rscale) friend
Referenced by pq_async::ln_var().
strip_var
void strip_var (numeric * var) friend
Referenced by pq_async::add_abs(), pq_async::div_var(), pq_async::div_var_fast(), pq_async::mul_var(), pq_async::numericvar_to_int64(), pq_async::set_var_from_str(), and pq_async::sub_abs().
sub_abs
void sub_abs (const numeric * var1, const numeric * var2, numeric * result) friend
Referenced by pq_async::add_var(), and pq_async::sub_var().
sub_var
void sub_var (const numeric * var1, const numeric * var2, numeric * result) friend
Referenced by pq_async::estimate_ln_dweight(), pq_async::floor_var(), pq_async::ln_var(), pq_async::mod_var(), operator-(), operator--(), and operator-=().
trunc_var
void trunc_var (numeric * var, int rscale) friend
Referenced by pq_async::ceil_var(), pq_async::div_var(), pq_async::div_var_fast(), and pq_async::floor_var().
zero_var
void zero_var (numeric * var) friend
Referenced by pq_async::add_var(), pq_async::div_var(), pq_async::div_var_fast(), pq_async::mul_var(), pq_async::power_var_int(), pq_async::sqrt_var(), and pq_async::sub_var().
The documentation for this class was generated from the following files:
src/pg_type_numeric_def.h
src/pg_type_numeric_def.cpp