libpq-async++: pq_async::event_strand< T > Class Template Reference
pq_async::event_strand< T > Class Template Reference
#include <src/event_queue.h>
Public Member Functions
event_strand (bool auto_requeue=true)
event_strand (event_queue *owner, bool auto_requeue=true)
virtual ~event_strand ()
virtual bool force_push ()
virtual size_t size () const
virtual event_requeue_pos requeue ()
T data ()
void data (T val)
template<typename Task >
uint64_t push_back (Task task)
template<typename Task >
uint64_t push_front (Task task)
virtual void run_task ()
void requeue_self_back ()
void requeue_self_front ()
Public Member Functions inherited from pq_async::event_queue
event_queue ()
virtual ~event_queue ()
Destructor.
virtual bool is_thread_safe ()
size_t local_size () const
template<typename T = int>
sp_event_strand< T > new_strand (bool auto_requeue=true)
template<typename Task >
uint64_t push_back (Task task)
template<typename Task >
uint64_t push_front (Task task)
bool cancel_task (uint64_t task_id)
template<typename Iterator , typename T >
void each (Iterator first, Iterator last, T cb, async_cb end_cb)
void series (std::vector< async_series_cb > cbs, async_cb end_cb)
virtual void run_n (uint32_t count=1)
virtual void run (uint32_t usec_wait=1)
Public Member Functions inherited from pq_async::event_task_base
event_task_base (event_queue *owner)
virtual ~event_task_base ()
event_queue * owner ()
uint64_t id () const
virtual void switch_owner (event_queue *new_owner, bool requeue=false)
Friends
class pq_async::event_queue
template<typename Task >
uint64_t _event_strand_push_back (event_queue *eq, Task task)
uint64_t _event_strand_push_back (event_queue *eq, sp_event_task task)
template<typename Task >
uint64_t _event_strand_push_front (event_queue *eq, Task task)
uint64_t _event_strand_push_front (event_queue *eq, sp_event_task task)
Additional Inherited Members
Static Public Member Functions inherited from pq_async::event_queue
static event_queue * get_default ()
static void destroy_default ()
Protected Attributes inherited from pq_async::event_task_base
event_queue * _owner
uint64_t _id
Constructor & Destructor Documentation
event_strand() [1/2]
template<typename T = int> pq_async::event_strand< T >::event_strand (bool auto_requeue = true) inline
event_strand() [2/2]
template<typename T = int> pq_async::event_strand< T >::event_strand (event_queue * owner, bool auto_requeue = true) inline
~event_strand()
template<typename T = int> virtual pq_async::event_strand< T >::~event_strand () inline virtual
References pq_async::event_task_base::_owner, and pq_async::event_queue::push_back().
Member Function Documentation
data() [1/2]
template<typename T = int> T pq_async::event_strand< T >::data () inline
data() [2/2]
template<typename T = int> void pq_async::event_strand< T >::data (T val) inline
force_push()
template<typename T = int> virtual bool pq_async::event_strand< T >::force_push () inline virtual
Reimplemented from pq_async::event_task_base.
push_back()
template<typename T = int> template<typename Task > uint64_t pq_async::event_strand< T >::push_back (Task task) inline
References pq_async::event_queue::_event_queue_push_back, pq_async::event_task_base::_owner, pq_async::event_task_base::id(), PQ_ASYNC_LOCK_EVENT_QUEUE, PQ_ASYNC_TO_TASKBASE, and pq_async::event_queue::push_back().
push_front()
template<typename T = int> template<typename Task > uint64_t pq_async::event_strand< T >::push_front (Task task) inline
References pq_async::event_queue::_event_queue_push_front, pq_async::event_task_base::_owner, pq_async::event_task_base::id(), PQ_ASYNC_LOCK_EVENT_QUEUE, PQ_ASYNC_TO_TASKBASE, and pq_async::event_queue::push_back().
requeue()
template<typename T = int> virtual event_requeue_pos pq_async::event_strand< T >::requeue () inline virtual
Implements pq_async::event_task_base.
References pq_async::back, pq_async::none, and pq_async::event_strand< T >::size().
requeue_self_back()
template<typename T = int> void pq_async::event_strand< T >::requeue_self_back () inline
References pq_async::event_task_base::_owner, PQ_ASYNC_TO_TASKBASE, and pq_async::event_queue::push_back().
requeue_self_front()
template<typename T = int> void pq_async::event_strand< T >::requeue_self_front () inline
References pq_async::event_task_base::_owner, PQ_ASYNC_TO_TASKBASE, and pq_async::event_queue::push_front().
run_task()
template<typename T = int> virtual void pq_async::event_strand< T >::run_task () inline virtual
Implements pq_async::event_task_base.
References pq_async::event_queue::run_n().
size()
template<typename T = int> virtual size_t pq_async::event_strand< T >::size () const inline virtual
Implements pq_async::event_task_base.
Referenced by pq_async::event_strand< T >::requeue().
Friends And Related Function Documentation
_event_strand_push_back [1/2]
template<typename T = int> template<typename Task > uint64_t _event_strand_push_back (event_queue * eq, Task task) friend
_event_strand_push_back [2/2]
template<typename T = int> uint64_t _event_strand_push_back (event_queue * eq, sp_event_task task) friend
_event_strand_push_front [1/2]
template<typename T = int> template<typename Task > uint64_t _event_strand_push_front (event_queue * eq, Task task) friend
_event_strand_push_front [2/2]
template<typename T = int> uint64_t _event_strand_push_front (event_queue * eq, sp_event_task task) friend
pq_async::event_queue
template<typename T = int> friend class pq_async::event_queue friend
The documentation for this class was generated from the following files:
src/event_queue.h
src/event_strand.h