libpq-async++: pq_async::data_row Class Reference
pq_async::data_row Class Reference
#include <src/data_row.h>
Public Member Functions
data_row (sp_data_columns_container cols, PGresult *row_result, int row_id)
virtual ~data_row ()
sp_data_value get_value (uint32_t i) const
sp_data_value get_value (const char *col_name) const
sp_data_value get_value (const std::string &col_name) const
sp_data_value operator[] (uint32_t i) const
sp_data_value operator[] (const char *col_name) const
sp_data_value operator[] (const std::string &col_name) const
sp_data_value operator() (uint32_t i) const
sp_data_value operator() (const char *col_name) const
sp_data_value operator() (const std::string &col_name) const
void to_json (pq_async::json &row_obj) const
void to_json_string (std::string &str, const unsigned int current_indent=0) const
sp_data_columns_container columns ()
bool is_null (int i) const
bool is_null (const char *col_name) const
template<typename T >
T as (int i) const
template<typename T >
T as (const char *col_name) const
bool as_bool (const char *col_name) const
bool as_bool (int32_t i) const
std::string as_text (const char *col_name) const
std::string as_text (int32_t i) const
int16_t as_int16 (const char *col_name) const
int16_t as_int16 (int32_t i) const
int32_t as_int32 (const char *col_name) const
int32_t as_int32 (int32_t i) const
int64_t as_int64 (const char *col_name) const
int64_t as_int64 (int32_t i) const
pq_async::numeric as_numeric (const char *col_name) const
pq_async::numeric as_numeric (int32_t i) const
pq_async::money as_money (const char *col_name) const
pq_async::money as_money (int32_t i) const
float as_float (const char *col_name) const
float as_float (int32_t i) const
double as_double (const char *col_name) const
double as_double (int32_t i) const
pq_async::time as_time (const char *col_name) const
pq_async::time as_time (int32_t i) const
pq_async::time_tz as_time_tz (const char *col_name) const
pq_async::time_tz as_time_tz (int32_t i) const
pq_async::timestamp as_timestamp (const char *col_name) const
pq_async::timestamp as_timestamp (int32_t i) const
pq_async::timestamp_tz as_timestamp_tz (const char *col_name) const
pq_async::timestamp_tz as_timestamp_tz (int32_t i) const
pq_async::date as_date (const char *col_name) const
pq_async::date as_date (int32_t i) const
pq_async::interval as_interval (const char *col_name) const
pq_async::interval as_interval (int32_t i) const
pq_async::json as_json (const char *col_name) const
pq_async::json as_json (int32_t i) const
std::vector< int8_t > as_bytea (const char *col_name) const
std::vector< int8_t > as_bytea (int32_t i) const
pq_async::uuid as_uuid (const char *col_name) const
pq_async::uuid as_uuid (int32_t i) const
pq_async::oid as_oid (const char *col_name) const
pq_async::oid as_oid (int32_t i) const
pq_async::cidr as_cidr (const char *col_name) const
pq_async::cidr as_cidr (int32_t i) const
pq_async::inet as_inet (const char *col_name) const
pq_async::inet as_inet (int32_t i) const
pq_async::macaddr as_macaddr (const char *col_name) const
pq_async::macaddr as_macaddr (int32_t i) const
pq_async::macaddr8 as_macaddr8 (const char *col_name) const
pq_async::macaddr8 as_macaddr8 (int32_t i) const
pq_async::point as_point (const char *col_name) const
pq_async::point as_point (int32_t i) const
pq_async::line as_line (const char *col_name) const
pq_async::line as_line (int32_t i) const
pq_async::lseg as_lseg (const char *col_name) const
pq_async::lseg as_lseg (int32_t i) const
pq_async::box as_box (const char *col_name) const
pq_async::box as_box (int32_t i) const
pq_async::path as_path (const char *col_name) const
pq_async::path as_path (int32_t i) const
pq_async::polygon as_polygon (const char *col_name) const
pq_async::polygon as_polygon (int32_t i) const
pq_async::circle as_circle (const char *col_name) const
pq_async::circle as_circle (int32_t i) const
pq_async::int4range as_int4range (const char *col_name) const
pq_async::int4range as_int4range (int32_t i) const
pq_async::int8range as_int8range (const char *col_name) const
pq_async::int8range as_int8range (int32_t i) const
pq_async::numrange as_numrange (const char *col_name) const
pq_async::numrange as_numrange (int32_t i) const
pq_async::tsrange as_tsrange (const char *col_name) const
pq_async::tsrange as_tsrange (int32_t i) const
pq_async::tstzrange as_tstzrange (const char *col_name) const
pq_async::tstzrange as_tstzrange (int32_t i) const
pq_async::daterange as_daterange (const char *col_name) const
pq_async::daterange as_daterange (int32_t i) const
bool is_array (const char *col_name) const
int get_array_ele_oid (const char *col_name) const
int get_array_dim (const char *col_name) const
template<class T , int32_t dim_count>
boost::multi_array< T, dim_count > as_array (const char *col_name) const
bool is_array (uint32_t i) const
int get_array_ele_oid (uint32_t i) const
int get_array_dim (uint32_t i) const
template<class T , int32_t dim_count>
boost::multi_array< T, dim_count > as_array (uint32_t i) const
Constructor & Destructor Documentation
data_row()
pq_async::data_row::data_row (sp_data_columns_container cols, PGresult * row_result, int row_id)
References pq_async_log_trace.
~data_row()
pq_async::data_row::~data_row () virtual
References pq_async_log_trace.
Member Function Documentation
as() [1/2]
template<typename T > T pq_async::data_row::as (int i) const inline
References get_value().
as() [2/2]
template<typename T > T pq_async::data_row::as (const char * col_name) const inline
References get_value().
as_array() [1/2]
template<class T , int32_t dim_count> boost::multi_array<T, dim_count> pq_async::data_row::as_array (const char * col_name) const inline
References get_value().
as_array() [2/2]
template<class T , int32_t dim_count> boost::multi_array<T, dim_count> pq_async::data_row::as_array (uint32_t i) const inline
References get_value().
as_bool() [1/2]
bool pq_async::data_row::as_bool (const char * col_name) const inline
as_bool() [2/2]
bool pq_async::data_row::as_bool (int32_t i) const inline
as_box() [1/2]
pq_async::box pq_async::data_row::as_box (const char * col_name) const inline
as_box() [2/2]
pq_async::box pq_async::data_row::as_box (int32_t i) const inline
as_bytea() [1/2]
std::vector<int8_t> pq_async::data_row::as_bytea (const char * col_name) const inline
as_bytea() [2/2]
std::vector<int8_t> pq_async::data_row::as_bytea (int32_t i) const inline
as_cidr() [1/2]
pq_async::cidr pq_async::data_row::as_cidr (const char * col_name) const inline
as_cidr() [2/2]
pq_async::cidr pq_async::data_row::as_cidr (int32_t i) const inline
as_circle() [1/2]
pq_async::circle pq_async::data_row::as_circle (const char * col_name) const inline
as_circle() [2/2]
pq_async::circle pq_async::data_row::as_circle (int32_t i) const inline
as_date() [1/2]
pq_async::date pq_async::data_row::as_date (const char * col_name) const inline
as_date() [2/2]
pq_async::date pq_async::data_row::as_date (int32_t i) const inline
as_daterange() [1/2]
pq_async::daterange pq_async::data_row::as_daterange (const char * col_name) const inline
as_daterange() [2/2]
pq_async::daterange pq_async::data_row::as_daterange (int32_t i) const inline
as_double() [1/2]
double pq_async::data_row::as_double (int32_t i) const inline
as_double() [2/2]
double pq_async::data_row::as_double (const char * col_name) const inline
as_float() [1/2]
float pq_async::data_row::as_float (int32_t i) const inline
as_float() [2/2]
float pq_async::data_row::as_float (const char * col_name) const inline
as_inet() [1/2]
pq_async::inet pq_async::data_row::as_inet (const char * col_name) const inline
as_inet() [2/2]
pq_async::inet pq_async::data_row::as_inet (int32_t i) const inline
as_int16() [1/2]
int16_t pq_async::data_row::as_int16 (const char * col_name) const inline
as_int16() [2/2]
int16_t pq_async::data_row::as_int16 (int32_t i) const inline
as_int32() [1/2]
int32_t pq_async::data_row::as_int32 (const char * col_name) const inline
as_int32() [2/2]
int32_t pq_async::data_row::as_int32 (int32_t i) const inline
as_int4range() [1/2]
pq_async::int4range pq_async::data_row::as_int4range (const char * col_name) const inline
as_int4range() [2/2]
pq_async::int4range pq_async::data_row::as_int4range (int32_t i) const inline
as_int64() [1/2]
int64_t pq_async::data_row::as_int64 (const char * col_name) const inline
as_int64() [2/2]
int64_t pq_async::data_row::as_int64 (int32_t i) const inline
as_int8range() [1/2]
pq_async::int8range pq_async::data_row::as_int8range (const char * col_name) const inline
as_int8range() [2/2]
pq_async::int8range pq_async::data_row::as_int8range (int32_t i) const inline
as_interval() [1/2]
pq_async::interval pq_async::data_row::as_interval (const char * col_name) const inline
as_interval() [2/2]
pq_async::interval pq_async::data_row::as_interval (int32_t i) const inline
as_json() [1/2]
pq_async::json pq_async::data_row::as_json (const char * col_name) const inline
as_json() [2/2]
pq_async::json pq_async::data_row::as_json (int32_t i) const inline
as_line() [1/2]
pq_async::line pq_async::data_row::as_line (const char * col_name) const inline
as_line() [2/2]
pq_async::line pq_async::data_row::as_line (int32_t i) const inline
as_lseg() [1/2]
pq_async::lseg pq_async::data_row::as_lseg (const char * col_name) const inline
as_lseg() [2/2]
pq_async::lseg pq_async::data_row::as_lseg (int32_t i) const inline
as_macaddr() [1/2]
pq_async::macaddr pq_async::data_row::as_macaddr (const char * col_name) const inline
as_macaddr() [2/2]
pq_async::macaddr pq_async::data_row::as_macaddr (int32_t i) const inline
as_macaddr8() [1/2]
pq_async::macaddr8 pq_async::data_row::as_macaddr8 (const char * col_name) const inline
as_macaddr8() [2/2]
pq_async::macaddr8 pq_async::data_row::as_macaddr8 (int32_t i) const inline
as_money() [1/2]
pq_async::money pq_async::data_row::as_money (const char * col_name) const inline
as_money() [2/2]
pq_async::money pq_async::data_row::as_money (int32_t i) const inline
as_numeric() [1/2]
pq_async::numeric pq_async::data_row::as_numeric (const char * col_name) const inline
as_numeric() [2/2]
pq_async::numeric pq_async::data_row::as_numeric (int32_t i) const inline
as_numrange() [1/2]
pq_async::numrange pq_async::data_row::as_numrange (const char * col_name) const inline
as_numrange() [2/2]
pq_async::numrange pq_async::data_row::as_numrange (int32_t i) const inline
as_oid() [1/2]
pq_async::oid pq_async::data_row::as_oid (const char * col_name) const inline
as_oid() [2/2]
pq_async::oid pq_async::data_row::as_oid (int32_t i) const inline
as_path() [1/2]
pq_async::path pq_async::data_row::as_path (const char * col_name) const inline
as_path() [2/2]
pq_async::path pq_async::data_row::as_path (int32_t i) const inline
as_point() [1/2]
pq_async::point pq_async::data_row::as_point (int32_t i) const inline
as_point() [2/2]
pq_async::point pq_async::data_row::as_point (const char * col_name) const inline
as_polygon() [1/2]
pq_async::polygon pq_async::data_row::as_polygon (const char * col_name) const inline
as_polygon() [2/2]
pq_async::polygon pq_async::data_row::as_polygon (int32_t i) const inline
as_text() [1/2]
std::string pq_async::data_row::as_text (const char * col_name) const inline
as_text() [2/2]
std::string pq_async::data_row::as_text (int32_t i) const inline
as_time() [1/2]
pq_async::time pq_async::data_row::as_time (int32_t i) const inline
as_time() [2/2]
pq_async::time pq_async::data_row::as_time (const char * col_name) const inline
as_time_tz() [1/2]
pq_async::time_tz pq_async::data_row::as_time_tz (int32_t i) const inline
as_time_tz() [2/2]
pq_async::time_tz pq_async::data_row::as_time_tz (const char * col_name) const inline
as_timestamp() [1/2]
pq_async::timestamp pq_async::data_row::as_timestamp (const char * col_name) const inline
as_timestamp() [2/2]
pq_async::timestamp pq_async::data_row::as_timestamp (int32_t i) const inline
as_timestamp_tz() [1/2]
pq_async::timestamp_tz pq_async::data_row::as_timestamp_tz (const char * col_name) const inline
as_timestamp_tz() [2/2]
pq_async::timestamp_tz pq_async::data_row::as_timestamp_tz (int32_t i) const inline
as_tsrange() [1/2]
pq_async::tsrange pq_async::data_row::as_tsrange (const char * col_name) const inline
as_tsrange() [2/2]
pq_async::tsrange pq_async::data_row::as_tsrange (int32_t i) const inline
as_tstzrange() [1/2]
pq_async::tstzrange pq_async::data_row::as_tstzrange (const char * col_name) const inline
as_tstzrange() [2/2]
pq_async::tstzrange pq_async::data_row::as_tstzrange (int32_t i) const inline
as_uuid() [1/2]
pq_async::uuid pq_async::data_row::as_uuid (const char * col_name) const inline
as_uuid() [2/2]
pq_async::uuid pq_async::data_row::as_uuid (int32_t i) const inline
columns()
sp_data_columns_container pq_async::data_row::columns () inline
get_array_dim() [1/2]
int pq_async::data_row::get_array_dim (const char * col_name) const inline
References get_value().
get_array_dim() [2/2]
int pq_async::data_row::get_array_dim (uint32_t i) const inline
References get_value().
get_array_ele_oid() [1/2]
int pq_async::data_row::get_array_ele_oid (const char * col_name) const inline
References get_value().
get_array_ele_oid() [2/2]
int pq_async::data_row::get_array_ele_oid (uint32_t i) const inline
References get_value().
get_value() [1/3]
sp_data_value pq_async::data_row::get_value (uint32_t i) const
Referenced by as(), as_array(), get_array_dim(), get_array_ele_oid(), get_value(), is_array(), is_null(), operator()(), and operator[]().
get_value() [2/3]
sp_data_value pq_async::data_row::get_value (const char * col_name) const
get_value() [3/3]
sp_data_value pq_async::data_row::get_value (const std::string & col_name) const inline
References get_value().
is_array() [1/2]
bool pq_async::data_row::is_array (const char * col_name) const inline
References get_value().
is_array() [2/2]
bool pq_async::data_row::is_array (uint32_t i) const inline
References get_value().
is_null() [1/2]
bool pq_async::data_row::is_null (int i) const inline
References get_value().
Referenced by to_json().
is_null() [2/2]
bool pq_async::data_row::is_null (const char * col_name) const inline
References get_value().
operator()() [1/3]
sp_data_value pq_async::data_row::operator() (uint32_t i) const inline
References get_value().
operator()() [2/3]
sp_data_value pq_async::data_row::operator() (const char * col_name) const inline
References get_value().
operator()() [3/3]
sp_data_value pq_async::data_row::operator() (const std::string & col_name) const inline
References get_value(), to_json(), and to_json_string().
operator[]() [1/3]
sp_data_value pq_async::data_row::operator[] (uint32_t i) const inline
References get_value().
operator[]() [2/3]
sp_data_value pq_async::data_row::operator[] (const char * col_name) const inline
References get_value().
operator[]() [3/3]
sp_data_value pq_async::data_row::operator[] (const std::string & col_name) const inline
References get_value().
to_json()
void pq_async::data_row::to_json (pq_async::json & row_obj) const
References _PQ_ASYNC_TO_JSON, BOOLARRAYOID, BOOLOID, BOXARRAYOID, BOXOID, pq_async::bytea, BYTEAARRAYOID, BYTEAOID, CASHOID, CIDARRAYOID, CIDROID, CIRCLEARRAYOID, CIRCLEOID, DATEARRAYOID, DATEOID, DATERANGEARRAYOID, DATERANGEOID, FLOAT4ARRAYOID, FLOAT4OID, FLOAT8ARRAYOID, FLOAT8OID, INETARRAYOID, INETOID, INT2ARRAYOID, INT2OID, INT4ARRAYOID, INT4OID, INT4RANGEARRAYOID, INT4RANGEOID, INT8ARRAYOID, INT8OID, INT8RANGEARRAYOID, INT8RANGEOID, INTERVALARRAYOID, INTERVALOID, is_null(), JSONARRAYOID, JSONBARRAYOID, JSONBOID, JSONOID, LINEARRAYOID, LINEOID, LSEGARRAYOID, LSEGOID, MACADDR8ARRAYOID, MACADDR8OID, MACADDRARRAYOID, MACADDROID, MONEYARRAYOID, NUMERICARRAYOID, NUMERICOID, NUMRANGEARRAYOID, NUMRANGEOID, OIDARRAYOID, OIDOID, PATHARRAYOID, PATHOID, POINTARRAYOID, POINTOID, POLYGONARRAYOID, POLYGONOID, pq_async_log_trace, pq_async::text, TEXTARRAYOID, TEXTOID, TIMEARRAYOID, TIMEOID, TIMESTAMPARRAYOID, TIMESTAMPOID, TIMESTAMPTZARRAYOID, TIMESTAMPTZOID, TIMETZARRAYOID, TIMETZOID, TSRANGEARRAYOID, TSRANGEOID, TSTZRANGEARRAYOID, TSTZRANGEOID, UUIDARRAYOID, and UUIDOID.
Referenced by operator()(), and to_json_string().
to_json_string()
void pq_async::data_row::to_json_string (std::string & str, const unsigned int current_indent = 0) const
References to_json().
Referenced by operator()().
The documentation for this class was generated from the following files:
src/data_row.h
src/data_row.cpp