libpq-async++: pq_async::data_reader Class Reference
pq_async::data_reader Class Reference
#include <src/data_reader.h>
Public Member Functions
~data_reader ()
sp_database db ()
bool closed ()
template<typename T , typename std::enable_if< !std::is_same< sp_data_row, typename std::remove_pointer< T >::type >::value &&!std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, sp_data_row >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, sp_data_row >::value), int32_t >::type = -1>
void next (T tcb)
sp_data_row next ()
void close ()
Friends
class database
class data_prepared
Constructor & Destructor Documentation
~data_reader()
pq_async::data_reader::~data_reader () inline
References close().
Member Function Documentation
close()
void pq_async::data_reader::close () inline
References pq_async_log_error.
Referenced by next(), and ~data_reader().
closed()
bool pq_async::data_reader::closed () inline
db()
sp_database pq_async::data_reader::db () inline
next() [1/2]
template<typename T , typename std::enable_if< !std::is_same< sp_data_row, typename std::remove_pointer< T >::type >::value &&!std::is_array< typename std::remove_pointer< T >::type >::value &&(std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &>::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, const cb_error &, sp_data_row >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type >::value||std::is_invocable_r< void, typename std::remove_pointer< T >::type, sp_data_row >::value), int32_t >::type = -1> void pq_async::data_reader::next (T tcb) inline
next() [2/2]
sp_data_row pq_async::data_reader::next () inline
References close().
Friends And Related Function Documentation
data_prepared
friend class data_prepared friend
database
friend class database friend
The documentation for this class was generated from the following file:
src/data_reader.h