libpq-async++: pq_async::timestamp_tz Class Reference
pq_async::timestamp_tz Class Reference
#include <src/pg_type_date_def.h>
Public Member Functions
timestamp_tz ()
timestamp_tz (int64_t pgticks)
template<typename Dur >
timestamp_tz (const hhdate::zoned_time< Dur > &ts)
timestamp_tz (const timestamp &ts)
const hhdate::time_zone * zone () const
int64_t pgticks () const
std::string iso_string () const
operator std::string () const
template<typename Dur >
operator hhdate::sys_time< Dur > () const
template<typename Dur >
operator hhdate::zoned_time< Dur > () const
timestamp_tz as_zone (const char *zone_name) const
timestamp_tz make_zoned (const char *zone_name) const
Static Public Member Functions
static timestamp_tz parse (const std::string &s)
Friends
class timestamp
std::ostream & operator<< (std::ostream &os, const timestamp_tz &v)
std::istream & operator>> (std::istream &is, timestamp_tz &v)
Constructor & Destructor Documentation
timestamp_tz() [1/4]
pq_async::timestamp_tz::timestamp_tz () inline
References pq_async::interval::pgticks(), and pq_async::timestamp_tz.
Referenced by as_zone(), and make_zoned().
timestamp_tz() [2/4]
pq_async::timestamp_tz::timestamp_tz (int64_t pgticks)
timestamp_tz() [3/4]
template<typename Dur > pq_async::timestamp_tz::timestamp_tz (const hhdate::zoned_time< Dur > & ts) inline explicit
References pq_async::timestamp_tz.
timestamp_tz() [4/4]
pq_async::timestamp_tz::timestamp_tz (const timestamp & ts) explicit
Member Function Documentation
as_zone()
timestamp_tz pq_async::timestamp_tz::as_zone (const char * zone_name) const
References timestamp_tz().
iso_string()
std::string pq_async::timestamp_tz::iso_string () const
Referenced by pq_async::operator<<(), and pq_async::tests::TEST_F().
make_zoned()
timestamp_tz pq_async::timestamp_tz::make_zoned (const char * zone_name) const
References timestamp_tz().
Referenced by pq_async::tests::TEST_F().
operator hhdate::sys_time< Dur >()
template<typename Dur > pq_async::timestamp_tz::operator hhdate::sys_time< Dur > () const inline
operator hhdate::zoned_time< Dur >()
template<typename Dur > pq_async::timestamp_tz::operator hhdate::zoned_time< Dur > () const inline
References pq_async::interval::parse(), and pq_async::s.
operator std::string()
pq_async::timestamp_tz::operator std::string () const inline
References pq_async::interval::iso_string().
parse()
timestamp_tz pq_async::timestamp_tz::parse (const std::string & s) static
Referenced by pq_async::range< T >::operator std::string(), and pq_async::operator>>().
pgticks()
int64_t pq_async::timestamp_tz::pgticks () const inline
References pq_async::interval::iso_string().
Referenced by pq_async::new_parameter().
zone()
const hhdate::time_zone* pq_async::timestamp_tz::zone () const inline
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const timestamp_tz & v) friend
operator>>
std::istream& operator>> (std::istream & is, timestamp_tz & v) friend
timestamp
friend class timestamp friend
The documentation for this class was generated from the following files:
src/pg_type_date_def.h
src/pg_type_date_def.cpp