libpq-async++: pq_async::log Class Reference
pq_async::log Class Reference
#include <src/log.h>
Static Public Member Functions
static std::string get_errno_msg ()
static log_level get_level ()
static void set_level (log_level level)
static bool is_color_enabled ()
static void enable_color (bool color)
static void init (const std::string &app_name, int level, bool enable_source)
static std::string level_to_str (log_level level)
static const std::string & machine_id ()
static void fatal (const char *log_name, const char *file, int line, const char *fn, const char *msg,...)
static void error (const char *log_name, const char *file, int line, const char *fn, const char *msg,...)
static void warning (const char *log_name, const char *file, int line, const char *fn, const char *msg,...)
static void info (const char *log_name, const char *file, int line, const char *fn, const char *msg,...)
static void debug (const char *log_name, const char *file, int line, const char *fn, const char *msg,...)
static void trace (const char *log_name, const char *file, int line, const char *fn, const char *msg,...)
Member Function Documentation
debug()
static void pq_async::log::debug (const char * log_name, const char * file, int line, const char * fn, const char * msg, ...) inline static
References pq_async::ll_debug.
enable_color()
static void pq_async::log::enable_color (bool color) inline static
error()
static void pq_async::log::error (const char * log_name, const char * file, int line, const char * fn, const char * msg, ...) inline static
References pq_async::ll_error.
fatal()
static void pq_async::log::fatal (const char * log_name, const char * file, int line, const char * fn, const char * msg, ...) inline static
References pq_async::ll_fatal.
get_errno_msg()
static std::string pq_async::log::get_errno_msg () inline static
get_level()
static log_level pq_async::log::get_level () inline static
info()
static void pq_async::log::info (const char * log_name, const char * file, int line, const char * fn, const char * msg, ...) inline static
References pq_async::ll_info.
init()
void pq_async::log::init (const std::string & app_name, int level, bool enable_source) static
References level_to_str(), pq_async::ll_debug, pq_async::ll_error, pq_async::ll_fatal, pq_async::ll_info, pq_async::ll_trace, pq_async::ll_warning, pq_async_log_debug, set_level(), and pq_async::trim().
Referenced by pq_async::tests::pq_async_test_env::SetUp().
is_color_enabled()
static bool pq_async::log::is_color_enabled () inline static
Referenced by pq_async::prepare_footer(), and pq_async::prepare_header().
level_to_str()
std::string pq_async::log::level_to_str (log_level level) static
References pq_async::ll_debug, pq_async::ll_error, pq_async::ll_fatal, pq_async::ll_info, pq_async::ll_trace, and pq_async::ll_warning.
Referenced by init().
machine_id()
const std::string & pq_async::log::machine_id () static
References pq_async::s_machine_id.
set_level()
static void pq_async::log::set_level (log_level level) inline static
Referenced by init().
trace()
static void pq_async::log::trace (const char * log_name, const char * file, int line, const char * fn, const char * msg, ...) inline static
References pq_async::ll_trace.
warning()
static void pq_async::log::warning (const char * log_name, const char * file, int line, const char * fn, const char * msg, ...) inline static
References pq_async::ll_warning.
The documentation for this class was generated from the following files:
src/log.h
src/log.cpp