libpq-async++: pq_async::path Class Reference
pq_async::path Class Reference
#include <src/pg_type_geo_def.h>
Public Member Functions
path ()
path (bool closed, const std::vector< point > &p)
path (const char *str)
operator std::string () const
bool closed () const
bool & closed ()
void closed (bool val)
std::vector< point > points () const
std::vector< point > & points ()
Friends
pq_async::path pgval_to_path (char *val, int len, int fmt)
pq_async::parameter * new_parameter (const pq_async::path &value)
std::ostream & operator<< (std::ostream &os, const path &v)
std::istream & operator>> (std::istream &is, path &v)
Constructor & Destructor Documentation
path() [1/3]
pq_async::path::path () inline
path() [2/3]
pq_async::path::path (bool closed, const std::vector< point > & p) inline
References pq_async::path.
path() [3/3]
pq_async::path::path (const char * str)
References pq_async::end(), pq_async::point::point(), pq_async::s, and pq_async::trim().
Member Function Documentation
closed() [1/3]
bool pq_async::path::closed () const inline
Referenced by pq_async::tests::TEST_F().
closed() [2/3]
bool& pq_async::path::closed () inline
closed() [3/3]
void pq_async::path::closed (bool val) inline
operator std::string()
pq_async::path::operator std::string () const
References pq_async::s.
points() [1/2]
std::vector< point > pq_async::path::points () const inline
points() [2/2]
std::vector< point >& pq_async::path::points () inline
Friends And Related Function Documentation
new_parameter
pq_async::parameter* new_parameter (const pq_async::path & value) friend
operator<<
std::ostream& operator<< (std::ostream & os, const path & v) friend
operator>>
std::istream& operator>> (std::istream & is, path & v) friend
pgval_to_path
pq_async::path pgval_to_path (char * val, int len, int fmt) friend
The documentation for this class was generated from the following files:
src/pg_type_geo_def.h
src/pg_type_geo_def.cpp