libpq-async++: pq_async::time_tz Class Reference
pq_async::time_tz Class Reference
#include <src/pg_type_date_def.h>
Public Member Functions
time_tz ()
time_tz (int64_t pgticks)
time_tz (const char *zone_name, int64_t pgticks)
time_tz (const hhdate::time_zone *zone, int64_t pgticks)
template<typename Dur >
time_tz (const hhdate::zoned_time< Dur > &ts)
time_tz (const time &ts)
const hhdate::time_zone * zone () const
int64_t pgticks () const
std::string iso_string () const
operator std::string () const
template<typename Dur >
operator hhdate::sys_time< Dur > () const
template<typename Dur >
operator hhdate::zoned_time< Dur > () const
time_tz as_zone (const char *zone_name) const
time_tz make_zoned (const char *zone_name) const
Static Public Member Functions
static time_tz parse (const std::string &s)
Friends
class time
std::ostream & operator<< (std::ostream &os, const time_tz &v)
std::istream & operator>> (std::istream &is, time_tz &v)
Constructor & Destructor Documentation
time_tz() [1/6]
pq_async::time_tz::time_tz ()
time_tz() [2/6]
pq_async::time_tz::time_tz (int64_t pgticks)
time_tz() [3/6]
pq_async::time_tz::time_tz (const char * zone_name, int64_t pgticks) inline
time_tz() [4/6]
pq_async::time_tz::time_tz (const hhdate::time_zone * zone, int64_t pgticks) inline
time_tz() [5/6]
template<typename Dur > pq_async::time_tz::time_tz (const hhdate::zoned_time< Dur > & ts) inline explicit
References pq_async::time_tz.
time_tz() [6/6]
pq_async::time_tz::time_tz (const time & ts) explicit
Member Function Documentation
as_zone()
time_tz pq_async::time_tz::as_zone (const char * zone_name) const
References pq_async::time_tz.
iso_string()
std::string pq_async::time_tz::iso_string () const
Referenced by pq_async::operator<<(), and pq_async::tests::TEST_F().
make_zoned()
time_tz pq_async::time_tz::make_zoned (const char * zone_name) const
References pq_async::time_tz.
Referenced by pq_async::tests::TEST_F().
operator hhdate::sys_time< Dur >()
template<typename Dur > pq_async::time_tz::operator hhdate::sys_time< Dur > () const inline
operator hhdate::zoned_time< Dur >()
template<typename Dur > pq_async::time_tz::operator hhdate::zoned_time< Dur > () const inline
References pq_async::interval::operator<<, pq_async::interval::operator>>, pq_async::interval::parse(), and pq_async::s.
operator std::string()
pq_async::time_tz::operator std::string () const inline
References pq_async::interval::iso_string().
parse()
time_tz pq_async::time_tz::parse (const std::string & s) static
Referenced by pq_async::operator>>().
pgticks()
int64_t pq_async::time_tz::pgticks () const inline
References pq_async::interval::iso_string().
Referenced by pq_async::new_parameter().
zone()
const hhdate::time_zone* pq_async::time_tz::zone () const inline
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const time_tz & v) friend
operator>>
std::istream& operator>> (std::istream & is, time_tz & v) friend
time
friend class time friend
The documentation for this class was generated from the following files:
src/pg_type_date_def.h
src/pg_type_date_def.cpp