libpq-async++: pq_async::timestamp Class Reference
pq_async::timestamp Class Reference
#include <src/pg_type_date_def.h>
Public Member Functions
timestamp ()
timestamp (int64_t pgticks)
template<typename Dur >
timestamp (const hhdate::sys_time< Dur > &ts)
timestamp (const timestamp_tz &tz)
int64_t pgticks () const
std::string iso_string () const
operator std::string () const
template<typename Dur >
operator hhdate::sys_time< Dur > () const
timestamp_tz as_zone (const char *zone_name) const
timestamp_tz make_zoned (const char *zone_name) const
Static Public Member Functions
static timestamp parse (const std::string &s)
Friends
class timestamp_tz
std::ostream & operator<< (std::ostream &os, const timestamp &v)
std::istream & operator>> (std::istream &is, timestamp &v)
Constructor & Destructor Documentation
timestamp() [1/4]
pq_async::timestamp::timestamp () inline
References pq_async::interval::pgticks(), and pq_async::timestamp.
timestamp() [2/4]
pq_async::timestamp::timestamp (int64_t pgticks)
timestamp() [3/4]
template<typename Dur > pq_async::timestamp::timestamp (const hhdate::sys_time< Dur > & ts) inline explicit
References pq_async::timestamp.
timestamp() [4/4]
pq_async::timestamp::timestamp (const timestamp_tz & tz) explicit
Member Function Documentation
as_zone()
timestamp_tz pq_async::timestamp::as_zone (const char * zone_name) const
References timestamp_tz.
Referenced by pq_async::tests::TEST_F().
iso_string()
std::string pq_async::timestamp::iso_string () const
Referenced by pq_async::operator<<(), and pq_async::tests::TEST_F().
make_zoned()
timestamp_tz pq_async::timestamp::make_zoned (const char * zone_name) const
References timestamp_tz.
operator hhdate::sys_time< Dur >()
template<typename Dur > pq_async::timestamp::operator hhdate::sys_time< Dur > () const inline
References pq_async::interval::parse(), and pq_async::s.
operator std::string()
pq_async::timestamp::operator std::string () const inline
References pq_async::interval::iso_string().
parse()
timestamp pq_async::timestamp::parse (const std::string & s) static
Referenced by pq_async::range< T >::operator std::string(), pq_async::operator>>(), and pq_async::tests::TEST_F().
pgticks()
int64_t pq_async::timestamp::pgticks () const inline
References pq_async::interval::iso_string().
Referenced by pq_async::new_parameter().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const timestamp & v) friend
operator>>
std::istream& operator>> (std::istream & is, timestamp & v) friend
timestamp_tz
friend class timestamp_tz friend
Referenced by as_zone(), and make_zoned().
The documentation for this class was generated from the following files:
src/pg_type_date_def.h
src/pg_type_date_def.cpp