libpq-async++: pq_async::point Class Reference
pq_async::point Class Reference
#include <src/pg_type_geo_def.h>
Public Member Functions
point ()
point (double x, double y)
point (const char *str)
operator std::string () const
double x () const
double y () const
double & x ()
double & y ()
void x (double val)
void y (double val)
bool operator== (const point &b) const
bool operator!= (const point &b) const
bool operator< (const point &b) const
bool operator> (const point &b) const
bool operator<= (const point &b) const
bool operator>= (const point &b) const
point operator+ (const point &b) const
point operator- (const point &b) const
point operator* (const point &b) const
point operator/ (const point &b) const
point & operator+= (const point &b)
point & operator-= (const point &b)
point & operator*= (const point &b)
point & operator/= (const point &b)
point operator- () const
point operator* (const double &s) const
point & operator*= (const double &s)
point operator/ (const double &s) const
point & operator/= (const double &s)
double dot (const point &b) const
double cross (const point &b) const
double magnitude () const
point normal () const
point perpendicular () const
Static Public Member Functions
static double dot (const point &a, const point &b)
static double cross (const point &a, const point &b)
static int cmp (const point &a, const point &b)
Friends
pq_async::point pgval_to_point (char *val, int len, int fmt)
pq_async::parameter * new_parameter (const pq_async::point &value)
pq_async::parameter * new_parameter (const pq_async::line &value)
pq_async::parameter * new_parameter (const pq_async::lseg &value)
pq_async::parameter * new_parameter (const pq_async::box &value)
pq_async::parameter * new_parameter (const pq_async::path &value)
pq_async::parameter * new_parameter (const pq_async::polygon &value)
pq_async::parameter * new_parameter (const pq_async::circle &value)
std::ostream & operator<< (std::ostream &os, const point &v)
std::istream & operator>> (std::istream &is, point &v)
Constructor & Destructor Documentation
point() [1/3]
pq_async::point::point () inline
Referenced by pq_async::box::box(), pq_async::circle::circle(), pq_async::lseg::get_intersect(), pq_async::line::line(), pq_async::lseg::lseg(), normal(), operator*(), operator-(), operator/(), pq_async::operator>>(), pq_async::path::path(), perpendicular(), point(), pq_async::line::point_from_x(), pq_async::line::point_from_y(), and pq_async::polygon::polygon().
point() [2/3]
pq_async::point::point (double x, double y) inline
References point().
point() [3/3]
pq_async::point::point (const char * str)
References pq_async::s, and pq_async::trim().
Member Function Documentation
cmp()
static int pq_async::point::cmp (const point & a, const point & b) inline static
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
cross() [1/2]
double pq_async::point::cross (const point & b) const inline
Referenced by pq_async::lseg::intersect().
cross() [2/2]
static double pq_async::point::cross (const point & a, const point & b) inline static
dot() [1/2]
double pq_async::point::dot (const point & b) const inline
dot() [2/2]
static double pq_async::point::dot (const point & a, const point & b) inline static
magnitude()
double pq_async::point::magnitude () const inline
Referenced by normal().
normal()
point pq_async::point::normal () const inline
References pq_async::m, magnitude(), and point().
operator std::string()
pq_async::point::operator std::string () const
References pq_async::num_to_str().
operator!=()
bool pq_async::point::operator!= (const point & b) const inline
References cmp().
operator*() [1/2]
point pq_async::point::operator* (const point & b) const inline
operator*() [2/2]
point pq_async::point::operator* (const double & s) const inline
References point().
operator*=() [1/2]
point& pq_async::point::operator*= (const point & b) inline
operator*=() [2/2]
point& pq_async::point::operator*= (const double & s) inline
References pq_async::s.
operator+()
point pq_async::point::operator+ (const point & b) const inline
operator+=()
point& pq_async::point::operator+= (const point & b) inline
operator-() [1/2]
point pq_async::point::operator- (const point & b) const inline
operator-() [2/2]
point pq_async::point::operator- () const inline
References point().
operator-=()
point& pq_async::point::operator-= (const point & b) inline
operator/() [1/2]
point pq_async::point::operator/ (const point & b) const inline
operator/() [2/2]
point pq_async::point::operator/ (const double & s) const inline
References point().
operator/=() [1/2]
point& pq_async::point::operator/= (const point & b) inline
operator/=() [2/2]
point& pq_async::point::operator/= (const double & s) inline
References pq_async::s.
operator<()
bool pq_async::point::operator< (const point & b) const inline
References cmp().
operator<=()
bool pq_async::point::operator<= (const point & b) const inline
References cmp().
operator==()
bool pq_async::point::operator== (const point & b) const inline
References cmp().
operator>()
bool pq_async::point::operator> (const point & b) const inline
References cmp().
operator>=()
bool pq_async::point::operator>= (const point & b) const inline
References cmp().
perpendicular()
point pq_async::point::perpendicular () const inline
References point().
x() [1/3]
double pq_async::point::x () const inline
Referenced by pq_async::line::line(), pq_async::line::point_from_x(), pq_async::line::point_from_y(), and pq_async::tests::TEST_F().
x() [2/3]
double& pq_async::point::x () inline
x() [3/3]
void pq_async::point::x (double val) inline
y() [1/3]
double pq_async::point::y () const inline
Referenced by pq_async::line::line(), pq_async::line::point_from_x(), pq_async::line::point_from_y(), and pq_async::tests::TEST_F().
y() [2/3]
double& pq_async::point::y () inline
y() [3/3]
void pq_async::point::y (double val) inline
Friends And Related Function Documentation
new_parameter [1/7]
pq_async::parameter* new_parameter (const pq_async::point & value) friend
new_parameter [2/7]
pq_async::parameter* new_parameter (const pq_async::line & value) friend
new_parameter [3/7]
pq_async::parameter* new_parameter (const pq_async::lseg & value) friend
new_parameter [4/7]
pq_async::parameter* new_parameter (const pq_async::box & value) friend
new_parameter [5/7]
pq_async::parameter* new_parameter (const pq_async::path & value) friend
new_parameter [6/7]
pq_async::parameter* new_parameter (const pq_async::polygon & value) friend
new_parameter [7/7]
pq_async::parameter* new_parameter (const pq_async::circle & value) friend
operator<<
std::ostream& operator<< (std::ostream & os, const point & v) friend
Referenced by pq_async::circle::radius().
operator>>
std::istream& operator>> (std::istream & is, point & v) friend
Referenced by pq_async::circle::radius().
pgval_to_point
pq_async::point pgval_to_point (char * val, int len, int fmt) friend
The documentation for this class was generated from the following files:
src/pg_type_geo_def.h
src/pg_type_geo_def.cpp