libpq-async++: pq_async::interval Class Reference
pq_async::interval Class Reference
#include <src/pg_type_date_def.h>
Public Member Functions
interval ()
interval (int64_t t, int32_t d, int32_t m)
interval (const hhdate::sys_time< std::chrono::microseconds > &t)
int64_t pgticks () const
operator hhdate::sys_time< std::chrono::microseconds > () const
std::string iso_string () const
operator std::string () const
hhdate::time_of_day< std::chrono::microseconds > time_of_day () const
int32_t days () const
int32_t months () const
Static Public Member Functions
static interval parse (const std::string &s)
Friends
std::ostream & operator<< (std::ostream &os, const interval &v)
std::istream & operator>> (std::istream &is, interval &v)
Constructor & Destructor Documentation
interval() [1/3]
pq_async::interval::interval () inline
Referenced by interval(), and parse().
interval() [2/3]
pq_async::interval::interval (int64_t t, int32_t d, int32_t m) inline
References interval().
interval() [3/3]
pq_async::interval::interval (const hhdate::sys_time< std::chrono::microseconds > & t)
Member Function Documentation
days()
int32_t pq_async::interval::days () const inline
Referenced by pq_async::new_parameter().
iso_string()
std::string pq_async::interval::iso_string () const
References pq_async::h, pq_async::m, months(), and pq_async::s.
Referenced by operator hhdate::sys_time< std::chrono::microseconds >(), operator std::string(), pq_async::date::operator std::string(), pq_async::timestamp::operator std::string(), pq_async::timestamp_tz::operator std::string(), pq_async::time::operator std::string(), pq_async::time_tz::operator std::string(), pq_async::operator<<(), pq_async::date::pgticks(), pq_async::timestamp::pgticks(), pq_async::timestamp_tz::pgticks(), pq_async::time::pgticks(), pq_async::time_tz::pgticks(), and pq_async::tests::TEST_F().
months()
int32_t pq_async::interval::months () const inline
References parse(), and pq_async::s.
Referenced by iso_string(), and pq_async::new_parameter().
operator hhdate::sys_time< std::chrono::microseconds >()
pq_async::interval::operator hhdate::sys_time< std::chrono::microseconds > () const inline
References iso_string(), pq_async::m, and pq_async::y.
operator std::string()
pq_async::interval::operator std::string () const inline
References iso_string().
parse()
interval pq_async::interval::parse (const std::string & s) static
References interval().
Referenced by months(), pq_async::timestamp::operator hhdate::sys_time< Dur >(), pq_async::time::operator hhdate::sys_time< Dur >(), pq_async::date::operator hhdate::year_month_day(), pq_async::timestamp_tz::operator hhdate::zoned_time< Dur >(), pq_async::time_tz::operator hhdate::zoned_time< Dur >(), and pq_async::operator>>().
pgticks()
int64_t pq_async::interval::pgticks () const inline
Referenced by pq_async::timestamp::timestamp(), and pq_async::timestamp_tz::timestamp_tz().
time_of_day()
hhdate::time_of_day<std::chrono::microseconds> pq_async::interval::time_of_day () const inline
Referenced by pq_async::new_parameter().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const interval & v) friend
Referenced by pq_async::time_tz::operator hhdate::zoned_time< Dur >().
operator>>
std::istream& operator>> (std::istream & is, interval & v) friend
Referenced by pq_async::time_tz::operator hhdate::zoned_time< Dur >().
The documentation for this class was generated from the following files:
src/pg_type_date_def.h
src/pg_type_date_def.cpp