libpq-async++: pq_async::line Class Reference
pq_async::line Class Reference
#include <src/pg_type_geo_def.h>
Public Member Functions
line ()
line (double a, double b, double c)
line (const point &a, const point &b)
line (const char *str)
operator std::string () const
double a () const
double b () const
double c () const
double & a ()
double & b ()
double & c ()
void a (double val)
void b (double val)
void c (double val)
point point_from_x (double x) const
point point_from_y (double y) const
Friends
pq_async::line pgval_to_line (char *val, int len, int fmt)
pq_async::parameter * new_parameter (const pq_async::line &value)
std::ostream & operator<< (std::ostream &os, const line &v)
std::istream & operator>> (std::istream &is, line &v)
Constructor & Destructor Documentation
line() [1/4]
pq_async::line::line () inline
line() [2/4]
pq_async::line::line (double a, double b, double c) inline
line() [3/4]
pq_async::line::line (const point & a, const point & b) inline
References pq_async::line, pq_async::m, pq_async::point::x(), and pq_async::point::y().
line() [4/4]
pq_async::line::line (const char * str)
References pq_async::point::point(), pq_async::s, and pq_async::trim().
Member Function Documentation
a() [1/3]
double pq_async::line::a () const inline
Referenced by pq_async::tests::TEST_F().
a() [2/3]
double& pq_async::line::a () inline
a() [3/3]
void pq_async::line::a (double val) inline
b() [1/3]
double pq_async::line::b () const inline
Referenced by pq_async::tests::TEST_F().
b() [2/3]
double& pq_async::line::b () inline
b() [3/3]
void pq_async::line::b (double val) inline
c() [1/3]
double pq_async::line::c () const inline
Referenced by pq_async::tests::TEST_F().
c() [2/3]
double& pq_async::line::c () inline
c() [3/3]
void pq_async::line::c (double val) inline
operator std::string()
pq_async::line::operator std::string () const
References pq_async::num_to_str().
point_from_x()
point pq_async::line::point_from_x (double x) const inline
References pq_async::point::point(), pq_async::point::x(), and pq_async::point::y().
Referenced by pq_async::tests::TEST_F().
point_from_y()
point pq_async::line::point_from_y (double y) const inline
References pq_async::point::point(), pq_async::point::x(), and pq_async::point::y().
Referenced by pq_async::tests::TEST_F().
Friends And Related Function Documentation
new_parameter
pq_async::parameter* new_parameter (const pq_async::line & value) friend
operator<<
std::ostream& operator<< (std::ostream & os, const line & v) friend
operator>>
std::istream& operator>> (std::istream & is, line & v) friend
pgval_to_line
pq_async::line pgval_to_line (char * val, int len, int fmt) friend
The documentation for this class was generated from the following files:
src/pg_type_geo_def.h
src/pg_type_geo_def.cpp