libpq-async++: pq_async::time Class Reference
pq_async::time Class Reference
#include <src/pg_type_date_def.h>
Public Member Functions
time ()
time (int64_t pgticks)
template<typename Dur >
time (const hhdate::sys_time< Dur > &tod)
time (const time_tz &tz)
int64_t pgticks () const
std::string iso_string () const
operator std::string () const
template<typename Dur >
operator hhdate::sys_time< Dur > () const
time_tz as_zone (const char *zone_name) const
time_tz make_zoned (const char *zone_name) const
Static Public Member Functions
static time parse (const std::string &s)
Friends
class time_tz
std::ostream & operator<< (std::ostream &os, const time &v)
std::istream & operator>> (std::istream &is, time &v)
Constructor & Destructor Documentation
time() [1/4]
pq_async::time::time ()
time() [2/4]
pq_async::time::time (int64_t pgticks)
time() [3/4]
template<typename Dur > pq_async::time::time (const hhdate::sys_time< Dur > & tod) inline explicit
References pq_async::time.
time() [4/4]
pq_async::time::time (const time_tz & tz) explicit
Member Function Documentation
as_zone()
time_tz pq_async::time::as_zone (const char * zone_name) const
References pq_async::time_tz.
Referenced by pq_async::tests::TEST_F().
iso_string()
std::string pq_async::time::iso_string () const
Referenced by pq_async::operator<<(), and pq_async::tests::TEST_F().
make_zoned()
time_tz pq_async::time::make_zoned (const char * zone_name) const
References pq_async::time_tz.
operator hhdate::sys_time< Dur >()
template<typename Dur > pq_async::time::operator hhdate::sys_time< Dur > () const inline
References pq_async::interval::parse(), and pq_async::s.
operator std::string()
pq_async::time::operator std::string () const inline
References pq_async::interval::iso_string().
parse()
pq_async::time pq_async::time::parse (const std::string & s) static
Referenced by pq_async::operator>>().
pgticks()
int64_t pq_async::time::pgticks () const inline
References pq_async::interval::iso_string().
Referenced by pq_async::new_parameter().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const time & v) friend
operator>>
std::istream& operator>> (std::istream & is, time & v) friend
time_tz
friend class time_tz friend
The documentation for this class was generated from the following files:
src/pg_type_date_def.h
src/pg_type_date_def.cpp