libpq-async++: pq_async::data_columns_container Class Reference
pq_async::data_columns_container Class Reference
#include <src/data_columns_container.h>
Public Member Functions
data_columns_container ()
virtual ~data_columns_container ()
sp_data_column get_col (int idx)
sp_data_column get_col (const char *col_name)
int32_t get_col_index (const char *col_name) const
Constructor & Destructor Documentation
data_columns_container()
pq_async::data_columns_container::data_columns_container ()
References pq_async_log_trace.
~data_columns_container()
pq_async::data_columns_container::~data_columns_container () virtual
References pq_async_log_trace.
Member Function Documentation
get_col() [1/2]
pq_async::sp_data_column pq_async::data_columns_container::get_col (int idx)
get_col() [2/2]
pq_async::sp_data_column pq_async::data_columns_container::get_col (const char * col_name)
References get_col(), and get_col_index().
Referenced by get_col().
get_col_index()
int32_t pq_async::data_columns_container::get_col_index (const char * col_name) const inline
References pq_async::str_to_lower().
Referenced by get_col().
The documentation for this class was generated from the following files:
src/data_columns_container.h
src/data_columns_container.cpp