libpq-async++: pq_async::connection Class Reference
pq_async::connection Class Reference
#include <src/data_connection_pool.h>
Public Member Functions
const std::string & id ()
PGconn * conn ()
bool is_opened ()
bool lock ()
void release ()
sp_event_strand< int > strand ()
void touch ()
bool is_dead ()
void open_connection ()
void close_connection ()
void reserve ()
void start_work ()
void stop_work ()
bool running ()
bool can_be_stolen ()
bool in_transaction ()
void begin_transaction ()
void commit_transaction ()
void rollback_transaction ()
void set_savepoint (const char *savepoint_name)
void release_savepoint (const char *savepoint_name)
void rollback_savepoint (const char *savepoint_name)
Friends
class connection_pool
class connection_lock
class database
Member Function Documentation
begin_transaction()
void pq_async::connection::begin_transaction () inline
References open_connection().
Referenced by pq_async::database::begin().
can_be_stolen()
bool pq_async::connection::can_be_stolen () inline
close_connection()
void pq_async::connection::close_connection () inline
References touch().
Referenced by open_connection().
commit_transaction()
void pq_async::connection::commit_transaction () inline
References touch().
Referenced by pq_async::database::commit().
conn()
PGconn* pq_async::connection::conn () inline
Referenced by pq_async::connection_task::_cancel_command(), pq_async::connection_task::_consume_data(), pq_async::connection_task::_send_prepare(), pq_async::connection_task::_send_query(), pq_async::connection_task::_send_query_prepared(), pq_async::database::open(), pq_async::connection_task::run_now(), pq_async::reader_connection_task::run_now(), pq_async::connection_task::run_task(), pq_async::reader_connection_task::run_task(), and pq_async::connection_task::size().
id()
const std::string& pq_async::connection::id () inline
in_transaction()
bool pq_async::connection::in_transaction () inline
Referenced by pq_async::database::in_transaction().
is_dead()
bool pq_async::connection::is_dead ()
Referenced by touch().
is_opened()
bool pq_async::connection::is_opened () inline
References lock(), release(), and strand().
lock()
bool pq_async::connection::lock ()
References pq_async_log_trace.
Referenced by pq_async::connection_pool::get_opened_connection_count(), and is_opened().
open_connection()
void pq_async::connection::open_connection () inline
References close_connection(), and touch().
Referenced by begin_transaction(), and pq_async::database::open_connection().
release()
void pq_async::connection::release ()
References pq_async_log_trace.
Referenced by pq_async::database::close(), and is_opened().
release_savepoint()
void pq_async::connection::release_savepoint (const char * savepoint_name) inline
References touch().
Referenced by pq_async::database::release_savepoint().
reserve()
void pq_async::connection::reserve () inline
References touch().
Referenced by pq_async::database::open_connection().
rollback_savepoint()
void pq_async::connection::rollback_savepoint (const char * savepoint_name) inline
References touch().
Referenced by pq_async::database::rollback_savepoint().
rollback_transaction()
void pq_async::connection::rollback_transaction () inline
References touch().
Referenced by pq_async::database::rollback().
running()
bool pq_async::connection::running () inline
Referenced by pq_async::database::working().
set_savepoint()
void pq_async::connection::set_savepoint (const char * savepoint_name) inline
References touch().
Referenced by pq_async::database::set_savepoint().
start_work()
void pq_async::connection::start_work () inline
References touch().
stop_work()
void pq_async::connection::stop_work () inline
References touch().
strand()
sp_event_strand< int > pq_async::connection::strand ()
References pq_async::database::get_strand().
Referenced by is_opened().
touch()
void pq_async::connection::touch () inline
References is_dead().
Referenced by close_connection(), pq_async::database::commit(), commit_transaction(), open_connection(), release_savepoint(), pq_async::database::release_savepoint(), reserve(), rollback_savepoint(), pq_async::database::rollback_savepoint(), rollback_transaction(), pq_async::database::roollback(), set_savepoint(), pq_async::database::set_savepoint(), start_work(), and stop_work().
Friends And Related Function Documentation
connection_lock
friend class connection_lock friend
connection_pool
friend class connection_pool friend
database
friend class database friend
The documentation for this class was generated from the following files:
src/data_connection_pool.h
src/data_connection_pool.cpp