libpq-async++: pq_async::parameters Class Reference
pq_async::parameters Class Reference
Parameter container.
#include <src/data_parameters.h>
Public Member Functions
parameters ()
Construct a new parameters object.
template<typename... PARAMS>
parameters (const PARAMS &... args)
Construct a new parameters object.
parameters (const parameters &b)
Copy construct a new parameters object.
parameters & operator= (const parameters &b)
Copy assign a parameters object.
parameters (parameters &&b)
Move construct a new parameters object.
parameters & operator= (parameters &&b)
Move assign a parameters object.
~parameters ()
Destroy the parameters object.
int size () const
get the parameters list size
Oid * types ()
const char ** values ()
int * lengths ()
int * formats ()
void push_back (parameter *p)
template<int SIZE = 0, typename std::enable_if<(SIZE==0), int32_t >::type = 0>
void push_back ()
the push_back method that sould only be called by the variadic push_back function
template<typename... PARAMS>
void push_back (const PARAMS &...args)
template<int SIZE, typename T , typename... PARAMS, typename std::enable_if<(SIZE==0), int32_t >::type = 0>
void push_back (const T &, const PARAMS &...)
template<int SIZE, typename T , typename... PARAMS, typename std::enable_if<(SIZE > 0>
void push_back (const T &value, const PARAMS &...args)
creates and push_back parameter object in the parameters object will be called recursively until all provided parameters have been processed
template<typename T >
void replace (size_t pos, const T &value)
replace a parameter at the specified position
void remove_at (size_t pos)
remove parameter at the specified position
const parameter * get_parameter (size_t pos)
Get the parameter object from the specified position.
Detailed Description
Parameter container.
Constructor & Destructor Documentation
parameters() [1/4]
pq_async::parameters::parameters () inline
Construct a new parameters object.
parameters() [2/4]
template<typename... PARAMS> pq_async::parameters::parameters (const PARAMS &... args) inline
Construct a new parameters object.
Template Parameters
PARAMS
Parameters
args
parameters() [3/4]
pq_async::parameters::parameters (const parameters & b) inline
Copy construct a new parameters object.
Parameters
b
parameters() [4/4]
pq_async::parameters::parameters (parameters && b) inline
Move construct a new parameters object.
Parameters
b
~parameters()
pq_async::parameters::~parameters () inline
Destroy the parameters object.
Member Function Documentation
formats()
int* pq_async::parameters::formats () inline
get_parameter()
const parameter* pq_async::parameters::get_parameter (size_t pos) inline
Get the parameter object from the specified position.
Parameters
pos
Returns
const parameter*
References pq_async::parameter::get_format(), pq_async::parameter::get_length(), pq_async::parameter::get_oid(), pq_async::parameter::get_value(), and pq_async::parameter::parameter().
lengths()
int* pq_async::parameters::lengths () inline
operator=() [1/2]
parameters& pq_async::parameters::operator= (const parameters & b) inline
Copy assign a parameters object.
Parameters
b
Returns
parameters&
operator=() [2/2]
parameters& pq_async::parameters::operator= (parameters && b) inline
Move assign a parameters object.
Parameters
b
Returns
parameters&
push_back() [1/5]
void pq_async::parameters::push_back (parameter * p) inline
Parameters
p
Referenced by pq_async::data_prepared::query_reader(), and pq_async::database::query_reader().
push_back() [2/5]
template<int SIZE = 0, typename std::enable_if<(SIZE==0), int32_t >::type = 0> void pq_async::parameters::push_back () inline
the push_back method that sould only be called by the variadic push_back function
push_back() [3/5]
template<typename... PARAMS> void pq_async::parameters::push_back (const PARAMS &... args) inline
push_back() [4/5]
template<int SIZE, typename T , typename... PARAMS, typename std::enable_if<(SIZE==0), int32_t >::type = 0> void pq_async::parameters::push_back (const T & , const PARAMS & ...) inline
push_back() [5/5]
template<int SIZE, typename T , typename... PARAMS, typename std::enable_if<(SIZE > 0> void pq_async::parameters::push_back (const T & value, const PARAMS &... args) inline
creates and push_back parameter object in the parameters object will be called recursively until all provided parameters have been processed
Template Parameters
T Type of current processed value
PARAMS Type of parameters pack
Parameters
value current processed value
args parameters pack
References pq_async::new_parameter().
remove_at()
void pq_async::parameters::remove_at (size_t pos) inline
remove parameter at the specified position
Parameters
pos the position of the parameter to remove
replace()
template<typename T > void pq_async::parameters::replace (size_t pos, const T & value) inline
replace a parameter at the specified position
Template Parameters
T value Type
Parameters
pos parameter position to replace
value new parameter value
References pq_async::new_parameter().
size()
int pq_async::parameters::size () const inline
get the parameters list size
Returns
int
types()
Oid* pq_async::parameters::types () inline
values()
const char** pq_async::parameters::values () inline
The documentation for this class was generated from the following file:
src/data_parameters.h