libpq-async++: pq_async::money Class Reference
pq_async::money Class Reference
#include <src/pg_type_cash_def.h>
Public Member Functions
money ()
money (const money &b)
money (const int64_t &b)
money (const int32_t &b)
money (const float &b)
money (const double &b)
bool operator== (const money &b) const
bool operator!= (const money &b) const
bool operator< (const money &b) const
bool operator> (const money &b) const
bool operator<= (const money &b) const
bool operator>= (const money &b) const
money & operator= (const money &b)
money & operator= (const int64_t &b)
money & operator= (const int32_t &b)
money & operator= (const float &b)
money & operator= (const double &b)
money operator+ (const money &b) const
money operator- (const money &b) const
money operator* (const money &b) const
money operator/ (const money &b) const
money operator% (const money &b) const
money & operator+= (const money &b)
money & operator-= (const money &b)
money & operator*= (const money &b)
money & operator/= (const money &b)
money & operator%= (const money &b)
money & operator++ ()
money operator++ (int)
money & operator-- ()
money operator-- (int)
operator int64_t () const
operator int32_t () const
operator float () const
operator double () const
operator std::string () const
std::string to_string () const
std::string to_string (const std::locale &l) const
std::string to_string (int frac_digits) const
operator numeric () const
numeric to_numeric () const
numeric to_numeric (const std::locale &l) const
numeric to_numeric (int frac_digits) const
template<typename T >
T to_num () const
template<typename T >
T to_num (const std::locale &l) const
template<typename T >
T to_num (int frac_digits) const
Static Public Member Functions
static const std::locale & getLocale ()
static void setLocale (std::locale loc)
static money from_numeric (const numeric &b)
static money from_numeric (const numeric &b, const std::locale &l)
static money from_numeric (const numeric &b, int frac_digits)
template<typename T >
static money from_num (const T &b)
template<typename T >
static money from_num (const T &b, const std::locale &l)
template<typename T >
static money from_num (const T &b, int frac_digits)
Friends
pq_async::money pgval_to_money (char *val, int len, int fmt)
pq_async::parameter * new_parameter (const pq_async::money &value)
std::ostream & operator<< (std::ostream &s, const money &v)
Constructor & Destructor Documentation
money() [1/6]
pq_async::money::money () inline
money() [2/6]
pq_async::money::money (const money & b) inline
money() [3/6]
pq_async::money::money (const int64_t & b) inline
money() [4/6]
pq_async::money::money (const int32_t & b) inline
money() [5/6]
pq_async::money::money (const float & b) inline
money() [6/6]
pq_async::money::money (const double & b) inline
Member Function Documentation
from_num() [1/3]
template<typename T > static money pq_async::money::from_num (const T & b) inline static
References getLocale().
from_num() [2/3]
template<typename T > static money pq_async::money::from_num (const T & b, const std::locale & l) inline static
from_num() [3/3]
template<typename T > static money pq_async::money::from_num (const T & b, int frac_digits) inline static
References getLocale(), pq_async::m, and operator<<.
from_numeric() [1/3]
static money pq_async::money::from_numeric (const numeric & b) inline static
References getLocale().
Referenced by from_numeric(), and pq_async::tests::TEST_F().
from_numeric() [2/3]
static money pq_async::money::from_numeric (const numeric & b, const std::locale & l) inline static
References from_numeric().
from_numeric() [3/3]
static money pq_async::money::from_numeric (const numeric & b, int frac_digits) inline static
References pq_async::m.
getLocale()
static const std::locale& pq_async::money::getLocale () inline static
Referenced by from_num(), from_numeric(), to_num(), to_numeric(), and to_string().
operator double()
pq_async::money::operator double () const inline
operator float()
pq_async::money::operator float () const inline
operator int32_t()
pq_async::money::operator int32_t () const inline
operator int64_t()
pq_async::money::operator int64_t () const inline
operator numeric()
pq_async::money::operator numeric () const inline
References to_numeric().
operator std::string()
pq_async::money::operator std::string () const inline
References to_string().
operator!=()
bool pq_async::money::operator!= (const money & b) const inline
operator%()
money pq_async::money::operator% (const money & b) const inline
operator%=()
money& pq_async::money::operator%= (const money & b) inline
operator*()
money pq_async::money::operator* (const money & b) const inline
operator*=()
money& pq_async::money::operator*= (const money & b) inline
operator+()
money pq_async::money::operator+ (const money & b) const inline
operator++() [1/2]
money& pq_async::money::operator++ () inline
operator++() [2/2]
money pq_async::money::operator++ (int) inline
operator+=()
money& pq_async::money::operator+= (const money & b) inline
operator-()
money pq_async::money::operator- (const money & b) const inline
operator--() [1/2]
money& pq_async::money::operator-- () inline
operator--() [2/2]
money pq_async::money::operator-- (int) inline
operator-=()
money& pq_async::money::operator-= (const money & b) inline
operator/()
money pq_async::money::operator/ (const money & b) const inline
operator/=()
money& pq_async::money::operator/= (const money & b) inline
operator<()
bool pq_async::money::operator< (const money & b) const inline
operator<=()
bool pq_async::money::operator<= (const money & b) const inline
operator=() [1/5]
money& pq_async::money::operator= (const money & b) inline
operator=() [2/5]
money& pq_async::money::operator= (const int64_t & b) inline
operator=() [3/5]
money& pq_async::money::operator= (const int32_t & b) inline
operator=() [4/5]
money& pq_async::money::operator= (const float & b) inline
operator=() [5/5]
money& pq_async::money::operator= (const double & b) inline
operator==()
bool pq_async::money::operator== (const money & b) const inline
operator>()
bool pq_async::money::operator> (const money & b) const inline
operator>=()
bool pq_async::money::operator>= (const money & b) const inline
setLocale()
static void pq_async::money::setLocale (std::locale loc) inline static
Referenced by pq_async::tests::TEST_F().
to_num() [1/3]
template<typename T > T pq_async::money::to_num () const inline
References getLocale().
to_num() [2/3]
template<typename T > T pq_async::money::to_num (const std::locale & l) const inline
to_num() [3/3]
template<typename T > T pq_async::money::to_num (int frac_digits) const inline
References pq_async::m.
to_numeric() [1/3]
numeric pq_async::money::to_numeric () const inline
References getLocale().
Referenced by operator numeric(), pq_async::tests::TEST_F(), and to_numeric().
to_numeric() [2/3]
numeric pq_async::money::to_numeric (const std::locale & l) const inline
References to_numeric().
to_numeric() [3/3]
numeric pq_async::money::to_numeric (int frac_digits) const inline
References pq_async::numeric, and to_string().
to_string() [1/3]
std::string pq_async::money::to_string () const inline
References getLocale().
Referenced by operator std::string(), to_numeric(), and to_string().
to_string() [2/3]
std::string pq_async::money::to_string (const std::locale & l) const inline
References to_string().
to_string() [3/3]
std::string pq_async::money::to_string (int frac_digits) const inline
References pq_async::d, pq_async::m, and pq_async::num_to_str().
Friends And Related Function Documentation
new_parameter
pq_async::parameter* new_parameter (const pq_async::money & value) friend
operator<<
std::ostream& operator<< (std::ostream & s, const money & v) friend
Referenced by from_num().
pgval_to_money
pq_async::money pgval_to_money (char * val, int len, int fmt) friend
The documentation for this class was generated from the following files:
src/pg_type_cash_def.h
src/pg_type_cash_def.cpp