libpq-async++: pq_async::polygon Class Reference
pq_async::polygon Class Reference
#include <src/pg_type_geo_def.h>
Public Member Functions
polygon ()
polygon (const box &b, const std::vector< point > &p)
polygon (const char *str)
operator std::string () const
box bound_box () const
box & bound_box ()
void bound_box (const box &val)
std::vector< point > points () const
std::vector< point > & points ()
Friends
pq_async::polygon pgval_to_polygon (char *val, int len, int fmt)
pq_async::parameter * new_parameter (const pq_async::polygon &value)
std::ostream & operator<< (std::ostream &os, const polygon &v)
std::istream & operator>> (std::istream &is, polygon &v)
Constructor & Destructor Documentation
polygon() [1/3]
pq_async::polygon::polygon () inline
polygon() [2/3]
pq_async::polygon::polygon (const box & b, const std::vector< point > & p) inline
References pq_async::polygon.
polygon() [3/3]
pq_async::polygon::polygon (const char * str)
References pq_async::end(), pq_async::point::point(), pq_async::s, and pq_async::trim().
Member Function Documentation
bound_box() [1/3]
box pq_async::polygon::bound_box () const inline
Referenced by pq_async::tests::TEST_F().
bound_box() [2/3]
box& pq_async::polygon::bound_box () inline
bound_box() [3/3]
void pq_async::polygon::bound_box (const box & val) inline
operator std::string()
pq_async::polygon::operator std::string () const
References pq_async::s.
points() [1/2]
std::vector< point > pq_async::polygon::points () const inline
Referenced by pq_async::tests::TEST_F().
points() [2/2]
std::vector< point >& pq_async::polygon::points () inline
Friends And Related Function Documentation
new_parameter
pq_async::parameter* new_parameter (const pq_async::polygon & value) friend
operator<<
std::ostream& operator<< (std::ostream & os, const polygon & v) friend
operator>>
std::istream& operator>> (std::istream & is, polygon & v) friend
pgval_to_polygon
pq_async::polygon pgval_to_polygon (char * val, int len, int fmt) friend
The documentation for this class was generated from the following files:
src/pg_type_geo_def.h
src/pg_type_geo_def.cpp