libpq-async++: pq_async::async Class Reference
pq_async::async Class Reference final
#include <src/async.h>
Static Public Member Functions
template<typename Iterator , typename T , typename std::enable_if< std::is_invocable_r< void, T, const typename std::iterator_traits< Iterator >::value_type &, std::function< void(const cb_error &err)> >::value, int32_t >::type = -1>
static void each (event_queue *eq, Iterator first, Iterator last, T cb, async_cb end_cb)
template<typename Iterator , typename T = typename std::iterator_traits<Iterator>::value_type>
static void each (event_queue *eq, Iterator first, Iterator last, async_item_cb< T > cb, async_cb end_cb)
static void series (event_queue *eq, std::vector< async_series_cb > cbs, async_cb end_cb)
Member Function Documentation
each() [1/2]
template<typename Iterator , typename T , typename std::enable_if< std::is_invocable_r< void, T, const typename std::iterator_traits< Iterator >::value_type &, std::function< void(const cb_error &err)> >::value, int32_t >::type = -1> static void pq_async::async::each (event_queue * eq, Iterator first, Iterator last, T cb, async_cb end_cb) inline static
Referenced by pq_async::tests::TEST_F().
each() [2/2]
template<typename Iterator , typename T = typename std::iterator_traits<Iterator>::value_type> static void pq_async::async::each (event_queue * eq, Iterator first, Iterator last, async_item_cb< T > cb, async_cb end_cb) inline static
References pq_async::event_queue::push_back().
series()
static void pq_async::async::series (event_queue * eq, std::vector< async_series_cb > cbs, async_cb end_cb) inline static
example: pq_async::async::series({ [&](pq_async::async_cb scb) -> void { return scb(nullptr); }, [&](pq_async::async_cb scb) -> void { return scb(nullptr); }, }, [&](const pq_async::cb_error& err) -> void { if(err) return cb(err, cfg); cb(pq_async::cb_error::no_err, cfg); });
References pq_async::event_queue::new_strand(), pq_async_log_fatal, and pq_async::event_queue::push_back().
Referenced by pq_async::event_queue::series(), and pq_async::tests::TEST_F().
The documentation for this class was generated from the following file:
src/async.h