libpq-async++: pq_async::uuid Class Reference
pq_async::uuid Class Reference
#include <src/pg_type_uuid_def.h>
Public Member Functions
uuid ()
uuid (const uint8_t *val, size_t max_len=16)
uuid (const uuid &b)
size_t size () const
uint8_t & operator[] (size_t idx)
uint8_t operator[] (size_t idx) const
const uint8_t * data () const
operator std::string () const
bool operator== (const uuid &b) const
bool operator!= (const uuid &b) const
bool operator< (const uuid &b) const
bool operator> (const uuid &b) const
bool operator<= (const uuid &b) const
bool operator>= (const uuid &b) const
Static Public Member Functions
static uuid generate ()
Constructor & Destructor Documentation
uuid() [1/3]
pq_async::uuid::uuid () inline
uuid() [2/3]
pq_async::uuid::uuid (const uint8_t * val, size_t max_len = 16) inline
uuid() [3/3]
pq_async::uuid::uuid (const uuid & b) inline
References size().
Member Function Documentation
data()
const uint8_t* pq_async::uuid::data () const inline
generate()
uuid pq_async::uuid::generate () static
Referenced by operator>=().
operator std::string()
pq_async::uuid::operator std::string () const inline
References pq_async::hex_to_str().
operator!=()
bool pq_async::uuid::operator!= (const uuid & b) const inline
operator<()
bool pq_async::uuid::operator< (const uuid & b) const inline
References size().
operator<=()
bool pq_async::uuid::operator<= (const uuid & b) const inline
operator==()
bool pq_async::uuid::operator== (const uuid & b) const inline
References size().
operator>()
bool pq_async::uuid::operator> (const uuid & b) const inline
operator>=()
bool pq_async::uuid::operator>= (const uuid & b) const inline
References generate().
operator[]() [1/2]
uint8_t& pq_async::uuid::operator[] (size_t idx) inline
operator[]() [2/2]
uint8_t pq_async::uuid::operator[] (size_t idx) const inline
size()
size_t pq_async::uuid::size () const inline
Referenced by operator<(), operator==(), and uuid().
The documentation for this class was generated from the following files:
src/pg_type_uuid_def.h
src/pg_type_uuid_def.cpp