libpq-async++: pq_async::circle Class Reference
pq_async::circle Class Reference
#include <src/pg_type_geo_def.h>
Public Member Functions
circle ()
circle (point c, double r)
circle (const char *str)
operator std::string () const
point center () const
point & center ()
void center (const point &val)
double radius () const
double & radius ()
void radius (double val)
Friends
pq_async::circle pgval_to_circle (char *val, int len, int fmt)
pq_async::parameter * new_parameter (const pq_async::circle &value)
std::ostream & operator<< (std::ostream &os, const circle &v)
std::istream & operator>> (std::istream &is, circle &v)
Constructor & Destructor Documentation
circle() [1/3]
pq_async::circle::circle () inline
circle() [2/3]
pq_async::circle::circle (point c, double r) inline
References pq_async::circle.
circle() [3/3]
pq_async::circle::circle (const char * str)
References pq_async::point::point(), pq_async::s, and pq_async::trim().
Member Function Documentation
center() [1/3]
point pq_async::circle::center () const inline
center() [2/3]
point& pq_async::circle::center () inline
center() [3/3]
void pq_async::circle::center (const point & val) inline
operator std::string()
pq_async::circle::operator std::string () const
References pq_async::num_to_str().
radius() [1/3]
double pq_async::circle::radius () const inline
radius() [2/3]
double& pq_async::circle::radius () inline
radius() [3/3]
void pq_async::circle::radius (double val) inline
References pq_async::point::operator<<, and pq_async::point::operator>>.
Friends And Related Function Documentation
new_parameter
pq_async::parameter* new_parameter (const pq_async::circle & value) friend
operator<<
std::ostream& operator<< (std::ostream & os, const circle & v) friend
operator>>
std::istream& operator>> (std::istream & is, circle & v) friend
pgval_to_circle
pq_async::circle pgval_to_circle (char * val, int len, int fmt) friend
The documentation for this class was generated from the following files:
src/pg_type_geo_def.h
src/pg_type_geo_def.cpp