libpq-async++: pq_async::box Class Reference
pq_async::box Class Reference
#include <src/pg_type_geo_def.h>
Public Member Functions
box ()
box (const point &h, const point &l)
box (const char *str)
operator std::string () const
point high () const
point low () const
point & high ()
point & low ()
void high (const point &val)
void low (const point &val)
Friends
pq_async::box pgval_to_box (char *val, int len, int fmt)
pq_async::parameter * new_parameter (const pq_async::box &value)
std::ostream & operator<< (std::ostream &os, const box &v)
std::istream & operator>> (std::istream &is, box &v)
Constructor & Destructor Documentation
box() [1/3]
pq_async::box::box () inline
box() [2/3]
pq_async::box::box (const point & h, const point & l) inline
References pq_async::box.
box() [3/3]
pq_async::box::box (const char * str)
References pq_async::point::point(), pq_async::s, and pq_async::trim().
Member Function Documentation
high() [1/3]
point pq_async::box::high () const inline
Referenced by pq_async::tests::TEST_F().
high() [2/3]
point& pq_async::box::high () inline
high() [3/3]
void pq_async::box::high (const point & val) inline
low() [1/3]
point pq_async::box::low () const inline
low() [2/3]
point& pq_async::box::low () inline
low() [3/3]
void pq_async::box::low (const point & val) inline
operator std::string()
pq_async::box::operator std::string () const
Friends And Related Function Documentation
new_parameter
pq_async::parameter* new_parameter (const pq_async::box & value) friend
operator<<
std::ostream& operator<< (std::ostream & os, const box & v) friend
operator>>
std::istream& operator>> (std::istream & is, box & v) friend
pgval_to_box
pq_async::box pgval_to_box (char * val, int len, int fmt) friend
The documentation for this class was generated from the following files:
src/pg_type_geo_def.h
src/pg_type_geo_def.cpp