libpq-async++: pq_async::lseg Class Reference
pq_async::lseg Class Reference
#include <src/pg_type_geo_def.h>
Public Member Functions
lseg ()
lseg (const point &a, const point &b)
lseg (const char *str)
operator std::string () const
point a () const
point b () const
point & a ()
point & b ()
void a (const point &val)
void b (const point &val)
bool intersect (const lseg &b) const
Static Public Member Functions
static bool intersect (const lseg &a, const lseg &b)
static point get_intersect (const lseg &a, const lseg &b)
Friends
pq_async::lseg pgval_to_lseg (char *val, int len, int fmt)
pq_async::parameter * new_parameter (const pq_async::lseg &value)
std::ostream & operator<< (std::ostream &os, const lseg &v)
std::istream & operator>> (std::istream &is, lseg &v)
Constructor & Destructor Documentation
lseg() [1/3]
pq_async::lseg::lseg () inline
lseg() [2/3]
pq_async::lseg::lseg (const point & a, const point & b) inline
lseg() [3/3]
pq_async::lseg::lseg (const char * str)
References pq_async::point::point(), pq_async::s, and pq_async::trim().
Member Function Documentation
a() [1/3]
point pq_async::lseg::a () const inline
Referenced by get_intersect(), and intersect().
a() [2/3]
point& pq_async::lseg::a () inline
a() [3/3]
void pq_async::lseg::a (const point & val) inline
b() [1/3]
point pq_async::lseg::b () const inline
Referenced by get_intersect(), and intersect().
b() [2/3]
point& pq_async::lseg::b () inline
b() [3/3]
void pq_async::lseg::b (const point & val) inline
get_intersect()
static point pq_async::lseg::get_intersect (const lseg & a, const lseg & b) inline static
References a(), b(), and pq_async::point::point().
intersect() [1/2]
bool pq_async::lseg::intersect (const lseg & b) const inline
intersect() [2/2]
static bool pq_async::lseg::intersect (const lseg & a, const lseg & b) inline static
References a(), b(), pq_async::point::cross(), and pq_async::s.
operator std::string()
pq_async::lseg::operator std::string () const
Friends And Related Function Documentation
new_parameter
pq_async::parameter* new_parameter (const pq_async::lseg & value) friend
operator<<
std::ostream& operator<< (std::ostream & os, const lseg & v) friend
operator>>
std::istream& operator>> (std::istream & is, lseg & v) friend
pgval_to_lseg
pq_async::lseg pgval_to_lseg (char * val, int len, int fmt) friend
The documentation for this class was generated from the following files:
src/pg_type_geo_def.h
src/pg_type_geo_def.cpp