libpq-async++: pq_async::date Class Reference
pq_async::date Class Reference
#include <src/pg_type_date_def.h>
Public Member Functions
date ()
date (int32_t val)
date (const hhdate::year_month_day &d)
int32_t pgticks () const
std::string iso_string () const
operator std::string () const
operator hhdate::year_month_day () const
Static Public Member Functions
static date parse (const std::string &s)
Friends
std::ostream & operator<< (std::ostream &os, const pq_async::date &v)
std::istream & operator>> (std::istream &is, pq_async::date &v)
Constructor & Destructor Documentation
date() [1/3]
pq_async::date::date () inline
References pq_async::date.
date() [2/3]
pq_async::date::date (int32_t val)
date() [3/3]
pq_async::date::date (const hhdate::year_month_day & d) inline
Member Function Documentation
iso_string()
std::string pq_async::date::iso_string () const
Referenced by pq_async::operator<<(), and pq_async::tests::TEST_F().
operator hhdate::year_month_day()
pq_async::date::operator hhdate::year_month_day () const inline
References pq_async::interval::parse(), and pq_async::s.
operator std::string()
pq_async::date::operator std::string () const inline
References pq_async::interval::iso_string().
parse()
date pq_async::date::parse (const std::string & s) static
References pq_async::date.
Referenced by pq_async::range< T >::operator std::string(), and pq_async::operator>>().
pgticks()
int32_t pq_async::date::pgticks () const inline
References pq_async::interval::iso_string().
Referenced by pq_async::new_parameter().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const pq_async::date & v) friend
operator>>
std::istream& operator>> (std::istream & is, pq_async::date & v) friend
The documentation for this class was generated from the following files:
src/pg_type_date_def.h
src/pg_type_date_def.cpp