libpq-async++: pq_async::parameter Class Reference
pq_async::parameter Class Reference
#include <src/data_parameters.h>
Public Member Functions
parameter (Oid oid, char *value, int length, int format)
Construct a new parameter object.
parameter (char *value, int length, int format)
Construct a new parameter object.
~parameter ()
Destroy the parameter object.
Oid get_oid () const
bool has_oid () const
const char * get_value () const
int get_length () const
int get_format () const
Constructor & Destructor Documentation
parameter() [1/2]
pq_async::parameter::parameter (Oid oid, char * value, int length, int format) inline
Construct a new parameter object.
Parameters
oid PostgreSQL OID value.
value network byte order serialized value
length length of the value param
format serialized value format (0 for text, 1 for bin)
Referenced by pq_async::parameters::get_parameter().
parameter() [2/2]
pq_async::parameter::parameter (char * value, int length, int format) inline
Construct a new parameter object.
Parameters
value network byte order serialized value
length length of the value param
format serialized value format (0 for text, 1 for bin)
~parameter()
pq_async::parameter::~parameter () inline
Destroy the parameter object.
Member Function Documentation
get_format()
int pq_async::parameter::get_format () const inline
Referenced by pq_async::parameters::get_parameter().
get_length()
int pq_async::parameter::get_length () const inline
Referenced by pq_async::parameters::get_parameter(), and pq_async::new_parameter_gen().
get_oid()
Oid pq_async::parameter::get_oid () const inline
Referenced by pq_async::parameters::get_parameter().
get_value()
const char* pq_async::parameter::get_value () const inline
Referenced by pq_async::parameters::get_parameter(), and pq_async::new_parameter_gen().
has_oid()
bool pq_async::parameter::has_oid () const inline
The documentation for this class was generated from the following file:
src/data_parameters.h