libpq-async++: pq_async::tests::pq_async_test_env Class Reference
pq_async::tests::pq_async_test_env Class Reference
#include <tests/pq_async_test_env.h>
Public Member Functions
pq_async_test_env ()
void SetUp () override
void TearDown () override
Constructor & Destructor Documentation
pq_async_test_env()
pq_async::tests::pq_async_test_env::pq_async_test_env () inline
Member Function Documentation
SetUp()
void pq_async::tests::pq_async_test_env::SetUp () inline override
References pq_async::log::init(), pq_async::connection_pool::init(), pq_async_log_level, and pq_async_max_pool_size.
TearDown()
void pq_async::tests::pq_async_test_env::TearDown () inline override
References pq_async::connection_pool::destroy(), and pq_async::event_queue::destroy_default().
The documentation for this class was generated from the following file:
tests/pq_async_test_env.h