libpq-async++: pq_async Namespace Reference
pq_async Namespace Reference
Namespaces
detail
spec
tests
Data Structures
class async
class box
class cb_error
class cidr
class circle
class connection
class connection_lock
class connection_pool
class connection_pool_assign_exception
class connection_task
class data_column
class data_columns_container
class data_large_object
class data_prepared
class data_reader
class data_row
class data_table
class data_value
class database
class date
class delegate
class delegate< R(Args...), Spec, size, align >
class duration
class event_queue
class event_strand
class event_task
class event_task_base
class exception
class inet
class interval
class line
class log
class lseg
class macaddr
class macaddr8
class money
class no_grouping
class numeric
class oid
class parameter
class parameters
Parameter container.
class path
class point
class polygon
class range
class range< T, typename std::enable_if< std::is_same< int32_t, T >::value||std::is_same< int64_t, T >::value||std::is_same< numeric, T >::value||std::is_same< timestamp, T >::value||std::is_same< timestamp_tz, T >::value||std::is_same< date, T >::value >::type >
class reader_connection_task
struct select_last
struct select_last< T >
struct select_last< T, Args... >
class stopwatch
class strand
class time
class time_tz
class timestamp
class timestamp_tz
class uuid
Typedefs
typedef std::function< void()> void_cb
typedef std::function< void(const cb_error &err)> async_cb
template<typename T >
using value_cb = std::function< void(const cb_error &err, T)>
template<typename T >
using no_err_value_cb = std::function< void(T)>
template<typename T >
using async_item_cb = typename std::function< void(const T &val, async_cb)>
typedef std::function< void(async_cb)> async_series_cb
typedef std::shared_ptr< pq_async::data_column > sp_data_column
typedef std::shared_ptr< pq_async::data_columns_container > sp_data_columns_container
typedef std::shared_ptr< pq_async::parameters > sp_parameters
typedef std::shared_ptr< pq_async::data_table > sp_data_table
typedef std::shared_ptr< pq_async::data_row > sp_data_row
typedef std::shared_ptr< pq_async::data_value > sp_data_value
typedef std::shared_ptr< pq_async::data_large_object > sp_data_large_object
typedef std::shared_ptr< pq_async::data_reader > sp_data_reader
typedef std::shared_ptr< pq_async::data_prepared > sp_data_prepared
template<typename DATA_T = int>
using sp_strand = typename std::shared_ptr< pq_async::strand< DATA_T > >
typedef std::shared_ptr< pq_async::database > sp_database
typedef std::function< void(sp_data_reader reader, const pq_async::cb_error &err, sp_data_row row)> query_next_cb
typedef std::shared_ptr< pq_async::connection_lock > sp_connection_lock
typedef std::shared_ptr< pq_async::connection_task > sp_connection_task
typedef boost::multi_array< std::string, 1 > arr_string_1d
typedef boost::multi_array< char *, 1 > arr_char_1d
typedef boost::multi_array< int16_t, 1 > arr_int16_1d
typedef boost::multi_array< int32_t, 1 > arr_int32_1d
typedef boost::multi_array< int64_t, 1 > arr_int64_1d
typedef boost::multi_array< float, 1 > arr_float_1d
typedef boost::multi_array< double, 1 > arr_double_1d
typedef boost::multi_array< pq_async::numeric, 1 > arr_numeric_1d
typedef boost::multi_array< pq_async::money, 1 > arr_money_1d
typedef boost::multi_array< pq_async::time, 1 > arr_time_1d
typedef boost::multi_array< pq_async::time_tz, 1 > arr_time_tz_1d
typedef boost::multi_array< pq_async::timestamp, 1 > arr_timestamp_1d
typedef boost::multi_array< pq_async::timestamp_tz, 1 > arr_timestamp_tz_1d
typedef boost::multi_array< pq_async::date, 1 > arr_date_1d
typedef boost::multi_array< pq_async::interval, 1 > arr_interval_1d
typedef boost::multi_array< pq_async::json, 1 > arr_json_1d
typedef boost::multi_array< std::vector< int8_t >, 1 > arr_bytea_1d
typedef boost::multi_array< pq_async::uuid, 1 > arr_uuid_1d
typedef boost::multi_array< pq_async::oid, 1 > arr_oid_1d
typedef boost::multi_array< pq_async::cidr, 1 > arr_cidr_1d
typedef boost::multi_array< pq_async::inet, 1 > arr_inet_1d
typedef boost::multi_array< pq_async::macaddr, 1 > arr_macaddr_1d
typedef boost::multi_array< pq_async::macaddr8, 1 > arr_macaddr8_1d
typedef boost::multi_array< pq_async::point, 1 > arr_point_1d
typedef boost::multi_array< pq_async::line, 1 > arr_line_1d
typedef boost::multi_array< pq_async::lseg, 1 > arr_lseg_1d
typedef boost::multi_array< pq_async::box, 1 > arr_box_1d
typedef boost::multi_array< pq_async::path, 1 > arr_path_1d
typedef boost::multi_array< pq_async::polygon, 1 > arr_polygon_1d
typedef boost::multi_array< pq_async::circle, 1 > arr_circle_1d
typedef boost::multi_array< pq_async::int4range, 1 > arr_int4range_1d
typedef boost::multi_array< pq_async::int8range, 1 > arr_int8range_1d
typedef boost::multi_array< pq_async::numrange, 1 > arr_numrange_1d
typedef boost::multi_array< pq_async::tsrange, 1 > arr_tsrange_1d
typedef boost::multi_array< pq_async::tstzrange, 1 > arr_tstzrange_1d
typedef boost::multi_array< pq_async::daterange, 1 > arr_daterange_1d
typedef boost::multi_array< std::string, 2 > arr_string_2d
typedef boost::multi_array< char *, 2 > arr_char_2d
typedef boost::multi_array< int16_t, 2 > arr_int16_2d
typedef boost::multi_array< int32_t, 2 > arr_int32_2d
typedef boost::multi_array< int64_t, 2 > arr_int64_2d
typedef boost::multi_array< float, 2 > arr_float_2d
typedef boost::multi_array< double, 2 > arr_double_2d
typedef boost::multi_array< pq_async::numeric, 2 > arr_numeric_2d
typedef boost::multi_array< pq_async::money, 2 > arr_money_2d
typedef boost::multi_array< pq_async::time, 2 > arr_time_2d
typedef boost::multi_array< pq_async::time_tz, 2 > arr_time_tz_2d
typedef boost::multi_array< pq_async::timestamp, 2 > arr_timestamp_2d
typedef boost::multi_array< pq_async::timestamp_tz, 2 > arr_timestamp_tz_2d
typedef boost::multi_array< pq_async::date, 2 > arr_date_2d
typedef boost::multi_array< pq_async::interval, 2 > arr_interval_2d
typedef boost::multi_array< pq_async::json, 2 > arr_json_2d
typedef boost::multi_array< std::vector< int8_t >, 2 > arr_bytea_2d
typedef boost::multi_array< pq_async::uuid, 2 > arr_uuid_2d
typedef boost::multi_array< pq_async::oid, 2 > arr_oid_2d
typedef boost::multi_array< pq_async::cidr, 2 > arr_cidr_2d
typedef boost::multi_array< pq_async::inet, 2 > arr_inet_2d
typedef boost::multi_array< pq_async::macaddr, 2 > arr_macaddr_2d
typedef boost::multi_array< pq_async::macaddr8, 2 > arr_macaddr8_2d
typedef boost::multi_array< pq_async::point, 2 > arr_point_2d
typedef boost::multi_array< pq_async::line, 2 > arr_line_2d
typedef boost::multi_array< pq_async::lseg, 2 > arr_lseg_2d
typedef boost::multi_array< pq_async::box, 2 > arr_box_2d
typedef boost::multi_array< pq_async::path, 2 > arr_path_2d
typedef boost::multi_array< pq_async::polygon, 2 > arr_polygon_2d
typedef boost::multi_array< pq_async::circle, 2 > arr_circle_2d
typedef boost::multi_array< pq_async::int4range, 2 > arr_int4range_2d
typedef boost::multi_array< pq_async::int8range, 2 > arr_int8range_2d
typedef boost::multi_array< pq_async::numrange, 2 > arr_numrange_2d
typedef boost::multi_array< pq_async::tsrange, 2 > arr_tsrange_2d
typedef boost::multi_array< pq_async::tstzrange, 2 > arr_tstzrange_2d
typedef boost::multi_array< pq_async::daterange, 2 > arr_daterange_2d
typedef boost::multi_array< std::string, 3 > arr_string_3d
typedef boost::multi_array< char *, 3 > arr_char_3d
typedef boost::multi_array< int16_t, 3 > arr_int16_3d
typedef boost::multi_array< int32_t, 3 > arr_int32_3d
typedef boost::multi_array< int64_t, 3 > arr_int64_3d
typedef boost::multi_array< float, 3 > arr_float_3d
typedef boost::multi_array< double, 3 > arr_double_3d
typedef boost::multi_array< pq_async::numeric, 3 > arr_numeric_3d
typedef boost::multi_array< pq_async::money, 3 > arr_money_3d
typedef boost::multi_array< pq_async::time, 3 > arr_time_3d
typedef boost::multi_array< pq_async::time_tz, 3 > arr_time_tz_3d
typedef boost::multi_array< pq_async::timestamp, 3 > arr_timestamp_3d
typedef boost::multi_array< pq_async::timestamp_tz, 3 > arr_timestamp_tz_3d
typedef boost::multi_array< pq_async::date, 3 > arr_date_3d
typedef boost::multi_array< pq_async::interval, 3 > arr_interval_3d
typedef boost::multi_array< pq_async::json, 3 > arr_json_3d
typedef boost::multi_array< std::vector< int8_t >, 3 > arr_bytea_3d
typedef boost::multi_array< pq_async::uuid, 3 > arr_uuid_3d
typedef boost::multi_array< pq_async::oid, 3 > arr_oid_3d
typedef boost::multi_array< pq_async::cidr, 3 > arr_cidr_3d
typedef boost::multi_array< pq_async::inet, 3 > arr_inet_3d
typedef boost::multi_array< pq_async::macaddr, 3 > arr_macaddr_3d
typedef boost::multi_array< pq_async::macaddr8, 3 > arr_macaddr8_3d
typedef boost::multi_array< pq_async::point, 3 > arr_point_3d
typedef boost::multi_array< pq_async::line, 3 > arr_line_3d
typedef boost::multi_array< pq_async::lseg, 3 > arr_lseg_3d
typedef boost::multi_array< pq_async::box, 3 > arr_box_3d
typedef boost::multi_array< pq_async::path, 3 > arr_path_3d
typedef boost::multi_array< pq_async::polygon, 3 > arr_polygon_3d
typedef boost::multi_array< pq_async::circle, 3 > arr_circle_3d
typedef boost::multi_array< pq_async::int4range, 3 > arr_int4range_3d
typedef boost::multi_array< pq_async::int8range, 3 > arr_int8range_3d
typedef boost::multi_array< pq_async::numrange, 3 > arr_numrange_3d
typedef boost::multi_array< pq_async::tsrange, 3 > arr_tsrange_3d
typedef boost::multi_array< pq_async::tstzrange, 3 > arr_tstzrange_3d
typedef boost::multi_array< pq_async::daterange, 3 > arr_daterange_3d
typedef boost::multi_array< std::string, 4 > arr_string_4d
typedef boost::multi_array< char *, 4 > arr_char_4d
typedef boost::multi_array< int16_t, 4 > arr_int16_4d
typedef boost::multi_array< int32_t, 4 > arr_int32_4d
typedef boost::multi_array< int64_t, 4 > arr_int64_4d
typedef boost::multi_array< float, 4 > arr_float_4d
typedef boost::multi_array< double, 4 > arr_double_4d
typedef boost::multi_array< pq_async::numeric, 4 > arr_numeric_4d
typedef boost::multi_array< pq_async::money, 4 > arr_money_4d
typedef boost::multi_array< pq_async::time, 4 > arr_time_4d
typedef boost::multi_array< pq_async::time_tz, 4 > arr_time_tz_4d
typedef boost::multi_array< pq_async::timestamp, 4 > arr_timestamp_4d
typedef boost::multi_array< pq_async::timestamp_tz, 4 > arr_timestamp_tz_4d
typedef boost::multi_array< pq_async::date, 4 > arr_date_4d
typedef boost::multi_array< pq_async::interval, 4 > arr_interval_4d
typedef boost::multi_array< pq_async::json, 4 > arr_json_4d
typedef boost::multi_array< std::vector< int8_t >, 4 > arr_bytea_4d
typedef boost::multi_array< pq_async::uuid, 4 > arr_uuid_4d
typedef boost::multi_array< pq_async::oid, 4 > arr_oid_4d
typedef boost::multi_array< pq_async::cidr, 4 > arr_cidr_4d
typedef boost::multi_array< pq_async::inet, 4 > arr_inet_4d
typedef boost::multi_array< pq_async::macaddr, 4 > arr_macaddr_4d
typedef boost::multi_array< pq_async::macaddr8, 4 > arr_macaddr8_4d
typedef boost::multi_array< pq_async::point, 4 > arr_point_4d
typedef boost::multi_array< pq_async::line, 4 > arr_line_4d
typedef boost::multi_array< pq_async::lseg, 4 > arr_lseg_4d
typedef boost::multi_array< pq_async::box, 4 > arr_box_4d
typedef boost::multi_array< pq_async::path, 4 > arr_path_4d
typedef boost::multi_array< pq_async::polygon, 4 > arr_polygon_4d
typedef boost::multi_array< pq_async::circle, 4 > arr_circle_4d
typedef boost::multi_array< pq_async::int4range, 4 > arr_int4range_4d
typedef boost::multi_array< pq_async::int8range, 4 > arr_int8range_4d
typedef boost::multi_array< pq_async::numrange, 4 > arr_numrange_4d
typedef boost::multi_array< pq_async::tsrange, 4 > arr_tsrange_4d
typedef boost::multi_array< pq_async::tstzrange, 4 > arr_tstzrange_4d
typedef boost::multi_array< pq_async::daterange, 4 > arr_daterange_4d
typedef boost::multi_array< std::string, 5 > arr_string_5d
typedef boost::multi_array< char *, 5 > arr_char_5d
typedef boost::multi_array< int16_t, 5 > arr_int16_5d
typedef boost::multi_array< int32_t, 5 > arr_int32_5d
typedef boost::multi_array< int64_t, 5 > arr_int64_5d
typedef boost::multi_array< float, 5 > arr_float_5d
typedef boost::multi_array< double, 5 > arr_double_5d
typedef boost::multi_array< pq_async::numeric, 5 > arr_numeric_5d
typedef boost::multi_array< pq_async::money, 5 > arr_money_5d
typedef boost::multi_array< pq_async::time, 5 > arr_time_5d
typedef boost::multi_array< pq_async::time_tz, 5 > arr_time_tz_5d
typedef boost::multi_array< pq_async::timestamp, 5 > arr_timestamp_5d
typedef boost::multi_array< pq_async::timestamp_tz, 5 > arr_timestamp_tz_5d
typedef boost::multi_array< pq_async::date, 5 > arr_date_5d
typedef boost::multi_array< pq_async::interval, 5 > arr_interval_5d
typedef boost::multi_array< pq_async::json, 5 > arr_json_5d
typedef boost::multi_array< std::vector< int8_t >, 5 > arr_bytea_5d
typedef boost::multi_array< pq_async::uuid, 5 > arr_uuid_5d
typedef boost::multi_array< pq_async::oid, 5 > arr_oid_5d
typedef boost::multi_array< pq_async::cidr, 5 > arr_cidr_5d
typedef boost::multi_array< pq_async::inet, 5 > arr_inet_5d
typedef boost::multi_array< pq_async::macaddr, 5 > arr_macaddr_5d
typedef boost::multi_array< pq_async::macaddr8, 5 > arr_macaddr8_5d
typedef boost::multi_array< pq_async::point, 5 > arr_point_5d
typedef boost::multi_array< pq_async::line, 5 > arr_line_5d
typedef boost::multi_array< pq_async::lseg, 5 > arr_lseg_5d
typedef boost::multi_array< pq_async::box, 5 > arr_box_5d
typedef boost::multi_array< pq_async::path, 5 > arr_path_5d
typedef boost::multi_array< pq_async::polygon, 5 > arr_polygon_5d
typedef boost::multi_array< pq_async::circle, 5 > arr_circle_5d
typedef boost::multi_array< pq_async::int4range, 5 > arr_int4range_5d
typedef boost::multi_array< pq_async::int8range, 5 > arr_int8range_5d
typedef boost::multi_array< pq_async::numrange, 5 > arr_numrange_5d
typedef boost::multi_array< pq_async::tsrange, 5 > arr_tsrange_5d
typedef boost::multi_array< pq_async::tstzrange, 5 > arr_tstzrange_5d
typedef boost::multi_array< pq_async::daterange, 5 > arr_daterange_5d
typedef std::shared_ptr< pq_async::event_queue > sp_event_queue
typedef std::shared_ptr< pq_async::event_task_base > sp_event_task
template<typename T = int>
using sp_event_strand = std::shared_ptr< pq_async::event_strand< T > >
typedef std::function< void() > event_task_fn
typedef nlohmann::json json
typedef range< numeric > numrange
typedef range< int32_t > int4range
typedef range< int64_t > int8range
typedef range< timestamp > tsrange
typedef range< timestamp_tz > tstzrange
typedef range< date > daterange
Enumerations
enum data_type {
data_type::bytea = 17, data_type::bytea_arr = 1001, data_type::boolean = 16, data_type::boolean_arr = 1000,
data_type::text = 25, data_type::text_arr = 1009, data_type::varchar = data_type::text, data_type::varchar_arr = data_type::text_arr,
data_type::chr = data_type::text, data_type::chr_arr = data_type::text_arr, data_type::timestamp = 1114, data_type::timestamp_arr = 1115,
data_type::timestamp_tz = 1184, data_type::timestamp_tz_arr = 1185, data_type::date = 1082, data_type::date_arr = 1182,
data_type::time = 1083, data_type::time_arr = 1183, data_type::time_tz = 1266, data_type::time_tz_arr = 1270,
data_type::interval = 1186, data_type::interval_arr = 1187, data_type::point = 600, data_type::point_arr = 1017,
data_type::line = 628, data_type::line_arr = 629, data_type::lseg = 601, data_type::lseg_arr = 1018,
data_type::box = 603, data_type::box_arr = 1020, data_type::path = 602, data_type::path_arr = 1019,
data_type::polygon = 604, data_type::polygon_arr = 1027, data_type::circle = 718, data_type::circle_arr = 719,
data_type::json = 114, data_type::json_arr = 199, data_type::jsonb = data_type::json, data_type::jsonb_arr = data_type::json_arr,
data_type::money = 790, data_type::money_arr = 791, data_type::cidr = 650, data_type::cidr_arr = 651,
data_type::inet = 869, data_type::inet_arr = 1041, data_type::macaddr = 829, data_type::macaddr_arr = 1040,
data_type::macaddr8 = 774, data_type::macaddr8_arr = 775, data_type::smallint = 21, data_type::smallint_arr = 1005,
data_type::integer = 23, data_type::integer_arr = 1007, data_type::bigint = 20, data_type::bigint_arr = 1016,
data_type::numeric = 1700, data_type::numeric_arr = 1231, data_type::real = 700, data_type::real_arr = 1021,
data_type::float4 = 700, data_type::float4_arr = 1021, data_type::dble = 701, data_type::dble_arr = 1022,
data_type::float8 = 701, data_type::float8_arr = 1022, data_type::int4range = 3904, data_type::int4range_arr = 3905,
data_type::int8range = 3926, data_type::int8range_arr = 3927, data_type::numrange = 3906, data_type::numrange_arr = 3907,
data_type::tsrange = 3908, data_type::tsrange_arr = 3909, data_type::tstzrange = 3910, data_type::tstzrange_arr = 3911,
data_type::daterange = 3912, data_type::daterange_arr = 3913, data_type::oid = 26, data_type::oid_arr = 1028,
data_type::uuid = 2950, data_type::uuid_arr = 2951
}
enum lo_mode { lo_mode::read = INV_READ, lo_mode::write = INV_WRITE }
enum lo_whence { lo_whence::seek_start = SEEK_SET, lo_whence::seek_cur = SEEK_CUR, lo_whence::seek_end = SEEK_END }
enum event_requeue_pos { event_requeue_pos::none = 0, event_requeue_pos::back = 1, event_requeue_pos::front = 2 }
enum log_level {
log_level::ll_fatal = 0, log_level::ll_error = 1, log_level::ll_warning = 2, log_level::ll_info = 3,
log_level::ll_debug = 4, log_level::ll_trace = 5
}
enum net_family { net_family::pq_net_family_none = PF_UNSPEC, net_family::pq_net_family_inet = PF_INET, net_family::pq_net_family_inet6 = PF_INET6 }
enum range_flag {
range_flag::none = 0x00, range_flag::empty = 0x01, range_flag::lb_inc = 0x02, range_flag::ub_inc = 0x04,
range_flag::lb_inf = 0x08, range_flag::ub_inf = 0x10, range_flag::lb_null = 0x20, range_flag::ub_null = 0x40,
range_flag::contain_empty = 0x80
}
enum range_inclusion { range_inclusion::inclusive = 0, range_inclusion::exclusive = 1 }
Functions
template<typename T , typename U , typename V , typename std::enable_if< std::is_invocable_r< void, typename std::remove_pointer< V >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< V >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< V >::type, const cb_error &, U >::value &&!std::is_invocable_r< void, typename std::remove_pointer< V >::type, U >::value, int32_t >::type = -1>
void assign_value_cb (T &cb, const V &value) noexcept
template<typename T , typename V , typename std::enable_if< std::is_invocable_r< void, typename std::remove_pointer< V >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< V >::type, const cb_error &>::value, int32_t >::type = -1>
void assign_async_cb (T &cb, const V &value) noexcept
bool pgval_to_bool (char *val, int len, int fmt)
parameters code.
std::string pgval_to_string (char *val, int len, int fmt)
int16_t pgval_to_int16 (char *val, int len, int fmt)
int32_t pgval_to_int32 (char *val, int len, int fmt)
int64_t pgval_to_int64 (char *val, int len, int fmt)
pq_async::numeric pgval_to_numeric (char *val, int len, int fmt)
pq_async::money pgval_to_money (char *val, int len, int fmt)
float pgval_to_float (char *val, int len, int fmt)
double pgval_to_double (char *val, int len, int fmt)
pq_async::time pgval_to_time (char *val, int len, int fmt)
pq_async::time_tz pgval_to_time_tz (char *val, int len, int fmt)
pq_async::timestamp pgval_to_timestamp (char *val, int len, int fmt)
pq_async::timestamp_tz pgval_to_timestamp_tz (char *val, int len, int fmt)
pq_async::date pgval_to_date (char *val, int len, int fmt)
pq_async::interval pgval_to_interval (char *val, int len, int fmt)
std::vector< int8_t > pgval_to_bytea (char *val, int len, int fmt)
pq_async::uuid pgval_to_uuid (char *val, int len, int fmt)
pq_async::oid pgval_to_oid (char *val, int len, int fmt)
pq_async::cidr pgval_to_cidr (char *val, int len, int fmt)
pq_async::inet pgval_to_inet (char *val, int len, int fmt)
pq_async::macaddr pgval_to_macaddr (char *val, int len, int fmt)
pq_async::macaddr8 pgval_to_macaddr8 (char *val, int len, int fmt)
pq_async::point pgval_to_point (char *val, int len, int fmt)
pq_async::line pgval_to_line (char *val, int len, int fmt)
pq_async::lseg pgval_to_lseg (char *val, int len, int fmt)
pq_async::box pgval_to_box (char *val, int len, int fmt)
pq_async::path pgval_to_path (char *val, int len, int fmt)
pq_async::polygon pgval_to_polygon (char *val, int len, int fmt)
pq_async::circle pgval_to_circle (char *val, int len, int fmt)
template<>
pq_async::int4range pgval_to_range< pq_async::int4range > (char *val, int len, int fmt)
template<>
pq_async::int8range pgval_to_range< pq_async::int8range > (char *val, int len, int fmt)
template<>
pq_async::numrange pgval_to_range< pq_async::numrange > (char *val, int len, int fmt)
template<>
pq_async::tsrange pgval_to_range< pq_async::tsrange > (char *val, int len, int fmt)
template<>
pq_async::tstzrange pgval_to_range< pq_async::tstzrange > (char *val, int len, int fmt)
template<>
pq_async::daterange pgval_to_range< pq_async::daterange > (char *val, int len, int fmt)
pq_async::parameter * new_null_parameter ()
pq_async::parameter * new_parameter (const std::string &value)
pq_async::parameter * new_parameter (const char *value)
pq_async::parameter * new_parameter (bool value)
pq_async::parameter * new_parameter (int16_t value)
pq_async::parameter * new_parameter (int32_t value)
pq_async::parameter * new_parameter (int64_t value)
pq_async::parameter * new_parameter (float value)
pq_async::parameter * new_parameter (double value)
pq_async::parameter * new_parameter (const pq_async::time &value)
pq_async::parameter * new_parameter (const pq_async::time_tz &value)
pq_async::parameter * new_parameter (const pq_async::timestamp &value)
pq_async::parameter * new_parameter (const pq_async::timestamp_tz &value)
pq_async::parameter * new_parameter (const pq_async::date &value)
pq_async::parameter * new_parameter (const pq_async::interval &value)
pq_async::parameter * new_parameter (const pq_async::numeric &value)
pq_async::parameter * new_parameter (const pq_async::money &value)
pq_async::parameter * new_parameter (const pq_async::json &value)
pq_async::parameter * new_parameter (const std::vector< int8_t > &value)
pq_async::parameter * new_parameter (const pq_async::uuid &value)
pq_async::parameter * new_parameter (const pq_async::oid &value)
pq_async::parameter * new_parameter (const pq_async::cidr &value)
pq_async::parameter * new_parameter (const pq_async::inet &value)
pq_async::parameter * new_parameter (const pq_async::macaddr &value)
pq_async::parameter * new_parameter (const pq_async::macaddr8 &value)
pq_async::parameter * new_parameter (const pq_async::point &value)
pq_async::parameter * new_parameter (const pq_async::line &value)
pq_async::parameter * new_parameter (const pq_async::lseg &value)
pq_async::parameter * new_parameter (const pq_async::box &value)
pq_async::parameter * new_parameter (const pq_async::path &value)
pq_async::parameter * new_parameter (const pq_async::polygon &value)
pq_async::parameter * new_parameter (const pq_async::circle &value)
pq_async::parameter * new_parameter (const pq_async::int4range &value)
pq_async::parameter * new_parameter (const pq_async::int8range &value)
pq_async::parameter * new_parameter (const pq_async::numrange &value)
pq_async::parameter * new_parameter (const pq_async::tsrange &value)
pq_async::parameter * new_parameter (const pq_async::tstzrange &value)
pq_async::parameter * new_parameter (const pq_async::daterange &value)
void vec_append (std::vector< char > &vec, char *buf, int len)
void get_array_oid_and_dim (char *val, int len, int fmt, int &oid, int &dim)
pq_async::parameter * new_parameter (const boost::multi_array< std::string, 1 > &value)
template<>
boost::multi_array< std::string, 1 > val_from_pgparam< boost::multi_array< std::string, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< char *, 1 > &value)
template<>
boost::multi_array< char *, 1 > val_from_pgparam< boost::multi_array< char *, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int16_t, 1 > &value)
template<>
boost::multi_array< int16_t, 1 > val_from_pgparam< boost::multi_array< int16_t, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int32_t, 1 > &value)
template<>
boost::multi_array< int32_t, 1 > val_from_pgparam< boost::multi_array< int32_t, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int64_t, 1 > &value)
template<>
boost::multi_array< int64_t, 1 > val_from_pgparam< boost::multi_array< int64_t, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< float, 1 > &value)
template<>
boost::multi_array< float, 1 > val_from_pgparam< boost::multi_array< float, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< double, 1 > &value)
template<>
boost::multi_array< double, 1 > val_from_pgparam< boost::multi_array< double, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::numeric, 1 > &value)
template<>
boost::multi_array< pq_async::numeric, 1 > val_from_pgparam< boost::multi_array< pq_async::numeric, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::money, 1 > &value)
template<>
boost::multi_array< pq_async::money, 1 > val_from_pgparam< boost::multi_array< pq_async::money, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::time, 1 > &value)
template<>
boost::multi_array< pq_async::time, 1 > val_from_pgparam< boost::multi_array< pq_async::time, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::time_tz, 1 > &value)
template<>
boost::multi_array< pq_async::time_tz, 1 > val_from_pgparam< boost::multi_array< pq_async::time_tz, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::timestamp, 1 > &value)
template<>
boost::multi_array< pq_async::timestamp, 1 > val_from_pgparam< boost::multi_array< pq_async::timestamp, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::timestamp_tz, 1 > &value)
template<>
boost::multi_array< pq_async::timestamp_tz, 1 > val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::date, 1 > &value)
template<>
boost::multi_array< pq_async::date, 1 > val_from_pgparam< boost::multi_array< pq_async::date, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::interval, 1 > &value)
template<>
boost::multi_array< pq_async::interval, 1 > val_from_pgparam< boost::multi_array< pq_async::interval, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::json, 1 > &value)
template<>
boost::multi_array< pq_async::json, 1 > val_from_pgparam< boost::multi_array< pq_async::json, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< std::vector< int8_t >, 1 > &value)
template<>
boost::multi_array< std::vector< int8_t >, 1 > val_from_pgparam< boost::multi_array< std::vector< int8_t >, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::uuid, 1 > &value)
template<>
boost::multi_array< pq_async::uuid, 1 > val_from_pgparam< boost::multi_array< pq_async::uuid, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::oid, 1 > &value)
template<>
boost::multi_array< pq_async::oid, 1 > val_from_pgparam< boost::multi_array< pq_async::oid, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::cidr, 1 > &value)
template<>
boost::multi_array< pq_async::cidr, 1 > val_from_pgparam< boost::multi_array< pq_async::cidr, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::inet, 1 > &value)
template<>
boost::multi_array< pq_async::inet, 1 > val_from_pgparam< boost::multi_array< pq_async::inet, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::macaddr, 1 > &value)
template<>
boost::multi_array< pq_async::macaddr, 1 > val_from_pgparam< boost::multi_array< pq_async::macaddr, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::macaddr8, 1 > &value)
template<>
boost::multi_array< pq_async::macaddr8, 1 > val_from_pgparam< boost::multi_array< pq_async::macaddr8, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::point, 1 > &value)
template<>
boost::multi_array< pq_async::point, 1 > val_from_pgparam< boost::multi_array< pq_async::point, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::line, 1 > &value)
template<>
boost::multi_array< pq_async::line, 1 > val_from_pgparam< boost::multi_array< pq_async::line, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::lseg, 1 > &value)
template<>
boost::multi_array< pq_async::lseg, 1 > val_from_pgparam< boost::multi_array< pq_async::lseg, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::box, 1 > &value)
template<>
boost::multi_array< pq_async::box, 1 > val_from_pgparam< boost::multi_array< pq_async::box, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::path, 1 > &value)
template<>
boost::multi_array< pq_async::path, 1 > val_from_pgparam< boost::multi_array< pq_async::path, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::polygon, 1 > &value)
template<>
boost::multi_array< pq_async::polygon, 1 > val_from_pgparam< boost::multi_array< pq_async::polygon, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::circle, 1 > &value)
template<>
boost::multi_array< pq_async::circle, 1 > val_from_pgparam< boost::multi_array< pq_async::circle, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< std::string, 2 > &value)
template<>
boost::multi_array< std::string, 2 > val_from_pgparam< boost::multi_array< std::string, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< char *, 2 > &value)
template<>
boost::multi_array< char *, 2 > val_from_pgparam< boost::multi_array< char *, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int16_t, 2 > &value)
template<>
boost::multi_array< int16_t, 2 > val_from_pgparam< boost::multi_array< int16_t, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int32_t, 2 > &value)
template<>
boost::multi_array< int32_t, 2 > val_from_pgparam< boost::multi_array< int32_t, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int64_t, 2 > &value)
template<>
boost::multi_array< int64_t, 2 > val_from_pgparam< boost::multi_array< int64_t, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< float, 2 > &value)
template<>
boost::multi_array< float, 2 > val_from_pgparam< boost::multi_array< float, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< double, 2 > &value)
template<>
boost::multi_array< double, 2 > val_from_pgparam< boost::multi_array< double, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::numeric, 2 > &value)
template<>
boost::multi_array< pq_async::numeric, 2 > val_from_pgparam< boost::multi_array< pq_async::numeric, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::money, 2 > &value)
template<>
boost::multi_array< pq_async::money, 2 > val_from_pgparam< boost::multi_array< pq_async::money, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::time, 2 > &value)
template<>
boost::multi_array< pq_async::time, 2 > val_from_pgparam< boost::multi_array< pq_async::time, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::time_tz, 2 > &value)
template<>
boost::multi_array< pq_async::time_tz, 2 > val_from_pgparam< boost::multi_array< pq_async::time_tz, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::timestamp, 2 > &value)
template<>
boost::multi_array< pq_async::timestamp, 2 > val_from_pgparam< boost::multi_array< pq_async::timestamp, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::timestamp_tz, 2 > &value)
template<>
boost::multi_array< pq_async::timestamp_tz, 2 > val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::date, 2 > &value)
template<>
boost::multi_array< pq_async::date, 2 > val_from_pgparam< boost::multi_array< pq_async::date, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::interval, 2 > &value)
template<>
boost::multi_array< pq_async::interval, 2 > val_from_pgparam< boost::multi_array< pq_async::interval, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::json, 2 > &value)
template<>
boost::multi_array< pq_async::json, 2 > val_from_pgparam< boost::multi_array< pq_async::json, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< std::vector< int8_t >, 2 > &value)
template<>
boost::multi_array< std::vector< int8_t >, 2 > val_from_pgparam< boost::multi_array< std::vector< int8_t >, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::uuid, 2 > &value)
template<>
boost::multi_array< pq_async::uuid, 2 > val_from_pgparam< boost::multi_array< pq_async::uuid, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::oid, 2 > &value)
template<>
boost::multi_array< pq_async::oid, 2 > val_from_pgparam< boost::multi_array< pq_async::oid, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::cidr, 2 > &value)
template<>
boost::multi_array< pq_async::cidr, 2 > val_from_pgparam< boost::multi_array< pq_async::cidr, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::inet, 2 > &value)
template<>
boost::multi_array< pq_async::inet, 2 > val_from_pgparam< boost::multi_array< pq_async::inet, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::macaddr, 2 > &value)
template<>
boost::multi_array< pq_async::macaddr, 2 > val_from_pgparam< boost::multi_array< pq_async::macaddr, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::macaddr8, 2 > &value)
template<>
boost::multi_array< pq_async::macaddr8, 2 > val_from_pgparam< boost::multi_array< pq_async::macaddr8, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::point, 2 > &value)
template<>
boost::multi_array< pq_async::point, 2 > val_from_pgparam< boost::multi_array< pq_async::point, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::line, 2 > &value)
template<>
boost::multi_array< pq_async::line, 2 > val_from_pgparam< boost::multi_array< pq_async::line, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::lseg, 2 > &value)
template<>
boost::multi_array< pq_async::lseg, 2 > val_from_pgparam< boost::multi_array< pq_async::lseg, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::box, 2 > &value)
template<>
boost::multi_array< pq_async::box, 2 > val_from_pgparam< boost::multi_array< pq_async::box, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::path, 2 > &value)
template<>
boost::multi_array< pq_async::path, 2 > val_from_pgparam< boost::multi_array< pq_async::path, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::polygon, 2 > &value)
template<>
boost::multi_array< pq_async::polygon, 2 > val_from_pgparam< boost::multi_array< pq_async::polygon, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::circle, 2 > &value)
template<>
boost::multi_array< pq_async::circle, 2 > val_from_pgparam< boost::multi_array< pq_async::circle, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< std::string, 3 > &value)
template<>
boost::multi_array< std::string, 3 > val_from_pgparam< boost::multi_array< std::string, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< char *, 3 > &value)
template<>
boost::multi_array< char *, 3 > val_from_pgparam< boost::multi_array< char *, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int16_t, 3 > &value)
template<>
boost::multi_array< int16_t, 3 > val_from_pgparam< boost::multi_array< int16_t, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int32_t, 3 > &value)
template<>
boost::multi_array< int32_t, 3 > val_from_pgparam< boost::multi_array< int32_t, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int64_t, 3 > &value)
template<>
boost::multi_array< int64_t, 3 > val_from_pgparam< boost::multi_array< int64_t, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< float, 3 > &value)
template<>
boost::multi_array< float, 3 > val_from_pgparam< boost::multi_array< float, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< double, 3 > &value)
template<>
boost::multi_array< double, 3 > val_from_pgparam< boost::multi_array< double, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::numeric, 3 > &value)
template<>
boost::multi_array< pq_async::numeric, 3 > val_from_pgparam< boost::multi_array< pq_async::numeric, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::money, 3 > &value)
template<>
boost::multi_array< pq_async::money, 3 > val_from_pgparam< boost::multi_array< pq_async::money, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::time, 3 > &value)
template<>
boost::multi_array< pq_async::time, 3 > val_from_pgparam< boost::multi_array< pq_async::time, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::time_tz, 3 > &value)
template<>
boost::multi_array< pq_async::time_tz, 3 > val_from_pgparam< boost::multi_array< pq_async::time_tz, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::timestamp, 3 > &value)
template<>
boost::multi_array< pq_async::timestamp, 3 > val_from_pgparam< boost::multi_array< pq_async::timestamp, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::timestamp_tz, 3 > &value)
template<>
boost::multi_array< pq_async::timestamp_tz, 3 > val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::date, 3 > &value)
template<>
boost::multi_array< pq_async::date, 3 > val_from_pgparam< boost::multi_array< pq_async::date, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::interval, 3 > &value)
template<>
boost::multi_array< pq_async::interval, 3 > val_from_pgparam< boost::multi_array< pq_async::interval, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::json, 3 > &value)
template<>
boost::multi_array< pq_async::json, 3 > val_from_pgparam< boost::multi_array< pq_async::json, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< std::vector< int8_t >, 3 > &value)
template<>
boost::multi_array< std::vector< int8_t >, 3 > val_from_pgparam< boost::multi_array< std::vector< int8_t >, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::uuid, 3 > &value)
template<>
boost::multi_array< pq_async::uuid, 3 > val_from_pgparam< boost::multi_array< pq_async::uuid, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::oid, 3 > &value)
template<>
boost::multi_array< pq_async::oid, 3 > val_from_pgparam< boost::multi_array< pq_async::oid, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::cidr, 3 > &value)
template<>
boost::multi_array< pq_async::cidr, 3 > val_from_pgparam< boost::multi_array< pq_async::cidr, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::inet, 3 > &value)
template<>
boost::multi_array< pq_async::inet, 3 > val_from_pgparam< boost::multi_array< pq_async::inet, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::macaddr, 3 > &value)
template<>
boost::multi_array< pq_async::macaddr, 3 > val_from_pgparam< boost::multi_array< pq_async::macaddr, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::macaddr8, 3 > &value)
template<>
boost::multi_array< pq_async::macaddr8, 3 > val_from_pgparam< boost::multi_array< pq_async::macaddr8, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::point, 3 > &value)
template<>
boost::multi_array< pq_async::point, 3 > val_from_pgparam< boost::multi_array< pq_async::point, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::line, 3 > &value)
template<>
boost::multi_array< pq_async::line, 3 > val_from_pgparam< boost::multi_array< pq_async::line, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::lseg, 3 > &value)
template<>
boost::multi_array< pq_async::lseg, 3 > val_from_pgparam< boost::multi_array< pq_async::lseg, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::box, 3 > &value)
template<>
boost::multi_array< pq_async::box, 3 > val_from_pgparam< boost::multi_array< pq_async::box, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::path, 3 > &value)
template<>
boost::multi_array< pq_async::path, 3 > val_from_pgparam< boost::multi_array< pq_async::path, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::polygon, 3 > &value)
template<>
boost::multi_array< pq_async::polygon, 3 > val_from_pgparam< boost::multi_array< pq_async::polygon, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::circle, 3 > &value)
template<>
boost::multi_array< pq_async::circle, 3 > val_from_pgparam< boost::multi_array< pq_async::circle, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< std::string, 4 > &value)
template<>
boost::multi_array< std::string, 4 > val_from_pgparam< boost::multi_array< std::string, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< char *, 4 > &value)
template<>
boost::multi_array< char *, 4 > val_from_pgparam< boost::multi_array< char *, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int16_t, 4 > &value)
template<>
boost::multi_array< int16_t, 4 > val_from_pgparam< boost::multi_array< int16_t, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int32_t, 4 > &value)
template<>
boost::multi_array< int32_t, 4 > val_from_pgparam< boost::multi_array< int32_t, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int64_t, 4 > &value)
template<>
boost::multi_array< int64_t, 4 > val_from_pgparam< boost::multi_array< int64_t, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< float, 4 > &value)
template<>
boost::multi_array< float, 4 > val_from_pgparam< boost::multi_array< float, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< double, 4 > &value)
template<>
boost::multi_array< double, 4 > val_from_pgparam< boost::multi_array< double, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::numeric, 4 > &value)
template<>
boost::multi_array< pq_async::numeric, 4 > val_from_pgparam< boost::multi_array< pq_async::numeric, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::money, 4 > &value)
template<>
boost::multi_array< pq_async::money, 4 > val_from_pgparam< boost::multi_array< pq_async::money, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::time, 4 > &value)
template<>
boost::multi_array< pq_async::time, 4 > val_from_pgparam< boost::multi_array< pq_async::time, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::time_tz, 4 > &value)
template<>
boost::multi_array< pq_async::time_tz, 4 > val_from_pgparam< boost::multi_array< pq_async::time_tz, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::timestamp, 4 > &value)
template<>
boost::multi_array< pq_async::timestamp, 4 > val_from_pgparam< boost::multi_array< pq_async::timestamp, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::timestamp_tz, 4 > &value)
template<>
boost::multi_array< pq_async::timestamp_tz, 4 > val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::date, 4 > &value)
template<>
boost::multi_array< pq_async::date, 4 > val_from_pgparam< boost::multi_array< pq_async::date, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::interval, 4 > &value)
template<>
boost::multi_array< pq_async::interval, 4 > val_from_pgparam< boost::multi_array< pq_async::interval, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::json, 4 > &value)
template<>
boost::multi_array< pq_async::json, 4 > val_from_pgparam< boost::multi_array< pq_async::json, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< std::vector< int8_t >, 4 > &value)
template<>
boost::multi_array< std::vector< int8_t >, 4 > val_from_pgparam< boost::multi_array< std::vector< int8_t >, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::uuid, 4 > &value)
template<>
boost::multi_array< pq_async::uuid, 4 > val_from_pgparam< boost::multi_array< pq_async::uuid, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::oid, 4 > &value)
template<>
boost::multi_array< pq_async::oid, 4 > val_from_pgparam< boost::multi_array< pq_async::oid, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::cidr, 4 > &value)
template<>
boost::multi_array< pq_async::cidr, 4 > val_from_pgparam< boost::multi_array< pq_async::cidr, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::inet, 4 > &value)
template<>
boost::multi_array< pq_async::inet, 4 > val_from_pgparam< boost::multi_array< pq_async::inet, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::macaddr, 4 > &value)
template<>
boost::multi_array< pq_async::macaddr, 4 > val_from_pgparam< boost::multi_array< pq_async::macaddr, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::macaddr8, 4 > &value)
template<>
boost::multi_array< pq_async::macaddr8, 4 > val_from_pgparam< boost::multi_array< pq_async::macaddr8, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::point, 4 > &value)
template<>
boost::multi_array< pq_async::point, 4 > val_from_pgparam< boost::multi_array< pq_async::point, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::line, 4 > &value)
template<>
boost::multi_array< pq_async::line, 4 > val_from_pgparam< boost::multi_array< pq_async::line, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::lseg, 4 > &value)
template<>
boost::multi_array< pq_async::lseg, 4 > val_from_pgparam< boost::multi_array< pq_async::lseg, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::box, 4 > &value)
template<>
boost::multi_array< pq_async::box, 4 > val_from_pgparam< boost::multi_array< pq_async::box, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::path, 4 > &value)
template<>
boost::multi_array< pq_async::path, 4 > val_from_pgparam< boost::multi_array< pq_async::path, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::polygon, 4 > &value)
template<>
boost::multi_array< pq_async::polygon, 4 > val_from_pgparam< boost::multi_array< pq_async::polygon, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::circle, 4 > &value)
template<>
boost::multi_array< pq_async::circle, 4 > val_from_pgparam< boost::multi_array< pq_async::circle, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< std::string, 5 > &value)
template<>
boost::multi_array< std::string, 5 > val_from_pgparam< boost::multi_array< std::string, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< char *, 5 > &value)
template<>
boost::multi_array< char *, 5 > val_from_pgparam< boost::multi_array< char *, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int16_t, 5 > &value)
template<>
boost::multi_array< int16_t, 5 > val_from_pgparam< boost::multi_array< int16_t, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int32_t, 5 > &value)
template<>
boost::multi_array< int32_t, 5 > val_from_pgparam< boost::multi_array< int32_t, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< int64_t, 5 > &value)
template<>
boost::multi_array< int64_t, 5 > val_from_pgparam< boost::multi_array< int64_t, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< float, 5 > &value)
template<>
boost::multi_array< float, 5 > val_from_pgparam< boost::multi_array< float, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< double, 5 > &value)
template<>
boost::multi_array< double, 5 > val_from_pgparam< boost::multi_array< double, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::numeric, 5 > &value)
template<>
boost::multi_array< pq_async::numeric, 5 > val_from_pgparam< boost::multi_array< pq_async::numeric, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::money, 5 > &value)
template<>
boost::multi_array< pq_async::money, 5 > val_from_pgparam< boost::multi_array< pq_async::money, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::time, 5 > &value)
template<>
boost::multi_array< pq_async::time, 5 > val_from_pgparam< boost::multi_array< pq_async::time, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::time_tz, 5 > &value)
template<>
boost::multi_array< pq_async::time_tz, 5 > val_from_pgparam< boost::multi_array< pq_async::time_tz, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::timestamp, 5 > &value)
template<>
boost::multi_array< pq_async::timestamp, 5 > val_from_pgparam< boost::multi_array< pq_async::timestamp, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::timestamp_tz, 5 > &value)
template<>
boost::multi_array< pq_async::timestamp_tz, 5 > val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::date, 5 > &value)
template<>
boost::multi_array< pq_async::date, 5 > val_from_pgparam< boost::multi_array< pq_async::date, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::interval, 5 > &value)
template<>
boost::multi_array< pq_async::interval, 5 > val_from_pgparam< boost::multi_array< pq_async::interval, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::json, 5 > &value)
template<>
boost::multi_array< pq_async::json, 5 > val_from_pgparam< boost::multi_array< pq_async::json, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< std::vector< int8_t >, 5 > &value)
template<>
boost::multi_array< std::vector< int8_t >, 5 > val_from_pgparam< boost::multi_array< std::vector< int8_t >, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::uuid, 5 > &value)
template<>
boost::multi_array< pq_async::uuid, 5 > val_from_pgparam< boost::multi_array< pq_async::uuid, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::oid, 5 > &value)
template<>
boost::multi_array< pq_async::oid, 5 > val_from_pgparam< boost::multi_array< pq_async::oid, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::cidr, 5 > &value)
template<>
boost::multi_array< pq_async::cidr, 5 > val_from_pgparam< boost::multi_array< pq_async::cidr, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::inet, 5 > &value)
template<>
boost::multi_array< pq_async::inet, 5 > val_from_pgparam< boost::multi_array< pq_async::inet, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::macaddr, 5 > &value)
template<>
boost::multi_array< pq_async::macaddr, 5 > val_from_pgparam< boost::multi_array< pq_async::macaddr, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::macaddr8, 5 > &value)
template<>
boost::multi_array< pq_async::macaddr8, 5 > val_from_pgparam< boost::multi_array< pq_async::macaddr8, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::point, 5 > &value)
template<>
boost::multi_array< pq_async::point, 5 > val_from_pgparam< boost::multi_array< pq_async::point, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::line, 5 > &value)
template<>
boost::multi_array< pq_async::line, 5 > val_from_pgparam< boost::multi_array< pq_async::line, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::lseg, 5 > &value)
template<>
boost::multi_array< pq_async::lseg, 5 > val_from_pgparam< boost::multi_array< pq_async::lseg, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::box, 5 > &value)
template<>
boost::multi_array< pq_async::box, 5 > val_from_pgparam< boost::multi_array< pq_async::box, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::path, 5 > &value)
template<>
boost::multi_array< pq_async::path, 5 > val_from_pgparam< boost::multi_array< pq_async::path, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::polygon, 5 > &value)
template<>
boost::multi_array< pq_async::polygon, 5 > val_from_pgparam< boost::multi_array< pq_async::polygon, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::circle, 5 > &value)
template<>
boost::multi_array< pq_async::circle, 5 > val_from_pgparam< boost::multi_array< pq_async::circle, 5 > > (int oid, char *val, int len, int format)
template<>
bool val_from_pgparam< bool > (int oid, char *val, int len, int format)
template<>
std::string val_from_pgparam< std::string > (int oid, char *val, int len, int format)
template<>
pq_async::json val_from_pgparam< pq_async::json > (int oid, char *val, int len, int format)
template<>
pq_async::numeric val_from_pgparam< pq_async::numeric > (int oid, char *val, int len, int format)
template<>
pq_async::money val_from_pgparam< pq_async::money > (int oid, char *val, int len, int format)
template<>
int16_t val_from_pgparam< int16_t > (int oid, char *val, int len, int format)
template<>
int32_t val_from_pgparam< int32_t > (int oid, char *val, int len, int format)
template<>
int64_t val_from_pgparam< int64_t > (int oid, char *val, int len, int format)
template<>
float val_from_pgparam< float > (int oid, char *val, int len, int format)
template<>
double val_from_pgparam< double > (int oid, char *val, int len, int format)
template<>
pq_async::time val_from_pgparam< pq_async::time > (int oid, char *val, int len, int format)
template<>
pq_async::time_tz val_from_pgparam< pq_async::time_tz > (int oid, char *val, int len, int format)
template<>
pq_async::timestamp val_from_pgparam< pq_async::timestamp > (int oid, char *val, int len, int format)
template<>
pq_async::timestamp_tz val_from_pgparam< pq_async::timestamp_tz > (int oid, char *val, int len, int format)
template<>
pq_async::date val_from_pgparam< pq_async::date > (int oid, char *val, int len, int format)
template<>
pq_async::interval val_from_pgparam< pq_async::interval > (int oid, char *val, int len, int format)
template<>
std::vector< int8_t > val_from_pgparam< std::vector< int8_t > > (int oid, char *val, int len, int format)
template<>
pq_async::uuid val_from_pgparam< pq_async::uuid > (int oid, char *val, int len, int format)
template<>
pq_async::oid val_from_pgparam< pq_async::oid > (int oid, char *val, int len, int format)
template<>
pq_async::cidr val_from_pgparam< pq_async::cidr > (int oid, char *val, int len, int format)
template<>
pq_async::inet val_from_pgparam< pq_async::inet > (int oid, char *val, int len, int format)
template<>
pq_async::macaddr val_from_pgparam< pq_async::macaddr > (int oid, char *val, int len, int format)
template<>
pq_async::macaddr8 val_from_pgparam< pq_async::macaddr8 > (int oid, char *val, int len, int format)
template<>
pq_async::point val_from_pgparam< pq_async::point > (int oid, char *val, int len, int format)
template<>
pq_async::line val_from_pgparam< pq_async::line > (int oid, char *val, int len, int format)
template<>
pq_async::lseg val_from_pgparam< pq_async::lseg > (int oid, char *val, int len, int format)
template<>
pq_async::box val_from_pgparam< pq_async::box > (int oid, char *val, int len, int format)
template<>
pq_async::path val_from_pgparam< pq_async::path > (int oid, char *val, int len, int format)
template<>
pq_async::polygon val_from_pgparam< pq_async::polygon > (int oid, char *val, int len, int format)
template<>
pq_async::circle val_from_pgparam< pq_async::circle > (int oid, char *val, int len, int format)
template<>
pq_async::int4range val_from_pgparam< pq_async::int4range > (int oid, char *val, int len, int format)
template<>
pq_async::int8range val_from_pgparam< pq_async::int8range > (int oid, char *val, int len, int format)
template<>
pq_async::numrange val_from_pgparam< pq_async::numrange > (int oid, char *val, int len, int format)
template<>
pq_async::tsrange val_from_pgparam< pq_async::tsrange > (int oid, char *val, int len, int format)
template<>
pq_async::tstzrange val_from_pgparam< pq_async::tstzrange > (int oid, char *val, int len, int format)
template<>
pq_async::daterange val_from_pgparam< pq_async::daterange > (int oid, char *val, int len, int format)
template<typename T >
T val_from_pgparam (int oid, char *val, int len, int format)
template<typename T >
T pgval_to_range (char *val, int len, int fmt)
template<class T , int32_t dim_count>
boost::multi_array< T, dim_count > pgval_to_array (char *val, int len, int fmt)
template<class T , int32_t dim_count>
pq_async::parameter * new_parameter_gen (boost::multi_array< T, dim_count > value, int32_t eleOid, int32_t arrEleOid)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::int4range, 1 > &value)
template<>
boost::multi_array< pq_async::int4range, 1 > val_from_pgparam< boost::multi_array< pq_async::int4range, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::int8range, 1 > &value)
template<>
boost::multi_array< pq_async::int8range, 1 > val_from_pgparam< boost::multi_array< pq_async::int8range, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::numrange, 1 > &value)
template<>
boost::multi_array< pq_async::numrange, 1 > val_from_pgparam< boost::multi_array< pq_async::numrange, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::tsrange, 1 > &value)
template<>
boost::multi_array< pq_async::tsrange, 1 > val_from_pgparam< boost::multi_array< pq_async::tsrange, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::tstzrange, 1 > &value)
template<>
boost::multi_array< pq_async::tstzrange, 1 > val_from_pgparam< boost::multi_array< pq_async::tstzrange, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::daterange, 1 > &value)
template<>
boost::multi_array< pq_async::daterange, 1 > val_from_pgparam< boost::multi_array< pq_async::daterange, 1 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::int4range, 2 > &value)
template<>
boost::multi_array< pq_async::int4range, 2 > val_from_pgparam< boost::multi_array< pq_async::int4range, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::int8range, 2 > &value)
template<>
boost::multi_array< pq_async::int8range, 2 > val_from_pgparam< boost::multi_array< pq_async::int8range, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::numrange, 2 > &value)
template<>
boost::multi_array< pq_async::numrange, 2 > val_from_pgparam< boost::multi_array< pq_async::numrange, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::tsrange, 2 > &value)
template<>
boost::multi_array< pq_async::tsrange, 2 > val_from_pgparam< boost::multi_array< pq_async::tsrange, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::tstzrange, 2 > &value)
template<>
boost::multi_array< pq_async::tstzrange, 2 > val_from_pgparam< boost::multi_array< pq_async::tstzrange, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::daterange, 2 > &value)
template<>
boost::multi_array< pq_async::daterange, 2 > val_from_pgparam< boost::multi_array< pq_async::daterange, 2 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::int4range, 3 > &value)
template<>
boost::multi_array< pq_async::int4range, 3 > val_from_pgparam< boost::multi_array< pq_async::int4range, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::int8range, 3 > &value)
template<>
boost::multi_array< pq_async::int8range, 3 > val_from_pgparam< boost::multi_array< pq_async::int8range, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::numrange, 3 > &value)
template<>
boost::multi_array< pq_async::numrange, 3 > val_from_pgparam< boost::multi_array< pq_async::numrange, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::tsrange, 3 > &value)
template<>
boost::multi_array< pq_async::tsrange, 3 > val_from_pgparam< boost::multi_array< pq_async::tsrange, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::tstzrange, 3 > &value)
template<>
boost::multi_array< pq_async::tstzrange, 3 > val_from_pgparam< boost::multi_array< pq_async::tstzrange, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::daterange, 3 > &value)
template<>
boost::multi_array< pq_async::daterange, 3 > val_from_pgparam< boost::multi_array< pq_async::daterange, 3 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::int4range, 4 > &value)
template<>
boost::multi_array< pq_async::int4range, 4 > val_from_pgparam< boost::multi_array< pq_async::int4range, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::int8range, 4 > &value)
template<>
boost::multi_array< pq_async::int8range, 4 > val_from_pgparam< boost::multi_array< pq_async::int8range, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::numrange, 4 > &value)
template<>
boost::multi_array< pq_async::numrange, 4 > val_from_pgparam< boost::multi_array< pq_async::numrange, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::tsrange, 4 > &value)
template<>
boost::multi_array< pq_async::tsrange, 4 > val_from_pgparam< boost::multi_array< pq_async::tsrange, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::tstzrange, 4 > &value)
template<>
boost::multi_array< pq_async::tstzrange, 4 > val_from_pgparam< boost::multi_array< pq_async::tstzrange, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::daterange, 4 > &value)
template<>
boost::multi_array< pq_async::daterange, 4 > val_from_pgparam< boost::multi_array< pq_async::daterange, 4 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::int4range, 5 > &value)
template<>
boost::multi_array< pq_async::int4range, 5 > val_from_pgparam< boost::multi_array< pq_async::int4range, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::int8range, 5 > &value)
template<>
boost::multi_array< pq_async::int8range, 5 > val_from_pgparam< boost::multi_array< pq_async::int8range, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::numrange, 5 > &value)
template<>
boost::multi_array< pq_async::numrange, 5 > val_from_pgparam< boost::multi_array< pq_async::numrange, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::tsrange, 5 > &value)
template<>
boost::multi_array< pq_async::tsrange, 5 > val_from_pgparam< boost::multi_array< pq_async::tsrange, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::tstzrange, 5 > &value)
template<>
boost::multi_array< pq_async::tstzrange, 5 > val_from_pgparam< boost::multi_array< pq_async::tstzrange, 5 > > (int oid, char *val, int len, int format)
pq_async::parameter * new_parameter (const boost::multi_array< pq_async::daterange, 5 > &value)
template<>
boost::multi_array< pq_async::daterange, 5 > val_from_pgparam< boost::multi_array< pq_async::daterange, 5 > > (int oid, char *val, int len, int format)
std::atomic< uint64_t > m_next_task_id (10UL)
uint64_t get_event_task_id ()
uint64_t _event_queue_push_back (event_queue *eq, sp_event_task tp_task)
uint64_t _event_queue_push_front (event_queue *eq, sp_event_task tp_task)
template<typename Task , typename std::enable_if< std::is_invocable< Task >::value, int32_t >::type = -1>
uint64_t _event_queue_push_back (event_queue *eq, Task task)
template<typename Task , typename std::enable_if< std::is_invocable< Task >::value, int32_t >::type = -1>
uint64_t _event_queue_push_front (event_queue *eq, Task task)
std::ostream & operator<< (std::ostream &s, const cb_error &v)
std::string get_timestamp ()
std::string prepare_header (const char *color, const char *hint, const char *ts, bool is_core)
std::string prepare_footer (const char *color)
std::string exec (const char *cmd)
std::ostream & operator<< (std::ostream &os, const money &v)
std::ostream & operator<< (std::ostream &os, const interval &v)
std::istream & operator>> (std::istream &is, interval &v)
std::ostream & operator<< (std::ostream &os, const pq_async::date &v)
std::istream & operator>> (std::istream &is, pq_async::date &v)
std::ostream & operator<< (std::ostream &os, const timestamp &v)
std::istream & operator>> (std::istream &is, timestamp &v)
std::ostream & operator<< (std::ostream &os, const timestamp_tz &v)
std::istream & operator>> (std::istream &is, timestamp_tz &v)
std::ostream & operator<< (std::ostream &os, const time &v)
std::istream & operator>> (std::istream &is, time &v)
std::ostream & operator<< (std::ostream &os, const time_tz &v)
std::istream & operator>> (std::istream &is, time_tz &v)
long double text_to_duration (const std::string &val)
std::string plural (long double ms_val, long double ms_abs, long double n, const std::string &name)
std::ostream & operator<< (std::ostream &os, const pq_async::duration &d)
std::istream & operator>> (std::istream &is, duration &v)
std::ostream & operator<< (std::ostream &os, const point &v)
std::istream & operator>> (std::istream &is, point &v)
std::ostream & operator<< (std::ostream &os, const line &v)
std::istream & operator>> (std::istream &is, line &v)
std::ostream & operator<< (std::ostream &os, const lseg &v)
std::istream & operator>> (std::istream &is, lseg &v)
std::ostream & operator<< (std::ostream &os, const box &v)
std::istream & operator>> (std::istream &is, box &v)
std::ostream & operator<< (std::ostream &os, const path &v)
std::istream & operator>> (std::istream &is, path &v)
std::ostream & operator<< (std::ostream &os, const polygon &v)
std::istream & operator>> (std::istream &is, polygon &v)
std::ostream & operator<< (std::ostream &os, const circle &v)
std::istream & operator>> (std::istream &is, circle &v)
std::ostream & operator<< (std::ostream &os, const cidr &v)
std::ostream & operator<< (std::ostream &os, const inet &v)
std::ostream & operator<< (std::ostream &os, const macaddr &v)
std::ostream & operator<< (std::ostream &os, const macaddr8 &v)
std::istream & operator>> (std::istream &is, cidr &v)
std::istream & operator>> (std::istream &is, inet &v)
std::istream & operator>> (std::istream &is, macaddr &v)
std::istream & operator>> (std::istream &is, macaddr8 &v)
int pg_strncasecmp (const char *s1, const char *s2, size_t n)
void alloc_var (numeric *var, int ndigits)
void free_var (numeric *var)
void zero_var (numeric *var)
const char * set_var_from_str (const char *str, const char *cp, numeric *dest)
char * get_str_from_var (const numeric *var)
char * get_str_from_var_sci (const numeric *var, int rscale)
int32_t numericvar_to_int32 (const numeric *var)
bool numericvar_to_int64 (const numeric *var, int64_t *result)
void int64_to_numericvar (int64_t val, numeric *var)
double numericvar_to_double_no_overflow (const numeric *var)
int cmp_var (const numeric *var1, const numeric *var2)
int cmp_var_common (const NumericDigit *var1digits, int var1ndigits, int var1weight, int var1sign, const NumericDigit *var2digits, int var2ndigits, int var2weight, int var2sign)
void add_var (const numeric *var1, const numeric *var2, numeric *result)
void sub_var (const numeric *var1, const numeric *var2, numeric *result)
void mul_var (const numeric *var1, const numeric *var2, numeric *result, int rscale)
void div_var (const numeric *var1, const numeric *var2, numeric *result, int rscale, bool round)
void div_var_fast (const numeric *var1, const numeric *var2, numeric *result, int rscale, bool round)
int select_div_scale (const numeric *var1, const numeric *var2)
void mod_var (const numeric *var1, const numeric *var2, numeric *result)
void ceil_var (const numeric *var, numeric *result)
void floor_var (const numeric *var, numeric *result)
void sqrt_var (const numeric *arg, numeric *result, int rscale)
void exp_var (const numeric *arg, numeric *result, int rscale)
int estimate_ln_dweight (const numeric *var)
void ln_var (const numeric *arg, numeric *result, int rscale)
void log_var (const numeric *base, const numeric *num, numeric *result)
void power_var (const numeric *base, const numeric *exp, numeric *result)
void power_var_int (const numeric *base, int exp, numeric *result, int rscale)
int cmp_abs (const numeric *var1, const numeric *var2)
int cmp_abs_common (const NumericDigit *var1digits, int var1ndigits, int var1weight, const NumericDigit *var2digits, int var2ndigits, int var2weight)
void add_abs (const numeric *var1, const numeric *var2, numeric *result)
void sub_abs (const numeric *var1, const numeric *var2, numeric *result)
void round_var (numeric *var, int rscale)
void trunc_var (numeric *var, int rscale)
void strip_var (numeric *var)
void copy_var_to_var (const numeric &src, numeric &dest)
std::ostream & operator<< (std::ostream &os, const numeric &v)
bool pg_sub_s64_overflow (int64_t a, int64_t b, int64_t *result)
bool pg_mul_s64_overflow (int64_t a, int64_t b, int64_t *result)
range_flag operator~ (range_flag a)
bool operator! (range_flag a)
range_flag operator| (range_flag a, range_flag b)
range_flag operator & (range_flag a, range_flag b)
range_flag operator^ (range_flag a, range_flag b)
range_flag & operator|= (range_flag &a, range_flag b)
range_flag & operator &= (range_flag &a, range_flag b)
range_flag & operator^= (range_flag &a, range_flag b)
template<typename T >
std::ostream & operator<< (std::ostream &os, const range< T > &v)
template<typename T >
std::istream & operator>> (std::istream &is, range< T > &v)
template<typename T >
range< T >::iterator begin (const range< T > &v)
template<typename T >
range< T >::iterator end (const range< T > &v)
template<typename T >
range< T >::const_iterator cbegin (const range< T > &v)
template<typename T >
range< T >::const_iterator cend (const range< T > &v)
std::string hex_to_str (const uint8_t *data, int len)
void swap2 (const int16_t *inp, int16_t *outp, bool to_network)
void swap4 (const int32_t *inp, int32_t *outp, bool to_network)
void swap8 (const int64_t *inp, int64_t *outp, bool to_network)
template<typename T >
constexpr const T & get_last (const T &v) noexcept
template<typename T , typename... PARAMS>
constexpr const select_last< T, PARAMS... >::type & get_last (const T &, const PARAMS &... args) noexcept
std::string str_to_lower (const std::string &str)
bool iequals (const std::string &a, const std::string &b)
template<typename T >
std::string num_to_str (T number, bool grouping=true)
template<typename T >
T str_to_num (const std::string &text)
void ltrim (std::string &s)
void rtrim (std::string &s)
void trim (std::string &s)
std::string ltrim_copy (std::string s)
std::string rtrim_copy (std::string s)
std::string trim_copy (std::string s)
template<typename T >
std::string join (const T &lst, const std::string &separator)
Variables
char s_hostname [HOST_NAME_MAX]
pid_t s_pid
std::string s_machine_id
const long double s = 1000.0L
const long double m = s * 60.0L
const long double h = m * 60.0L
const long double d = h * 24.0L
const long double w = d * 7.0L
const long double y = d * 365.25L
constexpr char hexmap []
Typedef Documentation
arr_box_1d
typedef boost::multi_array< pq_async::box , 1 > pq_async::arr_box_1d
arr_box_2d
typedef boost::multi_array< pq_async::box , 2 > pq_async::arr_box_2d
arr_box_3d
typedef boost::multi_array< pq_async::box , 3 > pq_async::arr_box_3d
arr_box_4d
typedef boost::multi_array< pq_async::box , 4 > pq_async::arr_box_4d
arr_box_5d
typedef boost::multi_array< pq_async::box , 5 > pq_async::arr_box_5d
arr_bytea_1d
typedef boost::multi_array< std::vector<int8_t> , 1 > pq_async::arr_bytea_1d
arr_bytea_2d
typedef boost::multi_array< std::vector<int8_t> , 2 > pq_async::arr_bytea_2d
arr_bytea_3d
typedef boost::multi_array< std::vector<int8_t> , 3 > pq_async::arr_bytea_3d
arr_bytea_4d
typedef boost::multi_array< std::vector<int8_t> , 4 > pq_async::arr_bytea_4d
arr_bytea_5d
typedef boost::multi_array< std::vector<int8_t> , 5 > pq_async::arr_bytea_5d
arr_char_1d
typedef boost::multi_array< char* , 1 > pq_async::arr_char_1d
arr_char_2d
typedef boost::multi_array< char* , 2 > pq_async::arr_char_2d
arr_char_3d
typedef boost::multi_array< char* , 3 > pq_async::arr_char_3d
arr_char_4d
typedef boost::multi_array< char* , 4 > pq_async::arr_char_4d
arr_char_5d
typedef boost::multi_array< char* , 5 > pq_async::arr_char_5d
arr_cidr_1d
typedef boost::multi_array< pq_async::cidr , 1 > pq_async::arr_cidr_1d
arr_cidr_2d
typedef boost::multi_array< pq_async::cidr , 2 > pq_async::arr_cidr_2d
arr_cidr_3d
typedef boost::multi_array< pq_async::cidr , 3 > pq_async::arr_cidr_3d
arr_cidr_4d
typedef boost::multi_array< pq_async::cidr , 4 > pq_async::arr_cidr_4d
arr_cidr_5d
typedef boost::multi_array< pq_async::cidr , 5 > pq_async::arr_cidr_5d
arr_circle_1d
typedef boost::multi_array< pq_async::circle , 1 > pq_async::arr_circle_1d
arr_circle_2d
typedef boost::multi_array< pq_async::circle , 2 > pq_async::arr_circle_2d
arr_circle_3d
typedef boost::multi_array< pq_async::circle , 3 > pq_async::arr_circle_3d
arr_circle_4d
typedef boost::multi_array< pq_async::circle , 4 > pq_async::arr_circle_4d
arr_circle_5d
typedef boost::multi_array< pq_async::circle , 5 > pq_async::arr_circle_5d
arr_date_1d
typedef boost::multi_array< pq_async::date , 1 > pq_async::arr_date_1d
arr_date_2d
typedef boost::multi_array< pq_async::date , 2 > pq_async::arr_date_2d
arr_date_3d
typedef boost::multi_array< pq_async::date , 3 > pq_async::arr_date_3d
arr_date_4d
typedef boost::multi_array< pq_async::date , 4 > pq_async::arr_date_4d
arr_date_5d
typedef boost::multi_array< pq_async::date , 5 > pq_async::arr_date_5d
arr_daterange_1d
typedef boost::multi_array< pq_async::daterange , 1 > pq_async::arr_daterange_1d
arr_daterange_2d
typedef boost::multi_array< pq_async::daterange , 2 > pq_async::arr_daterange_2d
arr_daterange_3d
typedef boost::multi_array< pq_async::daterange , 3 > pq_async::arr_daterange_3d
arr_daterange_4d
typedef boost::multi_array< pq_async::daterange , 4 > pq_async::arr_daterange_4d
arr_daterange_5d
typedef boost::multi_array< pq_async::daterange , 5 > pq_async::arr_daterange_5d
arr_double_1d
typedef boost::multi_array< double , 1 > pq_async::arr_double_1d
arr_double_2d
typedef boost::multi_array< double , 2 > pq_async::arr_double_2d
arr_double_3d
typedef boost::multi_array< double , 3 > pq_async::arr_double_3d
arr_double_4d
typedef boost::multi_array< double , 4 > pq_async::arr_double_4d
arr_double_5d
typedef boost::multi_array< double , 5 > pq_async::arr_double_5d
arr_float_1d
typedef boost::multi_array< float , 1 > pq_async::arr_float_1d
arr_float_2d
typedef boost::multi_array< float , 2 > pq_async::arr_float_2d
arr_float_3d
typedef boost::multi_array< float , 3 > pq_async::arr_float_3d
arr_float_4d
typedef boost::multi_array< float , 4 > pq_async::arr_float_4d
arr_float_5d
typedef boost::multi_array< float , 5 > pq_async::arr_float_5d
arr_inet_1d
typedef boost::multi_array< pq_async::inet , 1 > pq_async::arr_inet_1d
arr_inet_2d
typedef boost::multi_array< pq_async::inet , 2 > pq_async::arr_inet_2d
arr_inet_3d
typedef boost::multi_array< pq_async::inet , 3 > pq_async::arr_inet_3d
arr_inet_4d
typedef boost::multi_array< pq_async::inet , 4 > pq_async::arr_inet_4d
arr_inet_5d
typedef boost::multi_array< pq_async::inet , 5 > pq_async::arr_inet_5d
arr_int16_1d
typedef boost::multi_array< int16_t , 1 > pq_async::arr_int16_1d
arr_int16_2d
typedef boost::multi_array< int16_t , 2 > pq_async::arr_int16_2d
arr_int16_3d
typedef boost::multi_array< int16_t , 3 > pq_async::arr_int16_3d
arr_int16_4d
typedef boost::multi_array< int16_t , 4 > pq_async::arr_int16_4d
arr_int16_5d
typedef boost::multi_array< int16_t , 5 > pq_async::arr_int16_5d
arr_int32_1d
typedef boost::multi_array< int32_t , 1 > pq_async::arr_int32_1d
arr_int32_2d
typedef boost::multi_array< int32_t , 2 > pq_async::arr_int32_2d
arr_int32_3d
typedef boost::multi_array< int32_t , 3 > pq_async::arr_int32_3d
arr_int32_4d
typedef boost::multi_array< int32_t , 4 > pq_async::arr_int32_4d
arr_int32_5d
typedef boost::multi_array< int32_t , 5 > pq_async::arr_int32_5d
arr_int4range_1d
typedef boost::multi_array< pq_async::int4range , 1 > pq_async::arr_int4range_1d
arr_int4range_2d
typedef boost::multi_array< pq_async::int4range , 2 > pq_async::arr_int4range_2d
arr_int4range_3d
typedef boost::multi_array< pq_async::int4range , 3 > pq_async::arr_int4range_3d
arr_int4range_4d
typedef boost::multi_array< pq_async::int4range , 4 > pq_async::arr_int4range_4d
arr_int4range_5d
typedef boost::multi_array< pq_async::int4range , 5 > pq_async::arr_int4range_5d
arr_int64_1d
typedef boost::multi_array< int64_t , 1 > pq_async::arr_int64_1d
arr_int64_2d
typedef boost::multi_array< int64_t , 2 > pq_async::arr_int64_2d
arr_int64_3d
typedef boost::multi_array< int64_t , 3 > pq_async::arr_int64_3d
arr_int64_4d
typedef boost::multi_array< int64_t , 4 > pq_async::arr_int64_4d
arr_int64_5d
typedef boost::multi_array< int64_t , 5 > pq_async::arr_int64_5d
arr_int8range_1d
typedef boost::multi_array< pq_async::int8range , 1 > pq_async::arr_int8range_1d
arr_int8range_2d
typedef boost::multi_array< pq_async::int8range , 2 > pq_async::arr_int8range_2d
arr_int8range_3d
typedef boost::multi_array< pq_async::int8range , 3 > pq_async::arr_int8range_3d
arr_int8range_4d
typedef boost::multi_array< pq_async::int8range , 4 > pq_async::arr_int8range_4d
arr_int8range_5d
typedef boost::multi_array< pq_async::int8range , 5 > pq_async::arr_int8range_5d
arr_interval_1d
typedef boost::multi_array< pq_async::interval , 1 > pq_async::arr_interval_1d
arr_interval_2d
typedef boost::multi_array< pq_async::interval , 2 > pq_async::arr_interval_2d
arr_interval_3d
typedef boost::multi_array< pq_async::interval , 3 > pq_async::arr_interval_3d
arr_interval_4d
typedef boost::multi_array< pq_async::interval , 4 > pq_async::arr_interval_4d
arr_interval_5d
typedef boost::multi_array< pq_async::interval , 5 > pq_async::arr_interval_5d
arr_json_1d
typedef boost::multi_array< pq_async::json , 1 > pq_async::arr_json_1d
arr_json_2d
typedef boost::multi_array< pq_async::json , 2 > pq_async::arr_json_2d
arr_json_3d
typedef boost::multi_array< pq_async::json , 3 > pq_async::arr_json_3d
arr_json_4d
typedef boost::multi_array< pq_async::json , 4 > pq_async::arr_json_4d
arr_json_5d
typedef boost::multi_array< pq_async::json , 5 > pq_async::arr_json_5d
arr_line_1d
typedef boost::multi_array< pq_async::line , 1 > pq_async::arr_line_1d
arr_line_2d
typedef boost::multi_array< pq_async::line , 2 > pq_async::arr_line_2d
arr_line_3d
typedef boost::multi_array< pq_async::line , 3 > pq_async::arr_line_3d
arr_line_4d
typedef boost::multi_array< pq_async::line , 4 > pq_async::arr_line_4d
arr_line_5d
typedef boost::multi_array< pq_async::line , 5 > pq_async::arr_line_5d
arr_lseg_1d
typedef boost::multi_array< pq_async::lseg , 1 > pq_async::arr_lseg_1d
arr_lseg_2d
typedef boost::multi_array< pq_async::lseg , 2 > pq_async::arr_lseg_2d
arr_lseg_3d
typedef boost::multi_array< pq_async::lseg , 3 > pq_async::arr_lseg_3d
arr_lseg_4d
typedef boost::multi_array< pq_async::lseg , 4 > pq_async::arr_lseg_4d
arr_lseg_5d
typedef boost::multi_array< pq_async::lseg , 5 > pq_async::arr_lseg_5d
arr_macaddr8_1d
typedef boost::multi_array< pq_async::macaddr8 , 1 > pq_async::arr_macaddr8_1d
arr_macaddr8_2d
typedef boost::multi_array< pq_async::macaddr8 , 2 > pq_async::arr_macaddr8_2d
arr_macaddr8_3d
typedef boost::multi_array< pq_async::macaddr8 , 3 > pq_async::arr_macaddr8_3d
arr_macaddr8_4d
typedef boost::multi_array< pq_async::macaddr8 , 4 > pq_async::arr_macaddr8_4d
arr_macaddr8_5d
typedef boost::multi_array< pq_async::macaddr8 , 5 > pq_async::arr_macaddr8_5d
arr_macaddr_1d
typedef boost::multi_array< pq_async::macaddr , 1 > pq_async::arr_macaddr_1d
arr_macaddr_2d
typedef boost::multi_array< pq_async::macaddr , 2 > pq_async::arr_macaddr_2d
arr_macaddr_3d
typedef boost::multi_array< pq_async::macaddr , 3 > pq_async::arr_macaddr_3d
arr_macaddr_4d
typedef boost::multi_array< pq_async::macaddr , 4 > pq_async::arr_macaddr_4d
arr_macaddr_5d
typedef boost::multi_array< pq_async::macaddr , 5 > pq_async::arr_macaddr_5d
arr_money_1d
typedef boost::multi_array< pq_async::money , 1 > pq_async::arr_money_1d
arr_money_2d
typedef boost::multi_array< pq_async::money , 2 > pq_async::arr_money_2d
arr_money_3d
typedef boost::multi_array< pq_async::money , 3 > pq_async::arr_money_3d
arr_money_4d
typedef boost::multi_array< pq_async::money , 4 > pq_async::arr_money_4d
arr_money_5d
typedef boost::multi_array< pq_async::money , 5 > pq_async::arr_money_5d
arr_numeric_1d
typedef boost::multi_array< pq_async::numeric , 1 > pq_async::arr_numeric_1d
arr_numeric_2d
typedef boost::multi_array< pq_async::numeric , 2 > pq_async::arr_numeric_2d
arr_numeric_3d
typedef boost::multi_array< pq_async::numeric , 3 > pq_async::arr_numeric_3d
arr_numeric_4d
typedef boost::multi_array< pq_async::numeric , 4 > pq_async::arr_numeric_4d
arr_numeric_5d
typedef boost::multi_array< pq_async::numeric , 5 > pq_async::arr_numeric_5d
arr_numrange_1d
typedef boost::multi_array< pq_async::numrange , 1 > pq_async::arr_numrange_1d
arr_numrange_2d
typedef boost::multi_array< pq_async::numrange , 2 > pq_async::arr_numrange_2d
arr_numrange_3d
typedef boost::multi_array< pq_async::numrange , 3 > pq_async::arr_numrange_3d
arr_numrange_4d
typedef boost::multi_array< pq_async::numrange , 4 > pq_async::arr_numrange_4d
arr_numrange_5d
typedef boost::multi_array< pq_async::numrange , 5 > pq_async::arr_numrange_5d
arr_oid_1d
typedef boost::multi_array< pq_async::oid , 1 > pq_async::arr_oid_1d
arr_oid_2d
typedef boost::multi_array< pq_async::oid , 2 > pq_async::arr_oid_2d
arr_oid_3d
typedef boost::multi_array< pq_async::oid , 3 > pq_async::arr_oid_3d
arr_oid_4d
typedef boost::multi_array< pq_async::oid , 4 > pq_async::arr_oid_4d
arr_oid_5d
typedef boost::multi_array< pq_async::oid , 5 > pq_async::arr_oid_5d
arr_path_1d
typedef boost::multi_array< pq_async::path , 1 > pq_async::arr_path_1d
arr_path_2d
typedef boost::multi_array< pq_async::path , 2 > pq_async::arr_path_2d
arr_path_3d
typedef boost::multi_array< pq_async::path , 3 > pq_async::arr_path_3d
arr_path_4d
typedef boost::multi_array< pq_async::path , 4 > pq_async::arr_path_4d
arr_path_5d
typedef boost::multi_array< pq_async::path , 5 > pq_async::arr_path_5d
arr_point_1d
typedef boost::multi_array< pq_async::point , 1 > pq_async::arr_point_1d
arr_point_2d
typedef boost::multi_array< pq_async::point , 2 > pq_async::arr_point_2d
arr_point_3d
typedef boost::multi_array< pq_async::point , 3 > pq_async::arr_point_3d
arr_point_4d
typedef boost::multi_array< pq_async::point , 4 > pq_async::arr_point_4d
arr_point_5d
typedef boost::multi_array< pq_async::point , 5 > pq_async::arr_point_5d
arr_polygon_1d
typedef boost::multi_array< pq_async::polygon , 1 > pq_async::arr_polygon_1d
arr_polygon_2d
typedef boost::multi_array< pq_async::polygon , 2 > pq_async::arr_polygon_2d
arr_polygon_3d
typedef boost::multi_array< pq_async::polygon , 3 > pq_async::arr_polygon_3d
arr_polygon_4d
typedef boost::multi_array< pq_async::polygon , 4 > pq_async::arr_polygon_4d
arr_polygon_5d
typedef boost::multi_array< pq_async::polygon , 5 > pq_async::arr_polygon_5d
arr_string_1d
typedef boost::multi_array< std::string , 1 > pq_async::arr_string_1d
arr_string_2d
typedef boost::multi_array< std::string , 2 > pq_async::arr_string_2d
arr_string_3d
typedef boost::multi_array< std::string , 3 > pq_async::arr_string_3d
arr_string_4d
typedef boost::multi_array< std::string , 4 > pq_async::arr_string_4d
arr_string_5d
typedef boost::multi_array< std::string , 5 > pq_async::arr_string_5d
arr_time_1d
typedef boost::multi_array< pq_async::time , 1 > pq_async::arr_time_1d
arr_time_2d
typedef boost::multi_array< pq_async::time , 2 > pq_async::arr_time_2d
arr_time_3d
typedef boost::multi_array< pq_async::time , 3 > pq_async::arr_time_3d
arr_time_4d
typedef boost::multi_array< pq_async::time , 4 > pq_async::arr_time_4d
arr_time_5d
typedef boost::multi_array< pq_async::time , 5 > pq_async::arr_time_5d
arr_time_tz_1d
typedef boost::multi_array< pq_async::time_tz , 1 > pq_async::arr_time_tz_1d
arr_time_tz_2d
typedef boost::multi_array< pq_async::time_tz , 2 > pq_async::arr_time_tz_2d
arr_time_tz_3d
typedef boost::multi_array< pq_async::time_tz , 3 > pq_async::arr_time_tz_3d
arr_time_tz_4d
typedef boost::multi_array< pq_async::time_tz , 4 > pq_async::arr_time_tz_4d
arr_time_tz_5d
typedef boost::multi_array< pq_async::time_tz , 5 > pq_async::arr_time_tz_5d
arr_timestamp_1d
typedef boost::multi_array< pq_async::timestamp , 1 > pq_async::arr_timestamp_1d
arr_timestamp_2d
typedef boost::multi_array< pq_async::timestamp , 2 > pq_async::arr_timestamp_2d
arr_timestamp_3d
typedef boost::multi_array< pq_async::timestamp , 3 > pq_async::arr_timestamp_3d
arr_timestamp_4d
typedef boost::multi_array< pq_async::timestamp , 4 > pq_async::arr_timestamp_4d
arr_timestamp_5d
typedef boost::multi_array< pq_async::timestamp , 5 > pq_async::arr_timestamp_5d
arr_timestamp_tz_1d
typedef boost::multi_array< pq_async::timestamp_tz , 1 > pq_async::arr_timestamp_tz_1d
arr_timestamp_tz_2d
typedef boost::multi_array< pq_async::timestamp_tz , 2 > pq_async::arr_timestamp_tz_2d
arr_timestamp_tz_3d
typedef boost::multi_array< pq_async::timestamp_tz , 3 > pq_async::arr_timestamp_tz_3d
arr_timestamp_tz_4d
typedef boost::multi_array< pq_async::timestamp_tz , 4 > pq_async::arr_timestamp_tz_4d
arr_timestamp_tz_5d
typedef boost::multi_array< pq_async::timestamp_tz , 5 > pq_async::arr_timestamp_tz_5d
arr_tsrange_1d
typedef boost::multi_array< pq_async::tsrange , 1 > pq_async::arr_tsrange_1d
arr_tsrange_2d
typedef boost::multi_array< pq_async::tsrange , 2 > pq_async::arr_tsrange_2d
arr_tsrange_3d
typedef boost::multi_array< pq_async::tsrange , 3 > pq_async::arr_tsrange_3d
arr_tsrange_4d
typedef boost::multi_array< pq_async::tsrange , 4 > pq_async::arr_tsrange_4d
arr_tsrange_5d
typedef boost::multi_array< pq_async::tsrange , 5 > pq_async::arr_tsrange_5d
arr_tstzrange_1d
typedef boost::multi_array< pq_async::tstzrange , 1 > pq_async::arr_tstzrange_1d
arr_tstzrange_2d
typedef boost::multi_array< pq_async::tstzrange , 2 > pq_async::arr_tstzrange_2d
arr_tstzrange_3d
typedef boost::multi_array< pq_async::tstzrange , 3 > pq_async::arr_tstzrange_3d
arr_tstzrange_4d
typedef boost::multi_array< pq_async::tstzrange , 4 > pq_async::arr_tstzrange_4d
arr_tstzrange_5d
typedef boost::multi_array< pq_async::tstzrange , 5 > pq_async::arr_tstzrange_5d
arr_uuid_1d
typedef boost::multi_array< pq_async::uuid , 1 > pq_async::arr_uuid_1d
arr_uuid_2d
typedef boost::multi_array< pq_async::uuid , 2 > pq_async::arr_uuid_2d
arr_uuid_3d
typedef boost::multi_array< pq_async::uuid , 3 > pq_async::arr_uuid_3d
arr_uuid_4d
typedef boost::multi_array< pq_async::uuid , 4 > pq_async::arr_uuid_4d
arr_uuid_5d
typedef boost::multi_array< pq_async::uuid , 5 > pq_async::arr_uuid_5d
async_cb
typedef std::function<void(const cb_error& err)> pq_async::async_cb
async_item_cb
template<typename T > using pq_async::async_item_cb = typedef typename std::function<void(const T& val, async_cb)>
async_series_cb
typedef std::function<void(async_cb)> pq_async::async_series_cb
daterange
typedef range<date> pq_async::daterange
event_task_fn
typedef std::function< void() > pq_async::event_task_fn
int4range
typedef range<int32_t> pq_async::int4range
int8range
typedef range<int64_t> pq_async::int8range
json
typedef nlohmann::json pq_async::json
no_err_value_cb
template<typename T > using pq_async::no_err_value_cb = typedef std::function<void(T)>
numrange
typedef range< numeric > pq_async::numrange
query_next_cb
typedef std::function< void(sp_data_reader reader, const pq_async::cb_error& err, sp_data_row row)> pq_async::query_next_cb
sp_connection_lock
typedef std::shared_ptr<pq_async::connection_lock> pq_async::sp_connection_lock
sp_connection_task
typedef std::shared_ptr< pq_async::connection_task > pq_async::sp_connection_task
sp_data_column
typedef std::shared_ptr< pq_async::data_column > pq_async::sp_data_column
sp_data_columns_container
typedef std::shared_ptr< pq_async::data_columns_container > pq_async::sp_data_columns_container
sp_data_large_object
typedef std::shared_ptr< pq_async::data_large_object > pq_async::sp_data_large_object
sp_data_prepared
typedef std::shared_ptr< pq_async::data_prepared > pq_async::sp_data_prepared
sp_data_reader
typedef std::shared_ptr< pq_async::data_reader > pq_async::sp_data_reader
sp_data_row
typedef std::shared_ptr< pq_async::data_row > pq_async::sp_data_row
sp_data_table
typedef std::shared_ptr< pq_async::data_table > pq_async::sp_data_table
sp_data_value
typedef std::shared_ptr< pq_async::data_value > pq_async::sp_data_value
sp_database
typedef std::shared_ptr< pq_async::database > pq_async::sp_database
sp_event_queue
typedef std::shared_ptr< pq_async::event_queue > pq_async::sp_event_queue
sp_event_strand
template<typename T = int> using pq_async::sp_event_strand = typedef std::shared_ptr< pq_async::event_strand<T> >
sp_event_task
typedef std::shared_ptr< pq_async::event_task_base > pq_async::sp_event_task
sp_parameters
typedef std::shared_ptr< pq_async::parameters > pq_async::sp_parameters
sp_strand
template<typename DATA_T = int> using pq_async::sp_strand = typedef typename std::shared_ptr< pq_async::strand<DATA_T> >
tsrange
typedef range<timestamp> pq_async::tsrange
tstzrange
typedef range<timestamp_tz> pq_async::tstzrange
value_cb
template<typename T > using pq_async::value_cb = typedef std::function<void(const cb_error& err, T)>
void_cb
typedef std::function<void()> pq_async::void_cb
Enumeration Type Documentation
data_type
enum pq_async::data_type strong
Enumerator
bytea
bytea_arr
boolean
boolean_arr
text
text_arr
varchar
varchar_arr
chr
chr_arr
timestamp
timestamp_arr
timestamp_tz
timestamp_tz_arr
date
date_arr
time
time_arr
time_tz
time_tz_arr
interval
interval_arr
point
point_arr
line
line_arr
lseg
lseg_arr
box
box_arr
path
path_arr
polygon
polygon_arr
circle
circle_arr
json
json_arr
jsonb
jsonb_arr
money
money_arr
cidr
cidr_arr
inet
inet_arr
macaddr
macaddr_arr
macaddr8
macaddr8_arr
smallint
smallint_arr
integer
integer_arr
bigint
bigint_arr
numeric
numeric_arr
real
real_arr
float4
float4_arr
dble
dble_arr
float8
float8_arr
int4range
int4range_arr
int8range
int8range_arr
numrange
numrange_arr
tsrange
tsrange_arr
tstzrange
tstzrange_arr
daterange
daterange_arr
oid
oid_arr
uuid
uuid_arr
event_requeue_pos
enum pq_async::event_requeue_pos strong
Enumerator
none
back
front
lo_mode
enum pq_async::lo_mode strong
Enumerator
read
write
lo_whence
enum pq_async::lo_whence strong
Enumerator
seek_start
seek_cur
seek_end
log_level
enum pq_async::log_level strong
Enumerator
ll_fatal
ll_error
ll_warning
ll_info
ll_debug
ll_trace
net_family
enum pq_async::net_family strong
Enumerator
pq_net_family_none
pq_net_family_inet
pq_net_family_inet6
range_flag
enum pq_async::range_flag strong
Enumerator
none
empty
lb_inc
ub_inc
lb_inf
ub_inf
lb_null
ub_null
contain_empty
range_inclusion
enum pq_async::range_inclusion strong
Enumerator
inclusive
exclusive
Function Documentation
_event_queue_push_back() [1/2]
uint64_t pq_async::_event_queue_push_back (event_queue * eq, sp_event_task tp_task)
Referenced by _event_queue_push_front(), and pq_async::event_queue::push_back().
_event_queue_push_back() [2/2]
template<typename Task , typename std::enable_if< std::is_invocable< Task >::value, int32_t >::type = -1> uint64_t pq_async::_event_queue_push_back (event_queue * eq, Task task)
_event_queue_push_front() [1/2]
template<typename Task , typename std::enable_if< std::is_invocable< Task >::value, int32_t >::type = -1> uint64_t pq_async::_event_queue_push_front (event_queue * eq, Task task)
References _event_queue_push_back(), and _event_queue_push_front().
_event_queue_push_front() [2/2]
uint64_t pq_async::_event_queue_push_front (event_queue * eq, sp_event_task tp_task)
Referenced by _event_queue_push_front(), and pq_async::event_queue::push_front().
add_abs()
void pq_async::add_abs (const numeric * var1, const numeric * var2, numeric * result)
References digitbuf_alloc, digitbuf_free, NBASE, and pq_async::numeric::strip_var.
add_var()
void pq_async::add_var (const numeric * var1, const numeric * var2, numeric * result)
References pq_async::numeric::add_abs, pq_async::numeric::cmp_abs, NUMERIC_NEG, NUMERIC_POS, pq_async::numeric::sub_abs, and pq_async::numeric::zero_var.
alloc_var()
void pq_async::alloc_var (numeric * var, int ndigits)
References digitbuf_alloc, and digitbuf_free.
assign_async_cb()
template<typename T , typename V , typename std::enable_if< std::is_invocable_r< void, typename std::remove_pointer< V >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< V >::type, const cb_error &>::value, int32_t >::type = -1> void pq_async::assign_async_cb (T & cb, const V & value) noexcept
References pq_async_log_fatal.
assign_value_cb()
template<typename T , typename U , typename V , typename std::enable_if< std::is_invocable_r< void, typename std::remove_pointer< V >::type >::value &&!std::is_invocable_r< void, typename std::remove_pointer< V >::type, const cb_error &>::value &&!std::is_invocable_r< void, typename std::remove_pointer< V >::type, const cb_error &, U >::value &&!std::is_invocable_r< void, typename std::remove_pointer< V >::type, U >::value, int32_t >::type = -1> void pq_async::assign_value_cb (T & cb, const V & value) noexcept
References pq_async::cb_error::c_str(), and pq_async_log_fatal.
begin()
template<typename T > range<T>::iterator pq_async::begin (const range< T > & v)
cbegin()
template<typename T > range<T>::const_iterator pq_async::cbegin (const range< T > & v)
ceil_var()
void pq_async::ceil_var (const numeric * var, numeric * result)
References pq_async::numeric::add_var, pq_async::numeric::cmp(), pq_async::numeric::free_var, NUMERIC_POS, and pq_async::numeric::trunc_var.
cend()
template<typename T > range<T>::const_iterator pq_async::cend (const range< T > & v)
cmp_abs()
int pq_async::cmp_abs (const numeric * var1, const numeric * var2)
References cmp_abs_common().
cmp_abs_common()
int pq_async::cmp_abs_common (const NumericDigit * var1digits, int var1ndigits, int var1weight, const NumericDigit * var2digits, int var2ndigits, int var2weight)
Referenced by cmp_abs(), and cmp_var_common().
cmp_var()
int pq_async::cmp_var (const numeric * var1, const numeric * var2)
References cmp_var_common().
cmp_var_common()
int pq_async::cmp_var_common (const NumericDigit * var1digits, int var1ndigits, int var1weight, int var1sign, const NumericDigit * var2digits, int var2ndigits, int var2weight, int var2sign)
References cmp_abs_common(), NUMERIC_NEG, and NUMERIC_POS.
Referenced by pq_async::numeric::cmp(), and cmp_var().
copy_var_to_var()
void pq_async::copy_var_to_var (const numeric & src, numeric & dest)
References digitbuf_alloc, and digitbuf_free.
div_var()
void pq_async::div_var (const numeric * var1, const numeric * var2, numeric * result, int rscale, bool round)
References pq_async::numeric::alloc_var, d, DEC_DIGITS, HALF_NBASE, NBASE, NUMERIC_NEG, NUMERIC_POS, pq_async::numeric::round_var, pq_async::numeric::strip_var, pq_async::numeric::trunc_var, and pq_async::numeric::zero_var.
div_var_fast()
void pq_async::div_var_fast (const numeric * var1, const numeric * var2, numeric * result, int rscale, bool round)
References pq_async::numeric::alloc_var, DEC_DIGITS, DIV_GUARD_DIGITS, INT_MAX, NBASE, NUMERIC_NEG, NUMERIC_POS, pq_async::numeric::round_var, pq_async::numeric::strip_var, pq_async::numeric::trunc_var, and pq_async::numeric::zero_var.
end()
template<typename T > range<T>::iterator pq_async::end (const range< T > & v)
Referenced by pq_async::path::path(), and pq_async::polygon::polygon().
estimate_ln_dweight()
int pq_async::estimate_ln_dweight (const numeric * var)
References pq_async::numeric::cmp_var, DEC_DIGITS, pq_async::numeric::free_var, pq_async::numeric::ln_var, NBASE, and pq_async::numeric::sub_var.
exec()
std::string pq_async::exec (const char * cmd)
References get_timestamp(), line, ll_debug, ll_error, ll_fatal, ll_info, ll_trace, ll_warning, PQ_ASYNC_MAX_LOG_LENGTH, prepare_footer(), and prepare_header().
exp_var()
void pq_async::exp_var (const numeric * arg, numeric * result, int rscale)
References pq_async::numeric::add_var, DEC_DIGITS, pq_async::numeric::div_var_fast, pq_async::numeric::free_var, pq_async::numeric::from(), pq_async::numeric::mul_var, NUMERIC_MAX_RESULT_SCALE, NUMERIC_MIN_DISPLAY_SCALE, numericvar_to_double_no_overflow(), and pq_async::numeric::round_var.
floor_var()
void pq_async::floor_var (const numeric * var, numeric * result)
References pq_async::numeric::cmp(), pq_async::numeric::free_var, NUMERIC_NEG, pq_async::numeric::sub_var, and pq_async::numeric::trunc_var.
free_var()
void pq_async::free_var (numeric * var)
References digitbuf_free, and NUMERIC_NAN.
get_array_oid_and_dim()
void pq_async::get_array_oid_and_dim (char * val, int len, int fmt, int & oid, int & dim)
References swap4().
Referenced by pq_async::data_value::get_array_dim(), pq_async::data_value::get_array_ele_oid(), and pgval_to_range().
get_event_task_id()
uint64_t pq_async::get_event_task_id ()
References m_next_task_id().
get_last() [1/2]
template<typename T > constexpr const T& pq_async::get_last (const T & v) noexcept
Referenced by get_last(), pq_async::database::prepare(), pq_async::data_prepared::query_reader(), and pq_async::database::query_reader().
get_last() [2/2]
template<typename T , typename... PARAMS> constexpr const select_last<T, PARAMS...>::type& pq_async::get_last (const T & , const PARAMS &... args) noexcept
References get_last().
get_str_from_var()
char * pq_async::get_str_from_var (const numeric * var)
References d, DEC_DIGITS, NBASE, and NUMERIC_NEG.
get_str_from_var_sci()
char * pq_async::get_str_from_var_sci (const numeric * var, int rscale)
References DEC_DIGITS, pq_async::numeric::div_var, pq_async::numeric::get_str_from_var, and pq_async::numeric::power_var_int.
get_timestamp()
std::string pq_async::get_timestamp ()
References time.
Referenced by exec().
hex_to_str()
std::string pq_async::hex_to_str (const uint8_t * data, int len)
References s.
Referenced by join(), new_parameter(), and pq_async::uuid::operator std::string().
iequals()
bool pq_async::iequals (const std::string & a, const std::string & b) inline
Referenced by pgval_to_bool().
int64_to_numericvar()
void pq_async::int64_to_numericvar (int64_t val, numeric * var)
References pq_async::numeric::alloc_var, DEC_DIGITS, NBASE, NUMERIC_NEG, and NUMERIC_POS.
join()
template<typename T > std::string pq_async::join (const T & lst, const std::string & separator) inline
References hex_to_str(), swap2(), swap4(), and swap8().
Referenced by pq_async::database::exec_queries().
ln_var()
void pq_async::ln_var (const numeric * arg, numeric * result, int rscale)
References pq_async::numeric::add_var, pq_async::numeric::cmp(), pq_async::numeric::cmp_var, DEC_DIGITS, pq_async::numeric::div_var_fast, pq_async::numeric::free_var, pq_async::numeric::mul_var, NUMERIC_MIN_DISPLAY_SCALE, pq_async::numeric::sqrt_var, and pq_async::numeric::sub_var.
log_var()
void pq_async::log_var (const numeric * base, const numeric * num, numeric * result)
References pq_async::numeric::div_var_fast, pq_async::numeric::estimate_ln_dweight, pq_async::numeric::free_var, pq_async::numeric::ln_var, NUMERIC_MAX_DISPLAY_SCALE, NUMERIC_MIN_DISPLAY_SCALE, and NUMERIC_MIN_SIG_DIGITS.
ltrim()
void pq_async::ltrim (std::string & s) inline
Referenced by ltrim_copy(), and trim().
ltrim_copy()
std::string pq_async::ltrim_copy (std::string s) inline
References ltrim(), and s.
m_next_task_id()
std::atomic<uint64_t> pq_async::m_next_task_id (10UL)
Referenced by get_event_task_id().
mod_var()
void pq_async::mod_var (const numeric * var1, const numeric * var2, numeric * result)
References pq_async::numeric::div_var, pq_async::numeric::free_var, pq_async::numeric::mul_var, and pq_async::numeric::sub_var.
mul_var()
void pq_async::mul_var (const numeric * var1, const numeric * var2, numeric * result, int rscale)
References pq_async::numeric::alloc_var, DEC_DIGITS, INT_MAX, MUL_GUARD_DIGITS, NBASE, NUMERIC_NEG, NUMERIC_POS, pq_async::numeric::round_var, pq_async::numeric::strip_var, and pq_async::numeric::zero_var.
new_null_parameter()
pq_async::parameter * pq_async::new_null_parameter ()
Referenced by pgval_to_array().
new_parameter() [1/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::int8range, 1 > & value)
new_parameter() [2/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::numrange, 1 > & value)
new_parameter() [3/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::tsrange, 1 > & value)
new_parameter() [4/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::tstzrange, 1 > & value)
new_parameter() [5/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::daterange, 1 > & value)
new_parameter() [6/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::int4range, 1 > & value)
new_parameter() [7/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::int4range, 2 > & value)
new_parameter() [8/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::int8range, 2 > & value)
new_parameter() [9/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::numrange, 2 > & value)
new_parameter() [10/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::tsrange, 2 > & value)
new_parameter() [11/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::tstzrange, 2 > & value)
new_parameter() [12/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::daterange, 2 > & value)
new_parameter() [13/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::int4range, 3 > & value)
new_parameter() [14/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::int8range, 3 > & value)
new_parameter() [15/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::numrange, 3 > & value)
new_parameter() [16/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::tsrange, 3 > & value)
new_parameter() [17/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::daterange, 3 > & value)
new_parameter() [18/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::tstzrange, 3 > & value)
new_parameter() [19/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::int4range, 4 > & value)
new_parameter() [20/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::int8range, 4 > & value)
new_parameter() [21/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::numrange, 4 > & value)
new_parameter() [22/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::tsrange, 4 > & value)
new_parameter() [23/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::tstzrange, 4 > & value)
new_parameter() [24/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::daterange, 4 > & value)
new_parameter() [25/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::int4range, 5 > & value)
new_parameter() [26/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::int8range, 5 > & value)
new_parameter() [27/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::numrange, 5 > & value)
new_parameter() [28/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::tstzrange, 5 > & value)
new_parameter() [29/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::tsrange, 5 > & value)
new_parameter() [30/217]
pq_async::parameter* pq_async::new_parameter (const boost::multi_array< pq_async::daterange, 5 > & value)
new_parameter() [31/217]
pq_async::parameter * pq_async::new_parameter (const std::string & value)
References TEXTOID.
Referenced by new_parameter(), new_parameter_gen(), pgval_to_array(), pq_async::parameters::push_back(), and pq_async::parameters::replace().
new_parameter() [32/217]
pq_async::parameter * pq_async::new_parameter (const char * value)
References new_parameter().
new_parameter() [33/217]
pq_async::parameter * pq_async::new_parameter (bool value)
References BOOLOID.
new_parameter() [34/217]
pq_async::parameter * pq_async::new_parameter (int16_t value)
References INT2OID, and swap2().
new_parameter() [35/217]
pq_async::parameter * pq_async::new_parameter (int32_t value)
References INT4OID, and swap4().
new_parameter() [36/217]
pq_async::parameter * pq_async::new_parameter (int64_t value)
References INT8OID, and swap8().
new_parameter() [37/217]
pq_async::parameter * pq_async::new_parameter (float value)
References FLOAT4OID, and swap4().
new_parameter() [38/217]
pq_async::parameter * pq_async::new_parameter (double value)
References FLOAT8OID, and swap8().
new_parameter() [39/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::time & value)
References pq_async::time::pgticks(), swap8(), and TIMEOID.
new_parameter() [40/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::time_tz & value)
References pq_async::time_tz::pgticks(), POSTGRES_EPOCH_USEC, swap8(), and TIMETZOID.
new_parameter() [41/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::timestamp & value)
References pq_async::timestamp::pgticks(), POSTGRES_EPOCH_USEC, swap8(), and TIMESTAMPOID.
new_parameter() [42/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::timestamp_tz & value)
References pq_async::timestamp_tz::pgticks(), POSTGRES_EPOCH_USEC, swap8(), and TIMESTAMPTZOID.
new_parameter() [43/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::date & value)
References DATEOID, pq_async::date::pgticks(), POSTGRES_EPOCH_JDATE, and swap4().
new_parameter() [44/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::interval & value)
References pq_async::interval::days(), INTERVALOID, pq_async::interval::months(), swap4(), swap8(), and pq_async::interval::time_of_day().
new_parameter() [45/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::numeric & value)
References NUMERICOID.
new_parameter() [46/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::money & value)
References CASHOID, and swap8().
new_parameter() [47/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::json & value)
References JSONBOID.
new_parameter() [48/217]
pq_async::parameter * pq_async::new_parameter (const std::vector< int8_t > & value)
References BYTEAOID, and hex_to_str().
new_parameter() [49/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::uuid & value)
References UUIDOID.
new_parameter() [50/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::oid & value)
References OIDOID, and swap4().
new_parameter() [51/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::cidr & value)
References CIDROID, PGSQL_AF_INET, PGSQL_AF_INET6, and pq_net_family_inet.
new_parameter() [52/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::inet & value)
References INETOID, PGSQL_AF_INET, PGSQL_AF_INET6, and pq_net_family_inet.
new_parameter() [53/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::macaddr & value)
References pq_async::macaddr::a, pq_async::macaddr::b, pq_async::macaddr::c, pq_async::macaddr::d, pq_async::macaddr::e, pq_async::macaddr::f, and MACADDROID.
new_parameter() [54/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::macaddr8 & value)
References pq_async::macaddr8::a, pq_async::macaddr8::b, pq_async::macaddr8::c, pq_async::macaddr8::d, pq_async::macaddr8::e, pq_async::macaddr8::f, pq_async::macaddr8::g, pq_async::macaddr8::h, and MACADDR8OID.
new_parameter() [55/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::point & value)
References POINTOID, and swap8().
new_parameter() [56/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::line & value)
References LINEOID, and swap8().
new_parameter() [57/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::lseg & value)
References LSEGOID, and swap8().
new_parameter() [58/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::box & value)
References BOXOID, and swap8().
new_parameter() [59/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::path & value)
References PATHOID, swap4(), and swap8().
new_parameter() [60/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::polygon & value)
References POLYGONOID, swap4(), and swap8().
new_parameter() [61/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::circle & value)
References CIRCLEOID, and swap8().
new_parameter() [62/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::int4range & value)
References INT4RANGEOID, and swap4().
new_parameter() [63/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::int8range & value)
References INT8RANGEOID, swap4(), and swap8().
new_parameter() [64/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::numrange & value)
References NUMRANGEOID, and swap4().
new_parameter() [65/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::tsrange & value)
References POSTGRES_EPOCH_USEC, swap4(), swap8(), and TSRANGEOID.
new_parameter() [66/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::tstzrange & value)
References POSTGRES_EPOCH_USEC, swap4(), swap8(), and TSTZRANGEOID.
new_parameter() [67/217]
pq_async::parameter * pq_async::new_parameter (const pq_async::daterange & value)
References DATERANGEOID, POSTGRES_EPOCH_JDATE, and swap4().
new_parameter() [68/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::lseg, 1 > & value)
new_parameter() [69/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::box, 1 > & value)
new_parameter() [70/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::path, 1 > & value)
new_parameter() [71/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::polygon, 1 > & value)
new_parameter() [72/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::circle, 1 > & value)
new_parameter() [73/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< std::string, 1 > & value)
new_parameter() [74/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< char *, 1 > & value)
new_parameter() [75/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int16_t, 1 > & value)
new_parameter() [76/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int32_t, 1 > & value)
new_parameter() [77/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int64_t, 1 > & value)
new_parameter() [78/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< float, 1 > & value)
new_parameter() [79/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< double, 1 > & value)
new_parameter() [80/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::numeric, 1 > & value)
new_parameter() [81/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::money, 1 > & value)
new_parameter() [82/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::time, 1 > & value)
new_parameter() [83/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::time_tz, 1 > & value)
new_parameter() [84/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::timestamp, 1 > & value)
new_parameter() [85/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::timestamp_tz, 1 > & value)
new_parameter() [86/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::date, 1 > & value)
new_parameter() [87/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::interval, 1 > & value)
new_parameter() [88/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::json, 1 > & value)
new_parameter() [89/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< std::vector< int8_t >, 1 > & value)
new_parameter() [90/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::uuid, 1 > & value)
new_parameter() [91/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::oid, 1 > & value)
new_parameter() [92/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::cidr, 1 > & value)
new_parameter() [93/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::inet, 1 > & value)
new_parameter() [94/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::macaddr, 1 > & value)
new_parameter() [95/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::macaddr8, 1 > & value)
new_parameter() [96/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::point, 1 > & value)
new_parameter() [97/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::line, 1 > & value)
new_parameter() [98/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< std::string, 2 > & value)
new_parameter() [99/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< char *, 2 > & value)
new_parameter() [100/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int16_t, 2 > & value)
new_parameter() [101/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int32_t, 2 > & value)
new_parameter() [102/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int64_t, 2 > & value)
new_parameter() [103/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< float, 2 > & value)
new_parameter() [104/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< double, 2 > & value)
new_parameter() [105/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::numeric, 2 > & value)
new_parameter() [106/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::money, 2 > & value)
new_parameter() [107/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::time, 2 > & value)
new_parameter() [108/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::time_tz, 2 > & value)
new_parameter() [109/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::timestamp, 2 > & value)
new_parameter() [110/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::timestamp_tz, 2 > & value)
new_parameter() [111/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::date, 2 > & value)
new_parameter() [112/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::interval, 2 > & value)
new_parameter() [113/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::json, 2 > & value)
new_parameter() [114/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< std::vector< int8_t >, 2 > & value)
new_parameter() [115/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::uuid, 2 > & value)
new_parameter() [116/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::oid, 2 > & value)
new_parameter() [117/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::cidr, 2 > & value)
new_parameter() [118/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::inet, 2 > & value)
new_parameter() [119/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::macaddr, 2 > & value)
new_parameter() [120/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::macaddr8, 2 > & value)
new_parameter() [121/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::point, 2 > & value)
new_parameter() [122/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::line, 2 > & value)
new_parameter() [123/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::lseg, 2 > & value)
new_parameter() [124/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::box, 2 > & value)
new_parameter() [125/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::path, 2 > & value)
new_parameter() [126/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::polygon, 2 > & value)
new_parameter() [127/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::circle, 2 > & value)
new_parameter() [128/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::circle, 3 > & value)
new_parameter() [129/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< std::string, 3 > & value)
new_parameter() [130/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< char *, 3 > & value)
new_parameter() [131/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int16_t, 3 > & value)
new_parameter() [132/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int32_t, 3 > & value)
new_parameter() [133/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int64_t, 3 > & value)
new_parameter() [134/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< float, 3 > & value)
new_parameter() [135/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< double, 3 > & value)
new_parameter() [136/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::numeric, 3 > & value)
new_parameter() [137/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::money, 3 > & value)
new_parameter() [138/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::time, 3 > & value)
new_parameter() [139/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::time_tz, 3 > & value)
new_parameter() [140/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::timestamp, 3 > & value)
new_parameter() [141/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::timestamp_tz, 3 > & value)
new_parameter() [142/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::date, 3 > & value)
new_parameter() [143/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::interval, 3 > & value)
new_parameter() [144/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::json, 3 > & value)
new_parameter() [145/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< std::vector< int8_t >, 3 > & value)
new_parameter() [146/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::uuid, 3 > & value)
new_parameter() [147/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::oid, 3 > & value)
new_parameter() [148/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::cidr, 3 > & value)
new_parameter() [149/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::inet, 3 > & value)
new_parameter() [150/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::macaddr, 3 > & value)
new_parameter() [151/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::macaddr8, 3 > & value)
new_parameter() [152/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::point, 3 > & value)
new_parameter() [153/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::line, 3 > & value)
new_parameter() [154/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::lseg, 3 > & value)
new_parameter() [155/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::box, 3 > & value)
new_parameter() [156/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::path, 3 > & value)
new_parameter() [157/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::polygon, 3 > & value)
new_parameter() [158/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< std::string, 4 > & value)
new_parameter() [159/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< char *, 4 > & value)
new_parameter() [160/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int16_t, 4 > & value)
new_parameter() [161/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int32_t, 4 > & value)
new_parameter() [162/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int64_t, 4 > & value)
new_parameter() [163/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< float, 4 > & value)
new_parameter() [164/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< double, 4 > & value)
new_parameter() [165/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::numeric, 4 > & value)
new_parameter() [166/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::money, 4 > & value)
new_parameter() [167/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::time, 4 > & value)
new_parameter() [168/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::time_tz, 4 > & value)
new_parameter() [169/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::timestamp, 4 > & value)
new_parameter() [170/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::timestamp_tz, 4 > & value)
new_parameter() [171/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::date, 4 > & value)
new_parameter() [172/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::interval, 4 > & value)
new_parameter() [173/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::json, 4 > & value)
new_parameter() [174/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< std::vector< int8_t >, 4 > & value)
new_parameter() [175/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::uuid, 4 > & value)
new_parameter() [176/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::oid, 4 > & value)
new_parameter() [177/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::cidr, 4 > & value)
new_parameter() [178/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::inet, 4 > & value)
new_parameter() [179/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::macaddr, 4 > & value)
new_parameter() [180/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::macaddr8, 4 > & value)
new_parameter() [181/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::point, 4 > & value)
new_parameter() [182/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::line, 4 > & value)
new_parameter() [183/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::lseg, 4 > & value)
new_parameter() [184/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::box, 4 > & value)
new_parameter() [185/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::path, 4 > & value)
new_parameter() [186/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::polygon, 4 > & value)
new_parameter() [187/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::circle, 4 > & value)
new_parameter() [188/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< std::string, 5 > & value)
new_parameter() [189/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< char *, 5 > & value)
new_parameter() [190/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int16_t, 5 > & value)
new_parameter() [191/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int32_t, 5 > & value)
new_parameter() [192/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< int64_t, 5 > & value)
new_parameter() [193/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< float, 5 > & value)
new_parameter() [194/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< double, 5 > & value)
new_parameter() [195/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::numeric, 5 > & value)
new_parameter() [196/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::money, 5 > & value)
new_parameter() [197/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::time, 5 > & value)
new_parameter() [198/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::time_tz, 5 > & value)
new_parameter() [199/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::timestamp, 5 > & value)
new_parameter() [200/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::timestamp_tz, 5 > & value)
new_parameter() [201/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::date, 5 > & value)
new_parameter() [202/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::interval, 5 > & value)
new_parameter() [203/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::json, 5 > & value)
new_parameter() [204/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< std::vector< int8_t >, 5 > & value)
new_parameter() [205/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::uuid, 5 > & value)
new_parameter() [206/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::oid, 5 > & value)
new_parameter() [207/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::cidr, 5 > & value)
new_parameter() [208/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::inet, 5 > & value)
new_parameter() [209/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::macaddr, 5 > & value)
new_parameter() [210/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::macaddr8, 5 > & value)
new_parameter() [211/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::point, 5 > & value)
new_parameter() [212/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::line, 5 > & value)
new_parameter() [213/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::lseg, 5 > & value)
new_parameter() [214/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::box, 5 > & value)
new_parameter() [215/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::path, 5 > & value)
new_parameter() [216/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::polygon, 5 > & value)
new_parameter() [217/217]
pq_async::parameter * pq_async::new_parameter (const boost::multi_array< pq_async::circle, 5 > & value)
new_parameter_gen()
template<class T , int32_t dim_count> pq_async::parameter* pq_async::new_parameter_gen (boost::multi_array< T, dim_count > value, int32_t eleOid, int32_t arrEleOid)
References pq_async::parameter::get_length(), pq_async::parameter::get_value(), new_parameter(), swap4(), and vec_append().
num_to_str()
template<typename T > std::string pq_async::num_to_str (T number, bool grouping = true) inline
Referenced by pq_async::numeric::from(), pq_async::oid::operator std::string(), pq_async::point::operator std::string(), pq_async::range< T >::operator std::string(), pq_async::line::operator std::string(), pq_async::circle::operator std::string(), plural(), pq_async::tests::TEST_F(), pq_async::duration::to_long_string(), pq_async::duration::to_short_string(), and pq_async::money::to_string().
numericvar_to_double_no_overflow()
double pq_async::numericvar_to_double_no_overflow (const numeric * var)
References pq_async::numeric::get_str_from_var.
Referenced by exp_var(), pq_async::numeric::operator double(), and power_var().
numericvar_to_int32()
int32_t pq_async::numericvar_to_int32 (const numeric * var)
References pq_async::numeric::numericvar_to_int64.
Referenced by pq_async::numeric::operator int32_t().
numericvar_to_int64()
bool pq_async::numericvar_to_int64 (const numeric * var, int64_t * result)
References pq_async::numeric::free_var, NBASE, NUMERIC_NEG, PG_INT64_MIN, pg_mul_s64_overflow(), pg_sub_s64_overflow(), pq_async::numeric::round_var, pq_async::numeric::strip_var, and unlikely.
operator &()
range_flag pq_async::operator& (range_flag a, range_flag b) inline
operator &=()
range_flag& pq_async::operator&= (range_flag & a, range_flag b) inline
operator!()
bool pq_async::operator! (range_flag a) inline
operator<<() [1/22]
std::ostream & pq_async::operator<< (std::ostream & os, const money & v)
operator<<() [2/22]
std::ostream & pq_async::operator<< (std::ostream & s, const cb_error & v)
References pq_async::cb_error::c_str(), and s.
Referenced by pq_async::cb_error::c_str().
operator<<() [3/22]
template<typename T > std::ostream & pq_async::operator<< (std::ostream & os, const range< T > & v)
operator<<() [4/22]
std::ostream & pq_async::operator<< (std::ostream & os, const pq_async::duration & d)
References pq_async::duration::to_long_string().
operator<<() [5/22]
std::ostream & pq_async::operator<< (std::ostream & os, const point & v)
operator<<() [6/22]
std::ostream & pq_async::operator<< (std::ostream & os, const line & v)
operator<<() [7/22]
std::ostream & pq_async::operator<< (std::ostream & os, const lseg & v)
operator<<() [8/22]
std::ostream & pq_async::operator<< (std::ostream & os, const box & v)
operator<<() [9/22]
std::ostream & pq_async::operator<< (std::ostream & os, const path & v)
operator<<() [10/22]
std::ostream & pq_async::operator<< (std::ostream & os, const polygon & v)
operator<<() [11/22]
std::ostream & pq_async::operator<< (std::ostream & os, const circle & v)
operator<<() [12/22]
std::ostream & pq_async::operator<< (std::ostream & os, const interval & v)
References pq_async::interval::iso_string().
operator<<() [13/22]
std::ostream & pq_async::operator<< (std::ostream & os, const pq_async::date & v)
References pq_async::date::iso_string().
operator<<() [14/22]
std::ostream & pq_async::operator<< (std::ostream & os, const timestamp & v)
References pq_async::timestamp::iso_string().
operator<<() [15/22]
std::ostream & pq_async::operator<< (std::ostream & os, const timestamp_tz & v)
References pq_async::timestamp_tz::iso_string().
operator<<() [16/22]
std::ostream & pq_async::operator<< (std::ostream & os, const time & v)
References pq_async::time::iso_string().
operator<<() [17/22]
std::ostream & pq_async::operator<< (std::ostream & os, const time_tz & v)
References pq_async::time_tz::iso_string().
operator<<() [18/22]
std::ostream & pq_async::operator<< (std::ostream & os, const cidr & v)
operator<<() [19/22]
std::ostream & pq_async::operator<< (std::ostream & os, const inet & v)
operator<<() [20/22]
std::ostream & pq_async::operator<< (std::ostream & os, const macaddr & v)
operator<<() [21/22]
std::ostream & pq_async::operator<< (std::ostream & os, const numeric & v)
operator<<() [22/22]
std::ostream & pq_async::operator<< (std::ostream & os, const macaddr8 & v)
operator>>() [1/19]
template<typename T > std::istream & pq_async::operator>> (std::istream & is, range< T > & v)
References s.
operator>>() [2/19]
std::istream & pq_async::operator>> (std::istream & is, duration & v)
References pq_async::duration::duration(), and s.
operator>>() [3/19]
std::istream & pq_async::operator>> (std::istream & is, point & v)
References pq_async::point::point(), and s.
operator>>() [4/19]
std::istream & pq_async::operator>> (std::istream & is, line & v)
References line, and s.
operator>>() [5/19]
std::istream & pq_async::operator>> (std::istream & is, lseg & v)
References s.
operator>>() [6/19]
std::istream & pq_async::operator>> (std::istream & is, box & v)
References box, and s.
operator>>() [7/19]
std::istream & pq_async::operator>> (std::istream & is, path & v)
References path, and s.
operator>>() [8/19]
std::istream & pq_async::operator>> (std::istream & is, polygon & v)
References polygon, and s.
operator>>() [9/19]
std::istream & pq_async::operator>> (std::istream & is, circle & v)
References circle, and s.
operator>>() [10/19]
std::istream & pq_async::operator>> (std::istream & is, interval & v)
References pq_async::interval::parse(), and s.
operator>>() [11/19]
std::istream & pq_async::operator>> (std::istream & is, pq_async::date & v)
References pq_async::date::parse(), and s.
operator>>() [12/19]
std::istream & pq_async::operator>> (std::istream & is, timestamp & v)
References pq_async::timestamp::parse(), and s.
operator>>() [13/19]
std::istream & pq_async::operator>> (std::istream & is, timestamp_tz & v)
References pq_async::timestamp_tz::parse(), and s.
operator>>() [14/19]
std::istream & pq_async::operator>> (std::istream & is, time & v)
References pq_async::time::parse(), and s.
operator>>() [15/19]
std::istream & pq_async::operator>> (std::istream & is, time_tz & v)
References pq_async::time_tz::parse(), and s.
operator>>() [16/19]
std::istream & pq_async::operator>> (std::istream & is, cidr & v)
References cidr, and s.
operator>>() [17/19]
std::istream & pq_async::operator>> (std::istream & is, inet & v)
References pq_async::inet::inet(), and s.
operator>>() [18/19]
std::istream & pq_async::operator>> (std::istream & is, macaddr & v)
References macaddr, and s.
operator>>() [19/19]
std::istream & pq_async::operator>> (std::istream & is, macaddr8 & v)
References macaddr8, and s.
operator^()
range_flag pq_async::operator^ (range_flag a, range_flag b) inline
operator^=()
range_flag& pq_async::operator^= (range_flag & a, range_flag b) inline
operator|()
range_flag pq_async::operator| (range_flag a, range_flag b) inline
operator|=()
range_flag& pq_async::operator|= (range_flag & a, range_flag b) inline
operator~()
range_flag pq_async::operator~ (range_flag a) inline
pg_mul_s64_overflow()
bool pq_async::pg_mul_s64_overflow (int64_t a, int64_t b, int64_t * result) inline
References PG_INT32_MAX, PG_INT32_MIN, PG_INT64_MAX, and PG_INT64_MIN.
Referenced by numericvar_to_int64().
pg_strncasecmp()
int pq_async::pg_strncasecmp (const char * s1, const char * s2, size_t n)
References IS_HIGHBIT_SET.
Referenced by pq_async::numeric::numeric().
pg_sub_s64_overflow()
bool pq_async::pg_sub_s64_overflow (int64_t a, int64_t b, int64_t * result) inline
References PG_INT64_MAX, and PG_INT64_MIN.
Referenced by numericvar_to_int64().
pgval_to_array()
template<class T , int32_t dim_count> boost::multi_array<T, dim_count> pq_async::pgval_to_array (char * val, int len, int fmt)
References new_null_parameter(), new_parameter(), PQ_ASYNC_ERR_DIM_NO_MATCH, PQ_ASYNC_ERR_NO_TEXT_FMT, swap4(), and vec_append().
pgval_to_bool()
bool pq_async::pgval_to_bool (char * val, int len, int fmt)
parameters code.
References iequals().
Referenced by val_from_pgparam().
pgval_to_box()
pq_async::box pq_async::pgval_to_box (char * val, int len, int fmt)
References pgval_to_point().
Referenced by val_from_pgparam().
pgval_to_bytea()
std::vector< int8_t > pq_async::pgval_to_bytea (char * val, int len, int fmt)
References bytea.
Referenced by val_from_pgparam().
pgval_to_cidr()
pq_async::cidr pq_async::pgval_to_cidr (char * val, int len, int fmt)
References PGSQL_AF_INET, PGSQL_AF_INET6, pq_net_family_inet, and pq_net_family_inet6.
Referenced by val_from_pgparam().
pgval_to_circle()
pq_async::circle pq_async::pgval_to_circle (char * val, int len, int fmt)
References pgval_to_double(), and pgval_to_point().
Referenced by val_from_pgparam().
pgval_to_date()
pq_async::date pq_async::pgval_to_date (char * val, int len, int fmt)
References POSTGRES_EPOCH_JDATE, and swap4().
Referenced by pgval_to_range< pq_async::daterange >(), and val_from_pgparam().
pgval_to_double()
double pq_async::pgval_to_double (char * val, int len, int fmt)
References swap8().
Referenced by pgval_to_circle(), pgval_to_line(), pgval_to_point(), and val_from_pgparam().
pgval_to_float()
float pq_async::pgval_to_float (char * val, int len, int fmt)
References swap4().
Referenced by val_from_pgparam().
pgval_to_inet()
pq_async::inet pq_async::pgval_to_inet (char * val, int len, int fmt)
References PGSQL_AF_INET, PGSQL_AF_INET6, pq_net_family_inet, and pq_net_family_inet6.
Referenced by val_from_pgparam().
pgval_to_int16()
int16_t pq_async::pgval_to_int16 (char * val, int len, int fmt)
References swap2().
Referenced by val_from_pgparam().
pgval_to_int32()
int32_t pq_async::pgval_to_int32 (char * val, int len, int fmt)
References swap4().
Referenced by pgval_to_path(), pgval_to_polygon(), pgval_to_range< pq_async::daterange >(), pgval_to_range< pq_async::int4range >(), pgval_to_range< pq_async::int8range >(), pgval_to_range< pq_async::numrange >(), pgval_to_range< pq_async::tsrange >(), pgval_to_range< pq_async::tstzrange >(), and val_from_pgparam().
pgval_to_int64()
int64_t pq_async::pgval_to_int64 (char * val, int len, int fmt)
References swap8().
Referenced by pgval_to_range< pq_async::int8range >(), and val_from_pgparam().
pgval_to_interval()
pq_async::interval pq_async::pgval_to_interval (char * val, int len, int fmt)
References swap4(), and swap8().
Referenced by val_from_pgparam().
pgval_to_line()
pq_async::line pq_async::pgval_to_line (char * val, int len, int fmt)
References pgval_to_double().
Referenced by val_from_pgparam().
pgval_to_lseg()
pq_async::lseg pq_async::pgval_to_lseg (char * val, int len, int fmt)
References pgval_to_point().
Referenced by val_from_pgparam().
pgval_to_macaddr()
pq_async::macaddr pq_async::pgval_to_macaddr (char * val, int len, int fmt)
References pq_async::macaddr::a, pq_async::macaddr::b, pq_async::macaddr::c, pq_async::macaddr::d, pq_async::macaddr::e, pq_async::macaddr::f, and m.
Referenced by val_from_pgparam().
pgval_to_macaddr8()
pq_async::macaddr8 pq_async::pgval_to_macaddr8 (char * val, int len, int fmt)
References pq_async::macaddr8::a, pq_async::macaddr8::b, pq_async::macaddr8::c, pq_async::macaddr8::d, pq_async::macaddr8::e, pq_async::macaddr8::f, pq_async::macaddr8::g, pq_async::macaddr8::h, and m.
Referenced by val_from_pgparam().
pgval_to_money()
pq_async::money pq_async::pgval_to_money (char * val, int len, int fmt)
References m, and swap8().
Referenced by val_from_pgparam().
pgval_to_numeric()
pq_async::numeric pq_async::pgval_to_numeric (char * val, int len, int fmt)
References s, and swap2().
Referenced by pgval_to_range< pq_async::numrange >(), and val_from_pgparam().
pgval_to_oid()
pq_async::oid pq_async::pgval_to_oid (char * val, int len, int fmt)
References swap4().
Referenced by val_from_pgparam().
pgval_to_path()
pq_async::path pq_async::pgval_to_path (char * val, int len, int fmt)
References pgval_to_int32(), and pgval_to_point().
Referenced by val_from_pgparam().
pgval_to_point()
pq_async::point pq_async::pgval_to_point (char * val, int len, int fmt)
References pgval_to_double().
Referenced by pgval_to_box(), pgval_to_circle(), pgval_to_lseg(), pgval_to_path(), pgval_to_polygon(), and val_from_pgparam().
pgval_to_polygon()
pq_async::polygon pq_async::pgval_to_polygon (char * val, int len, int fmt)
References pgval_to_int32(), and pgval_to_point().
Referenced by val_from_pgparam().
pgval_to_range()
template<typename T > T pq_async::pgval_to_range (char * val, int len, int fmt)
References get_array_oid_and_dim().
pgval_to_range< pq_async::daterange >()
template<> pq_async::daterange pq_async::pgval_to_range< pq_async::daterange > (char * val, int len, int fmt)
References pgval_to_date(), and pgval_to_int32().
pgval_to_range< pq_async::int4range >()
template<> pq_async::int4range pq_async::pgval_to_range< pq_async::int4range > (char * val, int len, int fmt)
References pgval_to_int32().
pgval_to_range< pq_async::int8range >()
template<> pq_async::int8range pq_async::pgval_to_range< pq_async::int8range > (char * val, int len, int fmt)
References pgval_to_int32(), and pgval_to_int64().
pgval_to_range< pq_async::numrange >()
template<> pq_async::numrange pq_async::pgval_to_range< pq_async::numrange > (char * val, int len, int fmt)
References pgval_to_int32(), and pgval_to_numeric().
pgval_to_range< pq_async::tsrange >()
template<> pq_async::tsrange pq_async::pgval_to_range< pq_async::tsrange > (char * val, int len, int fmt)
References pgval_to_int32(), and pgval_to_timestamp().
pgval_to_range< pq_async::tstzrange >()
template<> pq_async::tstzrange pq_async::pgval_to_range< pq_async::tstzrange > (char * val, int len, int fmt)
References pgval_to_int32(), and pgval_to_timestamp_tz().
pgval_to_string()
std::string pq_async::pgval_to_string (char * val, int len, int fmt)
Referenced by val_from_pgparam().
pgval_to_time()
pq_async::time pq_async::pgval_to_time (char * val, int len, int fmt)
References POSTGRES_EPOCH_USEC, and swap8().
Referenced by val_from_pgparam().
pgval_to_time_tz()
pq_async::time_tz pq_async::pgval_to_time_tz (char * val, int len, int fmt)
References POSTGRES_EPOCH_USEC, and swap8().
Referenced by val_from_pgparam().
pgval_to_timestamp()
pq_async::timestamp pq_async::pgval_to_timestamp (char * val, int len, int fmt)
References POSTGRES_EPOCH_USEC, and swap8().
Referenced by pgval_to_range< pq_async::tsrange >(), and val_from_pgparam().
pgval_to_timestamp_tz()
pq_async::timestamp_tz pq_async::pgval_to_timestamp_tz (char * val, int len, int fmt)
References POSTGRES_EPOCH_USEC, and swap8().
Referenced by pgval_to_range< pq_async::tstzrange >(), and val_from_pgparam().
pgval_to_uuid()
pq_async::uuid pq_async::pgval_to_uuid (char * val, int len, int fmt)
Referenced by val_from_pgparam().
plural()
std::string pq_async::plural (long double ms_val, long double ms_abs, long double n, const std::string & name)
References num_to_str().
Referenced by pq_async::duration::to_long_string().
power_var()
void pq_async::power_var (const numeric * base, const numeric * exp, numeric * result)
References pq_async::numeric::cmp_var, pq_async::numeric::estimate_ln_dweight, pq_async::numeric::exp_var, pq_async::numeric::free_var, pq_async::numeric::ln_var, pq_async::numeric::mul_var, NUMERIC_MAX_DISPLAY_SCALE, NUMERIC_MAX_RESULT_SCALE, NUMERIC_MIN_DISPLAY_SCALE, NUMERIC_MIN_SIG_DIGITS, numericvar_to_double_no_overflow(), pq_async::numeric::numericvar_to_int64, and pq_async::numeric::power_var_int.
power_var_int()
void pq_async::power_var_int (const numeric * base, int exp, numeric * result, int rscale)
References DEC_DIGITS, pq_async::numeric::div_var, pq_async::numeric::div_var_fast, pq_async::numeric::free_var, pq_async::numeric::mul_var, NBASE, NUMERIC_MAX_DISPLAY_SCALE, NUMERIC_MIN_DISPLAY_SCALE, pq_async::numeric::round_var, and pq_async::numeric::zero_var.
prepare_footer()
std::string pq_async::prepare_footer (const char * color)
References pq_async::log::is_color_enabled(), and PQ_ASYNC_MAX_LOG_LENGTH.
Referenced by exec().
prepare_header()
std::string pq_async::prepare_header (const char * color, const char * hint, const char * ts, bool is_core)
References pq_async::log::is_color_enabled(), and PQ_ASYNC_MAX_LOG_LENGTH.
Referenced by exec().
round_var()
void pq_async::round_var (numeric * var, int rscale)
References DEC_DIGITS, HALF_NBASE, NBASE, and NUMERIC_POS.
rtrim()
void pq_async::rtrim (std::string & s) inline
Referenced by rtrim_copy(), and trim().
rtrim_copy()
std::string pq_async::rtrim_copy (std::string s) inline
References rtrim(), and s.
select_div_scale()
int pq_async::select_div_scale (const numeric * var1, const numeric * var2)
References DEC_DIGITS, NUMERIC_MAX_DISPLAY_SCALE, NUMERIC_MIN_DISPLAY_SCALE, and NUMERIC_MIN_SIG_DIGITS.
set_var_from_str()
const char * pq_async::set_var_from_str (const char * str, const char * cp, numeric * dest)
References pq_async::numeric::alloc_var, DEC_DIGITS, INT_MAX, NUMERIC_NEG, NUMERIC_POS, and pq_async::numeric::strip_var.
sqrt_var()
void pq_async::sqrt_var (const numeric * arg, numeric * result, int rscale)
References pq_async::numeric::add_var, pq_async::numeric::alloc_var, pq_async::numeric::cmp_var, pq_async::numeric::div_var_fast, pq_async::numeric::free_var, pq_async::numeric::mul_var, NUMERIC_POS, pq_async::numeric::round_var, and pq_async::numeric::zero_var.
str_to_lower()
std::string pq_async::str_to_lower (const std::string & str) inline
Referenced by pq_async::data_columns_container::get_col_index(), and text_to_duration().
str_to_num()
template<typename T > T pq_async::str_to_num (const std::string & text) inline
strip_var()
void pq_async::strip_var (numeric * var)
References NUMERIC_POS.
sub_abs()
void pq_async::sub_abs (const numeric * var1, const numeric * var2, numeric * result)
References digitbuf_alloc, digitbuf_free, NBASE, and pq_async::numeric::strip_var.
sub_var()
void pq_async::sub_var (const numeric * var1, const numeric * var2, numeric * result)
References pq_async::numeric::add_abs, pq_async::numeric::cmp_abs, NUMERIC_NEG, NUMERIC_POS, pq_async::numeric::sub_abs, and pq_async::numeric::zero_var.
swap2()
void pq_async::swap2 (const int16_t * inp, int16_t * outp, bool to_network)
Referenced by join(), new_parameter(), pgval_to_int16(), and pgval_to_numeric().
swap4()
void pq_async::swap4 (const int32_t * inp, int32_t * outp, bool to_network)
Referenced by get_array_oid_and_dim(), join(), new_parameter(), new_parameter_gen(), pgval_to_array(), pgval_to_date(), pgval_to_float(), pgval_to_int32(), pgval_to_interval(), and pgval_to_oid().
swap8()
void pq_async::swap8 (const int64_t * inp, int64_t * outp, bool to_network)
Referenced by join(), new_parameter(), pgval_to_double(), pgval_to_int64(), pgval_to_interval(), pgval_to_money(), pgval_to_time(), pgval_to_time_tz(), pgval_to_timestamp(), and pgval_to_timestamp_tz().
text_to_duration()
long double pq_async::text_to_duration (const std::string & val)
References d, h, m, s, str_to_lower(), trim(), w, and y.
Referenced by pq_async::duration::duration().
trim()
void pq_async::trim (std::string & s) inline
References ltrim(), and rtrim().
Referenced by pq_async::box::box(), pq_async::circle::circle(), pq_async::log::init(), pq_async::line::line(), pq_async::lseg::lseg(), pq_async::range< T >::operator std::string(), pq_async::path::path(), pq_async::point::point(), pq_async::polygon::polygon(), pq_async::range< T >::range(), pq_async::database::split_queries(), text_to_duration(), and trim_copy().
trim_copy()
std::string pq_async::trim_copy (std::string s) inline
References s, and trim().
trunc_var()
void pq_async::trunc_var (numeric * var, int rscale)
References DEC_DIGITS, and NUMERIC_POS.
val_from_pgparam()
template<typename T > T pq_async::val_from_pgparam (int oid, char * val, int len, int format)
References oid, pgval_to_bool(), pgval_to_box(), pgval_to_bytea(), pgval_to_cidr(), pgval_to_circle(), pgval_to_date(), pgval_to_double(), pgval_to_float(), pgval_to_inet(), pgval_to_int16(), pgval_to_int32(), pgval_to_int64(), pgval_to_interval(), pgval_to_line(), pgval_to_lseg(), pgval_to_macaddr(), pgval_to_macaddr8(), pgval_to_money(), pgval_to_numeric(), pgval_to_oid(), pgval_to_path(), pgval_to_point(), pgval_to_polygon(), pgval_to_string(), pgval_to_time(), pgval_to_time_tz(), pgval_to_timestamp(), pgval_to_timestamp_tz(), pgval_to_uuid(), val_from_pgparam< bool >(), val_from_pgparam< double >(), val_from_pgparam< float >(), val_from_pgparam< int16_t >(), val_from_pgparam< int32_t >(), and val_from_pgparam< int64_t >().
val_from_pgparam< bool >()
template<> bool pq_async::val_from_pgparam< bool > (int oid, char * val, int len, int format)
Referenced by val_from_pgparam().
val_from_pgparam< boost::multi_array< char *, 1 > >()
template<> boost::multi_array< char *, 1 > pq_async::val_from_pgparam< boost::multi_array< char *, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< char *, 2 > >()
template<> boost::multi_array< char *, 2 > pq_async::val_from_pgparam< boost::multi_array< char *, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< char *, 3 > >()
template<> boost::multi_array< char *, 3 > pq_async::val_from_pgparam< boost::multi_array< char *, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< char *, 4 > >()
template<> boost::multi_array< char *, 4 > pq_async::val_from_pgparam< boost::multi_array< char *, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< char *, 5 > >()
template<> boost::multi_array< char *, 5 > pq_async::val_from_pgparam< boost::multi_array< char *, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< double, 1 > >()
template<> boost::multi_array< double, 1 > pq_async::val_from_pgparam< boost::multi_array< double, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< double, 2 > >()
template<> boost::multi_array< double, 2 > pq_async::val_from_pgparam< boost::multi_array< double, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< double, 3 > >()
template<> boost::multi_array< double, 3 > pq_async::val_from_pgparam< boost::multi_array< double, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< double, 4 > >()
template<> boost::multi_array< double, 4 > pq_async::val_from_pgparam< boost::multi_array< double, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< double, 5 > >()
template<> boost::multi_array< double, 5 > pq_async::val_from_pgparam< boost::multi_array< double, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< float, 1 > >()
template<> boost::multi_array< float, 1 > pq_async::val_from_pgparam< boost::multi_array< float, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< float, 2 > >()
template<> boost::multi_array< float, 2 > pq_async::val_from_pgparam< boost::multi_array< float, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< float, 3 > >()
template<> boost::multi_array< float, 3 > pq_async::val_from_pgparam< boost::multi_array< float, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< float, 4 > >()
template<> boost::multi_array< float, 4 > pq_async::val_from_pgparam< boost::multi_array< float, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< float, 5 > >()
template<> boost::multi_array< float, 5 > pq_async::val_from_pgparam< boost::multi_array< float, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int16_t, 1 > >()
template<> boost::multi_array< int16_t, 1 > pq_async::val_from_pgparam< boost::multi_array< int16_t, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int16_t, 2 > >()
template<> boost::multi_array< int16_t, 2 > pq_async::val_from_pgparam< boost::multi_array< int16_t, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int16_t, 3 > >()
template<> boost::multi_array< int16_t, 3 > pq_async::val_from_pgparam< boost::multi_array< int16_t, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int16_t, 4 > >()
template<> boost::multi_array< int16_t, 4 > pq_async::val_from_pgparam< boost::multi_array< int16_t, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int16_t, 5 > >()
template<> boost::multi_array< int16_t, 5 > pq_async::val_from_pgparam< boost::multi_array< int16_t, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int32_t, 1 > >()
template<> boost::multi_array< int32_t, 1 > pq_async::val_from_pgparam< boost::multi_array< int32_t, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int32_t, 2 > >()
template<> boost::multi_array< int32_t, 2 > pq_async::val_from_pgparam< boost::multi_array< int32_t, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int32_t, 3 > >()
template<> boost::multi_array< int32_t, 3 > pq_async::val_from_pgparam< boost::multi_array< int32_t, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int32_t, 4 > >()
template<> boost::multi_array< int32_t, 4 > pq_async::val_from_pgparam< boost::multi_array< int32_t, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int32_t, 5 > >()
template<> boost::multi_array< int32_t, 5 > pq_async::val_from_pgparam< boost::multi_array< int32_t, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int64_t, 1 > >()
template<> boost::multi_array< int64_t, 1 > pq_async::val_from_pgparam< boost::multi_array< int64_t, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int64_t, 2 > >()
template<> boost::multi_array< int64_t, 2 > pq_async::val_from_pgparam< boost::multi_array< int64_t, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int64_t, 3 > >()
template<> boost::multi_array< int64_t, 3 > pq_async::val_from_pgparam< boost::multi_array< int64_t, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int64_t, 4 > >()
template<> boost::multi_array< int64_t, 4 > pq_async::val_from_pgparam< boost::multi_array< int64_t, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< int64_t, 5 > >()
template<> boost::multi_array< int64_t, 5 > pq_async::val_from_pgparam< boost::multi_array< int64_t, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::box, 1 > >()
template<> boost::multi_array< pq_async::box, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::box, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::box, 2 > >()
template<> boost::multi_array< pq_async::box, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::box, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::box, 3 > >()
template<> boost::multi_array< pq_async::box, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::box, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::box, 4 > >()
template<> boost::multi_array< pq_async::box, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::box, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::box, 5 > >()
template<> boost::multi_array< pq_async::box, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::box, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::cidr, 1 > >()
template<> boost::multi_array< pq_async::cidr, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::cidr, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::cidr, 2 > >()
template<> boost::multi_array< pq_async::cidr, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::cidr, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::cidr, 3 > >()
template<> boost::multi_array< pq_async::cidr, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::cidr, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::cidr, 4 > >()
template<> boost::multi_array< pq_async::cidr, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::cidr, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::cidr, 5 > >()
template<> boost::multi_array< pq_async::cidr, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::cidr, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::circle, 1 > >()
template<> boost::multi_array< pq_async::circle, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::circle, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::circle, 2 > >()
template<> boost::multi_array< pq_async::circle, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::circle, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::circle, 3 > >()
template<> boost::multi_array< pq_async::circle, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::circle, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::circle, 4 > >()
template<> boost::multi_array< pq_async::circle, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::circle, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::circle, 5 > >()
template<> boost::multi_array< pq_async::circle, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::circle, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::date, 1 > >()
template<> boost::multi_array< pq_async::date, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::date, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::date, 2 > >()
template<> boost::multi_array< pq_async::date, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::date, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::date, 3 > >()
template<> boost::multi_array< pq_async::date, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::date, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::date, 4 > >()
template<> boost::multi_array< pq_async::date, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::date, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::date, 5 > >()
template<> boost::multi_array< pq_async::date, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::date, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::daterange, 1 > >()
template<> boost::multi_array< pq_async::daterange , 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::daterange, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::daterange, 2 > >()
template<> boost::multi_array< pq_async::daterange , 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::daterange, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::daterange, 3 > >()
template<> boost::multi_array< pq_async::daterange , 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::daterange, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::daterange, 4 > >()
template<> boost::multi_array< pq_async::daterange , 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::daterange, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::daterange, 5 > >()
template<> boost::multi_array< pq_async::daterange , 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::daterange, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::inet, 1 > >()
template<> boost::multi_array< pq_async::inet, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::inet, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::inet, 2 > >()
template<> boost::multi_array< pq_async::inet, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::inet, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::inet, 3 > >()
template<> boost::multi_array< pq_async::inet, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::inet, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::inet, 4 > >()
template<> boost::multi_array< pq_async::inet, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::inet, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::inet, 5 > >()
template<> boost::multi_array< pq_async::inet, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::inet, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::int4range, 1 > >()
template<> boost::multi_array< pq_async::int4range , 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::int4range, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::int4range, 2 > >()
template<> boost::multi_array< pq_async::int4range , 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::int4range, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::int4range, 3 > >()
template<> boost::multi_array< pq_async::int4range , 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::int4range, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::int4range, 4 > >()
template<> boost::multi_array< pq_async::int4range , 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::int4range, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::int4range, 5 > >()
template<> boost::multi_array< pq_async::int4range , 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::int4range, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::int8range, 1 > >()
template<> boost::multi_array< pq_async::int8range , 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::int8range, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::int8range, 2 > >()
template<> boost::multi_array< pq_async::int8range , 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::int8range, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::int8range, 3 > >()
template<> boost::multi_array< pq_async::int8range , 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::int8range, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::int8range, 4 > >()
template<> boost::multi_array< pq_async::int8range , 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::int8range, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::int8range, 5 > >()
template<> boost::multi_array< pq_async::int8range , 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::int8range, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::interval, 1 > >()
template<> boost::multi_array< pq_async::interval, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::interval, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::interval, 2 > >()
template<> boost::multi_array< pq_async::interval, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::interval, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::interval, 3 > >()
template<> boost::multi_array< pq_async::interval, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::interval, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::interval, 4 > >()
template<> boost::multi_array< pq_async::interval, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::interval, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::interval, 5 > >()
template<> boost::multi_array< pq_async::interval, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::interval, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::json, 1 > >()
template<> boost::multi_array< pq_async::json, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::json, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::json, 2 > >()
template<> boost::multi_array< pq_async::json, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::json, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::json, 3 > >()
template<> boost::multi_array< pq_async::json, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::json, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::json, 4 > >()
template<> boost::multi_array< pq_async::json, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::json, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::json, 5 > >()
template<> boost::multi_array< pq_async::json, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::json, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::line, 1 > >()
template<> boost::multi_array< pq_async::line, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::line, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::line, 2 > >()
template<> boost::multi_array< pq_async::line, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::line, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::line, 3 > >()
template<> boost::multi_array< pq_async::line, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::line, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::line, 4 > >()
template<> boost::multi_array< pq_async::line, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::line, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::line, 5 > >()
template<> boost::multi_array< pq_async::line, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::line, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::lseg, 1 > >()
template<> boost::multi_array< pq_async::lseg, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::lseg, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::lseg, 2 > >()
template<> boost::multi_array< pq_async::lseg, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::lseg, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::lseg, 3 > >()
template<> boost::multi_array< pq_async::lseg, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::lseg, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::lseg, 4 > >()
template<> boost::multi_array< pq_async::lseg, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::lseg, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::lseg, 5 > >()
template<> boost::multi_array< pq_async::lseg, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::lseg, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::macaddr, 1 > >()
template<> boost::multi_array< pq_async::macaddr, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::macaddr, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::macaddr, 2 > >()
template<> boost::multi_array< pq_async::macaddr, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::macaddr, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::macaddr, 3 > >()
template<> boost::multi_array< pq_async::macaddr, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::macaddr, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::macaddr, 4 > >()
template<> boost::multi_array< pq_async::macaddr, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::macaddr, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::macaddr, 5 > >()
template<> boost::multi_array< pq_async::macaddr, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::macaddr, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::macaddr8, 1 > >()
template<> boost::multi_array< pq_async::macaddr8, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::macaddr8, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::macaddr8, 2 > >()
template<> boost::multi_array< pq_async::macaddr8, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::macaddr8, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::macaddr8, 3 > >()
template<> boost::multi_array< pq_async::macaddr8, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::macaddr8, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::macaddr8, 4 > >()
template<> boost::multi_array< pq_async::macaddr8, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::macaddr8, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::macaddr8, 5 > >()
template<> boost::multi_array< pq_async::macaddr8, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::macaddr8, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::money, 1 > >()
template<> boost::multi_array< pq_async::money, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::money, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::money, 2 > >()
template<> boost::multi_array< pq_async::money, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::money, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::money, 3 > >()
template<> boost::multi_array< pq_async::money, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::money, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::money, 4 > >()
template<> boost::multi_array< pq_async::money, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::money, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::money, 5 > >()
template<> boost::multi_array< pq_async::money, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::money, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::numeric, 1 > >()
template<> boost::multi_array< pq_async::numeric, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::numeric, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::numeric, 2 > >()
template<> boost::multi_array< pq_async::numeric, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::numeric, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::numeric, 3 > >()
template<> boost::multi_array< pq_async::numeric, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::numeric, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::numeric, 4 > >()
template<> boost::multi_array< pq_async::numeric, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::numeric, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::numeric, 5 > >()
template<> boost::multi_array< pq_async::numeric, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::numeric, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::numrange, 1 > >()
template<> boost::multi_array< pq_async::numrange , 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::numrange, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::numrange, 2 > >()
template<> boost::multi_array< pq_async::numrange , 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::numrange, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::numrange, 3 > >()
template<> boost::multi_array< pq_async::numrange , 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::numrange, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::numrange, 4 > >()
template<> boost::multi_array< pq_async::numrange , 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::numrange, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::numrange, 5 > >()
template<> boost::multi_array< pq_async::numrange , 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::numrange, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::oid, 1 > >()
template<> boost::multi_array< pq_async::oid, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::oid, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::oid, 2 > >()
template<> boost::multi_array< pq_async::oid, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::oid, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::oid, 3 > >()
template<> boost::multi_array< pq_async::oid, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::oid, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::oid, 4 > >()
template<> boost::multi_array< pq_async::oid, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::oid, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::oid, 5 > >()
template<> boost::multi_array< pq_async::oid, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::oid, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::path, 1 > >()
template<> boost::multi_array< pq_async::path, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::path, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::path, 2 > >()
template<> boost::multi_array< pq_async::path, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::path, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::path, 3 > >()
template<> boost::multi_array< pq_async::path, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::path, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::path, 4 > >()
template<> boost::multi_array< pq_async::path, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::path, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::path, 5 > >()
template<> boost::multi_array< pq_async::path, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::path, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::point, 1 > >()
template<> boost::multi_array< pq_async::point, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::point, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::point, 2 > >()
template<> boost::multi_array< pq_async::point, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::point, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::point, 3 > >()
template<> boost::multi_array< pq_async::point, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::point, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::point, 4 > >()
template<> boost::multi_array< pq_async::point, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::point, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::point, 5 > >()
template<> boost::multi_array< pq_async::point, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::point, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::polygon, 1 > >()
template<> boost::multi_array< pq_async::polygon, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::polygon, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::polygon, 2 > >()
template<> boost::multi_array< pq_async::polygon, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::polygon, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::polygon, 3 > >()
template<> boost::multi_array< pq_async::polygon, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::polygon, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::polygon, 4 > >()
template<> boost::multi_array< pq_async::polygon, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::polygon, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::polygon, 5 > >()
template<> boost::multi_array< pq_async::polygon, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::polygon, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::time, 1 > >()
template<> boost::multi_array< pq_async::time, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::time, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::time, 2 > >()
template<> boost::multi_array< pq_async::time, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::time, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::time, 3 > >()
template<> boost::multi_array< pq_async::time, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::time, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::time, 4 > >()
template<> boost::multi_array< pq_async::time, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::time, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::time, 5 > >()
template<> boost::multi_array< pq_async::time, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::time, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::time_tz, 1 > >()
template<> boost::multi_array< pq_async::time_tz, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::time_tz, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::time_tz, 2 > >()
template<> boost::multi_array< pq_async::time_tz, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::time_tz, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::time_tz, 3 > >()
template<> boost::multi_array< pq_async::time_tz, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::time_tz, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::time_tz, 4 > >()
template<> boost::multi_array< pq_async::time_tz, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::time_tz, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::time_tz, 5 > >()
template<> boost::multi_array< pq_async::time_tz, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::time_tz, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::timestamp, 1 > >()
template<> boost::multi_array< pq_async::timestamp, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::timestamp, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::timestamp, 2 > >()
template<> boost::multi_array< pq_async::timestamp, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::timestamp, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::timestamp, 3 > >()
template<> boost::multi_array< pq_async::timestamp, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::timestamp, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::timestamp, 4 > >()
template<> boost::multi_array< pq_async::timestamp, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::timestamp, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::timestamp, 5 > >()
template<> boost::multi_array< pq_async::timestamp, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::timestamp, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 1 > >()
template<> boost::multi_array< pq_async::timestamp_tz, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 2 > >()
template<> boost::multi_array< pq_async::timestamp_tz, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 3 > >()
template<> boost::multi_array< pq_async::timestamp_tz, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 4 > >()
template<> boost::multi_array< pq_async::timestamp_tz, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 5 > >()
template<> boost::multi_array< pq_async::timestamp_tz, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::timestamp_tz, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::tsrange, 1 > >()
template<> boost::multi_array< pq_async::tsrange , 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::tsrange, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::tsrange, 2 > >()
template<> boost::multi_array< pq_async::tsrange , 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::tsrange, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::tsrange, 3 > >()
template<> boost::multi_array< pq_async::tsrange , 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::tsrange, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::tsrange, 4 > >()
template<> boost::multi_array< pq_async::tsrange , 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::tsrange, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::tsrange, 5 > >()
template<> boost::multi_array< pq_async::tsrange , 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::tsrange, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::tstzrange, 1 > >()
template<> boost::multi_array< pq_async::tstzrange , 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::tstzrange, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::tstzrange, 2 > >()
template<> boost::multi_array< pq_async::tstzrange , 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::tstzrange, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::tstzrange, 3 > >()
template<> boost::multi_array< pq_async::tstzrange , 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::tstzrange, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::tstzrange, 4 > >()
template<> boost::multi_array< pq_async::tstzrange , 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::tstzrange, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::tstzrange, 5 > >()
template<> boost::multi_array< pq_async::tstzrange , 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::tstzrange, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::uuid, 1 > >()
template<> boost::multi_array< pq_async::uuid, 1 > pq_async::val_from_pgparam< boost::multi_array< pq_async::uuid, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::uuid, 2 > >()
template<> boost::multi_array< pq_async::uuid, 2 > pq_async::val_from_pgparam< boost::multi_array< pq_async::uuid, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::uuid, 3 > >()
template<> boost::multi_array< pq_async::uuid, 3 > pq_async::val_from_pgparam< boost::multi_array< pq_async::uuid, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::uuid, 4 > >()
template<> boost::multi_array< pq_async::uuid, 4 > pq_async::val_from_pgparam< boost::multi_array< pq_async::uuid, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< pq_async::uuid, 5 > >()
template<> boost::multi_array< pq_async::uuid, 5 > pq_async::val_from_pgparam< boost::multi_array< pq_async::uuid, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< std::string, 1 > >()
template<> boost::multi_array< std::string, 1 > pq_async::val_from_pgparam< boost::multi_array< std::string, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< std::string, 2 > >()
template<> boost::multi_array< std::string, 2 > pq_async::val_from_pgparam< boost::multi_array< std::string, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< std::string, 3 > >()
template<> boost::multi_array< std::string, 3 > pq_async::val_from_pgparam< boost::multi_array< std::string, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< std::string, 4 > >()
template<> boost::multi_array< std::string, 4 > pq_async::val_from_pgparam< boost::multi_array< std::string, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< std::string, 5 > >()
template<> boost::multi_array< std::string, 5 > pq_async::val_from_pgparam< boost::multi_array< std::string, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< std::vector< int8_t >, 1 > >()
template<> boost::multi_array< std::vector< int8_t >, 1 > pq_async::val_from_pgparam< boost::multi_array< std::vector< int8_t >, 1 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< std::vector< int8_t >, 2 > >()
template<> boost::multi_array< std::vector< int8_t >, 2 > pq_async::val_from_pgparam< boost::multi_array< std::vector< int8_t >, 2 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< std::vector< int8_t >, 3 > >()
template<> boost::multi_array< std::vector< int8_t >, 3 > pq_async::val_from_pgparam< boost::multi_array< std::vector< int8_t >, 3 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< std::vector< int8_t >, 4 > >()
template<> boost::multi_array< std::vector< int8_t >, 4 > pq_async::val_from_pgparam< boost::multi_array< std::vector< int8_t >, 4 > > (int oid, char * val, int len, int format)
val_from_pgparam< boost::multi_array< std::vector< int8_t >, 5 > >()
template<> boost::multi_array< std::vector< int8_t >, 5 > pq_async::val_from_pgparam< boost::multi_array< std::vector< int8_t >, 5 > > (int oid, char * val, int len, int format)
val_from_pgparam< double >()
template<> double pq_async::val_from_pgparam< double > (int oid, char * val, int len, int format)
Referenced by val_from_pgparam().
val_from_pgparam< float >()
template<> float pq_async::val_from_pgparam< float > (int oid, char * val, int len, int format)
Referenced by val_from_pgparam().
val_from_pgparam< int16_t >()
template<> int16_t pq_async::val_from_pgparam< int16_t > (int oid, char * val, int len, int format)
Referenced by val_from_pgparam().
val_from_pgparam< int32_t >()
template<> int32_t pq_async::val_from_pgparam< int32_t > (int oid, char * val, int len, int format)
Referenced by val_from_pgparam().
val_from_pgparam< int64_t >()
template<> int64_t pq_async::val_from_pgparam< int64_t > (int oid, char * val, int len, int format)
Referenced by val_from_pgparam().
val_from_pgparam< pq_async::box >()
template<> pq_async::box pq_async::val_from_pgparam< pq_async::box > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::cidr >()
template<> pq_async::cidr pq_async::val_from_pgparam< pq_async::cidr > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::circle >()
template<> pq_async::circle pq_async::val_from_pgparam< pq_async::circle > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::date >()
template<> pq_async::date pq_async::val_from_pgparam< pq_async::date > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::daterange >()
template<> pq_async::daterange pq_async::val_from_pgparam< pq_async::daterange > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::inet >()
template<> pq_async::inet pq_async::val_from_pgparam< pq_async::inet > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::int4range >()
template<> pq_async::int4range pq_async::val_from_pgparam< pq_async::int4range > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::int8range >()
template<> pq_async::int8range pq_async::val_from_pgparam< pq_async::int8range > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::interval >()
template<> pq_async::interval pq_async::val_from_pgparam< pq_async::interval > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::json >()
template<> pq_async::json pq_async::val_from_pgparam< pq_async::json > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::line >()
template<> pq_async::line pq_async::val_from_pgparam< pq_async::line > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::lseg >()
template<> pq_async::lseg pq_async::val_from_pgparam< pq_async::lseg > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::macaddr >()
template<> pq_async::macaddr pq_async::val_from_pgparam< pq_async::macaddr > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::macaddr8 >()
template<> pq_async::macaddr8 pq_async::val_from_pgparam< pq_async::macaddr8 > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::money >()
template<> pq_async::money pq_async::val_from_pgparam< pq_async::money > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::numeric >()
template<> pq_async::numeric pq_async::val_from_pgparam< pq_async::numeric > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::numrange >()
template<> pq_async::numrange pq_async::val_from_pgparam< pq_async::numrange > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::oid >()
template<> pq_async::oid pq_async::val_from_pgparam< pq_async::oid > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::path >()
template<> pq_async::path pq_async::val_from_pgparam< pq_async::path > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::point >()
template<> pq_async::point pq_async::val_from_pgparam< pq_async::point > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::polygon >()
template<> pq_async::polygon pq_async::val_from_pgparam< pq_async::polygon > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::time >()
template<> pq_async::time pq_async::val_from_pgparam< pq_async::time > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::time_tz >()
template<> pq_async::time_tz pq_async::val_from_pgparam< pq_async::time_tz > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::timestamp >()
template<> pq_async::timestamp pq_async::val_from_pgparam< pq_async::timestamp > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::timestamp_tz >()
template<> pq_async::timestamp_tz pq_async::val_from_pgparam< pq_async::timestamp_tz > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::tsrange >()
template<> pq_async::tsrange pq_async::val_from_pgparam< pq_async::tsrange > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::tstzrange >()
template<> pq_async::tstzrange pq_async::val_from_pgparam< pq_async::tstzrange > (int oid, char * val, int len, int format)
val_from_pgparam< pq_async::uuid >()
template<> pq_async::uuid pq_async::val_from_pgparam< pq_async::uuid > (int oid, char * val, int len, int format)
val_from_pgparam< std::string >()
template<> std::string pq_async::val_from_pgparam< std::string > (int oid, char * val, int len, int format)
val_from_pgparam< std::vector< int8_t > >()
template<> std::vector< int8_t > pq_async::val_from_pgparam< std::vector< int8_t > > (int oid, char * val, int len, int format)
vec_append()
void pq_async::vec_append (std::vector< char > & vec, char * buf, int len)
Referenced by new_parameter_gen(), and pgval_to_array().
zero_var()
void pq_async::zero_var (numeric * var)
References digitbuf_free, and NUMERIC_POS.
Variable Documentation
d
const long double pq_async::d = h * 24.0L
Referenced by div_var(), get_str_from_var(), pq_async::macaddr::macaddr(), pq_async::macaddr8::macaddr8(), pq_async::duration::operator interval(), pq_async::macaddr::operator std::string(), pq_async::macaddr8::operator std::string(), pq_async::tests::TEST_F(), text_to_duration(), and pq_async::money::to_string().
h
const long double pq_async::h = m * 60.0L
Referenced by pq_async::interval::iso_string(), pq_async::macaddr8::macaddr8(), pq_async::macaddr8::operator std::string(), and text_to_duration().
hexmap
constexpr char pq_async::hexmap[]
Initial value:
= {
    '0', '1', '2', '3', '4', '5', '6', '7',
    '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'
}
m
const long double pq_async::m = s * 60.0L
Referenced by pq_async::money::from_num(), pq_async::money::from_numeric(), pq_async::interval::iso_string(), pq_async::line::line(), pq_async::point::normal(), pq_async::data_large_object::opened_write(), pq_async::interval::operator hhdate::sys_time< std::chrono::microseconds >(), pgval_to_macaddr(), pgval_to_macaddr8(), pgval_to_money(), pq_async::tests::TEST_F(), text_to_duration(), pq_async::money::to_num(), and pq_async::money::to_string().
s
const long double pq_async::s = 1000.0L
Referenced by pq_async::box::box(), pq_async::cb_error::c_str(), pq_async::circle::circle(), hex_to_str(), pq_async::lseg::intersect(), pq_async::interval::iso_string(), pq_async::line::line(), pq_async::lseg::lseg(), ltrim_copy(), pq_async::interval::months(), pq_async::timestamp::operator hhdate::sys_time< Dur >(), pq_async::time::operator hhdate::sys_time< Dur >(), pq_async::date::operator hhdate::year_month_day(), pq_async::timestamp_tz::operator hhdate::zoned_time< Dur >(), pq_async::time_tz::operator hhdate::zoned_time< Dur >(), pq_async::range< T >::operator std::string(), pq_async::numeric::operator std::string(), pq_async::path::operator std::string(), pq_async::polygon::operator std::string(), pq_async::point::operator*=(), pq_async::point::operator/=(), operator<<(), operator>>(), pq_async::path::path(), pgval_to_numeric(), pq_async::point::point(), pq_async::polygon::polygon(), pq_async::range< T >::range(), pq_async::database::release_savepoint(), pq_async::database::rollback_savepoint(), rtrim_copy(), pq_async::database::set_savepoint(), text_to_duration(), and trim_copy().
s_hostname
char pq_async::s_hostname[HOST_NAME_MAX]
s_machine_id
std::string pq_async::s_machine_id
Referenced by pq_async::log::machine_id().
s_pid
pid_t pq_async::s_pid
w
const long double pq_async::w = d * 7.0L
Referenced by pq_async::data_large_object::opened_write(), and text_to_duration().
y
const long double pq_async::y = d * 365.25L
Referenced by pq_async::interval::operator hhdate::sys_time< std::chrono::microseconds >(), and text_to_duration().