libpq-async++: pq_async::tests Namespace Reference
pq_async::tests Namespace Reference
Data Structures
class bin_types_test
class cash_types_test
class char_types_test
class data_prepared_test
class data_reader_test
class database_test
class date_types_test
class db_test_base
class enum_types_test
class geo_types_test
class net_types_test
class num_types_test
class pq_async_test_env
class queue_test
class range_types_test
class sys_types_test
class uuid_types_test
Functions
TEST_F (data_prepared_test, data_prepared_test)
TEST_F (data_reader_test, data_reader_sync_test)
TEST_F (data_reader_test, data_reader_sync_close_test)
TEST_F (data_reader_test, data_reader_async_test)
TEST_F (data_reader_test, data_reader_async_close_test)
TEST_F (database_test, max_connection_sync_test)
TEST_F (database_test, max_connection_async_test)
TEST_F (database_test, max_connection_async2_test)
TEST_F (queue_test, queue_test)
TEST_F (queue_test, queue_strand_test)
TEST_F (queue_test, queue_db_strand_test)
TEST_F (queue_test, queue_db_strand_test_b)
TEST_F (queue_test, queue_async_each_test)
TEST_F (queue_test, queue_async_series_test)
TEST_F (queue_test, queue_async_multithread_test)
TEST_F (bin_types_test, bin_test_bin)
std::ostream & operator<< (std::ostream &os, std::moneypunct< char >::pattern p)
TEST_F (cash_types_test, cash_test_bin)
TEST_F (char_types_test, text_test_bin)
TEST_F (char_types_test, varchar_test_bin)
TEST_F (char_types_test, char_test_bin)
TEST_F (char_types_test, insert_fetch_test_bin)
TEST_F (date_types_test, timestamp_array)
TEST_F (date_types_test, timestamp_from_bin)
TEST_F (date_types_test, timestamp_from_txt)
TEST_F (date_types_test, timestamp_tz_from_bin)
TEST_F (date_types_test, timestamp_tz_make_zoned)
TEST_F (date_types_test, timestamp_as_zone)
TEST_F (date_types_test, interval_from_bin)
TEST_F (date_types_test, date_from_bin)
TEST_F (date_types_test, time_from_bin)
TEST_F (date_types_test, time_zone_info)
TEST_F (date_types_test, time_tz_from_bin)
TEST_F (date_types_test, time_tz_make_zoned)
TEST_F (date_types_test, time_as_zone)
TEST_F (enum_types_test, enum_test_bin)
TEST_F (geo_types_test, geo_point_test_bin)
TEST_F (geo_types_test, geo_line_test_bin)
TEST_F (geo_types_test, geo_lseg_test_bin)
TEST_F (geo_types_test, geo_box_test_bin)
TEST_F (geo_types_test, geo_path_open_test_bin)
TEST_F (geo_types_test, geo_path_closed_test_bin)
TEST_F (geo_types_test, geo_polygon_test_bin)
TEST_F (geo_types_test, geo_circle_test_bin)
TEST_F (net_types_test, cidr_test_bin)
TEST_F (net_types_test, inet_test_bin)
TEST_F (net_types_test, macaddr_test_bin)
TEST_F (net_types_test, macaddr8_test_bin)
TEST_F (num_types_test, numeric_test_bin)
TEST_F (range_types_test, int4range_test_bin)
TEST_F (range_types_test, int8range_test_bin)
TEST_F (range_types_test, numrange_test_bin)
TEST_F (range_types_test, tsrange_test_bin)
TEST_F (range_types_test, tstzrange_test_bin)
TEST_F (range_types_test, daterange_test_bin)
TEST_F (sys_types_test, sys_oid_test_bin)
TEST_F (sys_types_test, sys_tid_test_bin)
TEST_F (sys_types_test, sys_xid_test_bin)
TEST_F (sys_types_test, sys_cid_test_bin)
TEST_F (sys_types_test, sys_char_test_bin)
TEST_F (sys_types_test, sys_name_test_bin)
TEST_F (uuid_types_test, uuid_test_bin)
Function Documentation
operator<<()
std::ostream& pq_async::tests::operator<< (std::ostream & os, std::moneypunct< char >::pattern p)
TEST_F() [1/61]
pq_async::tests::TEST_F (net_types_test , cidr_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [2/61]
pq_async::tests::TEST_F (num_types_test , numeric_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [3/61]
pq_async::tests::TEST_F (range_types_test , int4range_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [4/61]
pq_async::tests::TEST_F (geo_types_test , geo_point_test_bin)
References pq_async::tests::db_test_base::db, pq_async::point::x(), and pq_async::point::y().
TEST_F() [5/61]
pq_async::tests::TEST_F (date_types_test , timestamp_array)
References pq_async::tests::db_test_base::db.
TEST_F() [6/61]
pq_async::tests::TEST_F (cash_types_test , cash_test_bin)
References pq_async::d, pq_async::tests::db_test_base::db, pq_async::money::from_numeric(), pq_async::m, pq_async::money::setLocale(), and pq_async::money::to_numeric().
TEST_F() [7/61]
pq_async::tests::TEST_F (enum_types_test , enum_test_bin)
TEST_F() [8/61]
pq_async::tests::TEST_F (queue_test , queue_test)
References pq_async::event_queue::get_default(), pq_async::event_queue::push_back(), and pq_async::event_queue::run().
TEST_F() [9/61]
pq_async::tests::TEST_F (data_reader_test , data_reader_sync_test)
References pq_async::tests::db_test_base::db, and pq_async::num_to_str().
TEST_F() [10/61]
pq_async::tests::TEST_F (bin_types_test , bin_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [11/61]
pq_async::tests::TEST_F (data_prepared_test , data_prepared_test)
References pq_async::bigint, pq_async::date, pq_async::tests::db_test_base::db, and pq_async::text.
TEST_F() [12/61]
pq_async::tests::TEST_F (char_types_test , text_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [13/61]
pq_async::tests::TEST_F (database_test , max_connection_sync_test)
References pq_async::tests::db_test_base::db, pq_async::connection_pool::get_max_conn(), pq_async::num_to_str(), pq_async::database::open(), and pq_async_connection_string.
TEST_F() [14/61]
pq_async::tests::TEST_F (sys_types_test , sys_oid_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [15/61]
pq_async::tests::TEST_F (uuid_types_test , uuid_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [16/61]
pq_async::tests::TEST_F (range_types_test , int8range_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [17/61]
pq_async::tests::TEST_F (geo_types_test , geo_line_test_bin)
References pq_async::line::a(), pq_async::line::b(), pq_async::line::c(), pq_async::tests::db_test_base::db, pq_async::line::point_from_x(), and pq_async::line::point_from_y().
TEST_F() [18/61]
pq_async::tests::TEST_F (net_types_test , inet_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [19/61]
pq_async::tests::TEST_F (char_types_test , varchar_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [20/61]
pq_async::tests::TEST_F (date_types_test , timestamp_from_bin)
References pq_async::tests::db_test_base::db, and pq_async::timestamp::iso_string().
TEST_F() [21/61]
pq_async::tests::TEST_F (range_types_test , numrange_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [22/61]
pq_async::tests::TEST_F (queue_test , queue_strand_test)
References pq_async::stopwatch::elapsed(), pq_async::event_queue::get_default(), pq_async::event_queue::new_strand(), and pq_async::event_queue::run().
TEST_F() [23/61]
pq_async::tests::TEST_F (data_reader_test , data_reader_sync_close_test)
References pq_async::tests::db_test_base::db, and pq_async::num_to_str().
TEST_F() [24/61]
pq_async::tests::TEST_F (net_types_test , macaddr_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [25/61]
pq_async::tests::TEST_F (database_test , max_connection_async_test)
References pq_async::tests::db_test_base::db, pq_async::event_queue::get_default(), pq_async::connection_pool::get_max_conn(), pq_async::num_to_str(), pq_async::database::open(), pq_async_connection_string, pq_async_log_debug, and pq_async::event_queue::run().
TEST_F() [26/61]
pq_async::tests::TEST_F (char_types_test , char_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [27/61]
pq_async::tests::TEST_F (range_types_test , tsrange_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [28/61]
pq_async::tests::TEST_F (net_types_test , macaddr8_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [29/61]
pq_async::tests::TEST_F (char_types_test , insert_fetch_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [30/61]
pq_async::tests::TEST_F (sys_types_test , sys_tid_test_bin)
TEST_F() [31/61]
pq_async::tests::TEST_F (data_reader_test , data_reader_async_test)
References pq_async::tests::db_test_base::db, pq_async::event_queue::get_default(), pq_async::num_to_str(), and pq_async_log_error.
TEST_F() [32/61]
pq_async::tests::TEST_F (range_types_test , tstzrange_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [33/61]
pq_async::tests::TEST_F (queue_test , queue_db_strand_test)
References pq_async::tests::db_test_base::db, pq_async::event_queue::get_default(), and pq_async::event_queue::run().
TEST_F() [34/61]
pq_async::tests::TEST_F (date_types_test , timestamp_from_txt)
References pq_async::tests::db_test_base::db, and pq_async::timestamp::parse().
TEST_F() [35/61]
pq_async::tests::TEST_F (geo_types_test , geo_lseg_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [36/61]
pq_async::tests::TEST_F (sys_types_test , sys_xid_test_bin)
TEST_F() [37/61]
pq_async::tests::TEST_F (range_types_test , daterange_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [38/61]
pq_async::tests::TEST_F (sys_types_test , sys_cid_test_bin)
TEST_F() [39/61]
pq_async::tests::TEST_F (date_types_test , timestamp_tz_from_bin)
References pq_async::tests::db_test_base::db, pq_async::timestamp_tz::iso_string(), and pq_async::timestamp_tz::make_zoned().
TEST_F() [40/61]
pq_async::tests::TEST_F (geo_types_test , geo_box_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [41/61]
pq_async::tests::TEST_F (queue_test , queue_db_strand_test_b)
References pq_async::tests::db_test_base::db, pq_async::event_queue::get_default(), pq_async::num_to_str(), and pq_async_log_error.
TEST_F() [42/61]
pq_async::tests::TEST_F (sys_types_test , sys_char_test_bin)
TEST_F() [43/61]
pq_async::tests::TEST_F (database_test , max_connection_async2_test)
References pq_async::tests::db_test_base::db, pq_async::event_queue::get_default(), pq_async::connection_pool::get_max_conn(), pq_async::num_to_str(), pq_async::database::open(), pq_async_connection_string, and pq_async_log_debug.
TEST_F() [44/61]
pq_async::tests::TEST_F (sys_types_test , sys_name_test_bin)
TEST_F() [45/61]
pq_async::tests::TEST_F (geo_types_test , geo_path_open_test_bin)
References pq_async::path::closed(), and pq_async::tests::db_test_base::db.
TEST_F() [46/61]
pq_async::tests::TEST_F (data_reader_test , data_reader_async_close_test)
References pq_async::tests::db_test_base::db, pq_async::event_queue::get_default(), pq_async::num_to_str(), and pq_async_log_error.
TEST_F() [47/61]
pq_async::tests::TEST_F (queue_test , queue_async_each_test)
References pq_async::async::each(), pq_async::event_queue::each(), pq_async::event_queue::get_default(), and pq_async::event_queue::run().
TEST_F() [48/61]
pq_async::tests::TEST_F (geo_types_test , geo_path_closed_test_bin)
References pq_async::path::closed(), and pq_async::tests::db_test_base::db.
TEST_F() [49/61]
pq_async::tests::TEST_F (geo_types_test , geo_polygon_test_bin)
References pq_async::polygon::bound_box(), pq_async::d, pq_async::tests::db_test_base::db, pq_async::box::high(), pq_async::polygon::points(), and pq_async::point::x().
TEST_F() [50/61]
pq_async::tests::TEST_F (queue_test , queue_async_series_test)
References pq_async::event_queue::get_default(), pq_async::event_queue::run(), pq_async::async::series(), and pq_async::event_queue::series().
TEST_F() [51/61]
pq_async::tests::TEST_F (date_types_test , timestamp_tz_make_zoned)
References pq_async::tests::db_test_base::db, pq_async::timestamp::iso_string(), pq_async::timestamp_tz::iso_string(), and pq_async::timestamp_tz::make_zoned().
TEST_F() [52/61]
pq_async::tests::TEST_F (date_types_test , timestamp_as_zone)
References pq_async::timestamp::as_zone(), pq_async::tests::db_test_base::db, and pq_async::timestamp::iso_string().
TEST_F() [53/61]
pq_async::tests::TEST_F (geo_types_test , geo_circle_test_bin)
References pq_async::tests::db_test_base::db.
TEST_F() [54/61]
pq_async::tests::TEST_F (queue_test , queue_async_multithread_test)
References pq_async::event_queue::get_default(), and pq_async::event_queue::series().
TEST_F() [55/61]
pq_async::tests::TEST_F (date_types_test , interval_from_bin)
References pq_async::tests::db_test_base::db, and pq_async::interval::iso_string().
TEST_F() [56/61]
pq_async::tests::TEST_F (date_types_test , date_from_bin)
References pq_async::date, pq_async::tests::db_test_base::db, and pq_async::date::iso_string().
TEST_F() [57/61]
pq_async::tests::TEST_F (date_types_test , time_from_bin)
References pq_async::tests::db_test_base::db, and pq_async::time::iso_string().
TEST_F() [58/61]
pq_async::tests::TEST_F (date_types_test , time_zone_info)
References pq_async::duration::from_seconds().
TEST_F() [59/61]
pq_async::tests::TEST_F (date_types_test , time_tz_from_bin)
References pq_async::tests::db_test_base::db, and pq_async::time_tz::iso_string().
TEST_F() [60/61]
pq_async::tests::TEST_F (date_types_test , time_tz_make_zoned)
References pq_async::tests::db_test_base::db, pq_async::time::iso_string(), pq_async::time_tz::iso_string(), and pq_async::time_tz::make_zoned().
TEST_F() [61/61]
pq_async::tests::TEST_F (date_types_test , time_as_zone)
References pq_async::time::as_zone(), pq_async::tests::db_test_base::db, and pq_async::time::iso_string().